---
sidebar: sidebar 
permalink: hu-aix-73.html 
keywords: Host Utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: 描述如何將 IBM AIX 7.3 和/或 PowerVM VIOS 4.x 與ONTAP結合使用 
---
= 使用ONTAP儲存為 FCP 和 iSCSI 設定 AIX 7.3/VIOS 4.x
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AIX Host Utilities 軟體為連接到ONTAP儲存的 AIX 主機提供管理和診斷工具。在 AIX 7.3/VIOS 4.x 主機上安裝 AIX Host Utilities 時，您可以使用 Host Utilities 來協助您管理ONTAP LUN 的 FCP 和 iSCSI 協定操作。



== 步驟 1 ：選擇性啟用 SAN 開機

您可以設定主機以使用 SAN 啟動來簡化部署並提高可擴充性。如果您的配置不支援 SAN 啟動，您可以使用本機啟動。

[role="tabbed-block"]
====
.SAN開機
--
SAN 啟動是將 SAN 連線磁碟（LUN）設定為 AIX/PowerVM 主機的啟動設備的過程。您可以設定 SAN 啟動 LUN 以在使用 FC 協定並使用 FC 或 FCoE 協定執行 AIX Host Utilities 的 AIX 多路徑 I/O (MPIO) 環境中運作。在 AIX MPIO 環境中建立 SAN 啟動 LUN 和安裝新 OS 映像的方法取決於您使用的協定。

.步驟
. 使用link:https://mysupport.netapp.com/matrix/#welcome["互通性對照表工具"^]驗證您的 AIX OS、協定和ONTAP版本是否支援 SAN 啟動。
. 請依照供應商文件中有關設定 SAN 啟動的最佳實務進行操作。


--
.本機開機
--
透過在本機硬碟（例如 SSD、SATA 或 RAID）上安裝 AIX OS 來執行本機啟動。

--
====


== 第 2 步：安裝 AIX 主機實用程式

NetApp強烈建議安裝 AIX Host Utilities 來支援ONTAP LUN 管理並協助技術支援收集設定資料。  Host Utilities 中的 MPIO 套件為 AIX 和 VIOS 提供 MPIO 支援。


NOTE: 安裝 AIX Host Utilities 可為您的 AIX 主機提供額外的逾時設定。

link:hu-aix-80.html["安裝 AIX Host Utilities 8.0"] 。



== 步驟 3 ：確認主機的多重路徑組態

您可以使用 AIX 和 PowerVM 的多路徑來管理ONTAP LUN。

多路徑可讓您在主機和儲存系統之間配置多條網路路徑。如果一條路徑發生故障，流量仍可透過剩餘路徑繼續傳輸。  Host Utilities 的 AIX 和 PowerVM 環境使用 AIX 本機多路徑解決方案 (MPIO)。

路徑控制模組 (PCM) 負責控制 AIX 主機的多條路徑。  PCM 是儲存供應商提供的程式碼，用於處理路徑管理，在 Host Utilities 安裝期間安裝並啟用。

為確保為您的主機正確配置多路徑，請驗證您是否已為您的ONTAP LUN 設定NetApp建議的設定。

.步驟
. 驗證「MPIO NetApp」是否可用。  「MPIO NetApp」在 AIX Host Utilities 安裝期間加載，並在您重新啟動主機後可用。
+
[source, cli]
----
lsdev -Cc disk
----
+
.輸出範例
`hdisk1  Available 00-00-02 MPIO NetApp FCP Default PCM Disk`

. AIX Host Utilities 為ONTAP LUN 載入以下參數設定。
+
.顯示參數設定
[%collapsible]
====
[cols="4*"]
|===
| 參數 | 環境 | AIX的價值 | 附註 


| 演算法 | MPIO | 循環配置資源 | 由主機公用程式設定 


| h檢查_cmd | MPIO | 查詢 | 由主機公用程式設定 


| h檢查 間隔 | MPIO | 30 | 由主機公用程式設定 


| h檢查 模式 | MPIO | 非作用中 | 由主機公用程式設定 


| LUN_RESET_spt | MPIO /非MPIO | 是的 | 由主機公用程式設定 


| MAX_transfer | MPIO /非MPIO | FC LUN：0x100000位元組 | 由主機公用程式設定 


| QFUl_dly | MPIO /非MPIO | 延遲2秒 | 由主機公用程式設定 


| 佇列深度 | MPIO /非MPIO | 64 | 由主機公用程式設定 


| RESID_policy | MPIO /非MPIO | no_Reserve | 由主機公用程式設定 


| Re_timeout（磁碟） | MPIO /非MPIO | 30秒 | 使用OS預設值 


| Dyntrk | MPIO /非MPIO | 是的 | 使用OS預設值 


| FC_err_recov | MPIO /非MPIO | 快速失敗 | 使用OS預設值 


| Q_type | MPIO /非MPIO | 簡單易用 | 使用OS預設值 


| 數字_cmd | MPIO /非MPIO | 適用於AIX 3072 for VIOS的1024 | FC EN1B、FC EN1C 


| 數字_cmd | MPIO /非MPIO | 適用於AIX的1024 | FC EN0G 
|===
====
. 配置以下設定以最佳化 FC 和 iSCSI 的 I/O 操作。
+
[role="tabbed-block"]
====
.FCP
--
[cols="4*"]
|===
| 參數 | AIX 版本 | AIX OS 預設值 | NetApp建議值 


.4+| rw_timeout（磁碟） | AIX 7.3TL3 | NPIV：30秒，vSCSI：45秒 | NPIV：30秒，vSCSI：120秒 


| AIX 7.2TL5 | NPIV：30秒，vSCSI：45秒 | NPIV：30秒，vSCSI：120秒 


| VIOS 3.1 | 30秒 | 30秒 


| VIOS 4.1 | 30秒 | 30秒 
|===
--
.iSCSI
--
[cols="4*"]
|===
| 參數 | AIX 版本 | AIX OS 預設值 | NetApp建議值 


.5+| rw_timeout（磁碟） | AIX 7.3TL3 | vSCSI：45 秒 | vSCSI：120 秒 


| AIX 7.2TL5 | vSCSI：45 秒 | vSCSI：120 秒 


| VIOS 3.1 | 120秒 | 30秒 


| VIOS 4.1 | 120秒 | 30秒 


| 所有 AIX7.2 和 AIX 7.3 獨立版 | 120秒 | 30秒 


| isw_err_recov (iscsi0) | 所有 AIX7.2 和 AIX 7.3 獨立版 | 延遲失敗 | 快速失敗 
|===
--
====
. 如果您的儲存配置包括MetroCluster或SnapMirror活動同步，請變更預設設定：
+
[role="tabbed-block"]
====
.MetroCluster
--
預設情況下，當沒有可用的 LUN 路徑時，AIX OS 會強制執行較短的 I/O 逾時。這可能發生在包含單一交換器 SAN 結構的配置中以及經歷計劃外故障轉移的MetroCluster配置中。有關其他資訊和建議對預設設定進行更改，請參閱知識庫文章link:https://kb.netapp.com/on-prem/ontap/mc/MC-KBs/What_are_AIX_Host_support_considerations_in_a_MetroCluster_configuration["MetroCluster配置中的 AIX 主機支援注意事項有哪些？"^]。

--
.SnapMirror主動同步
--
從ONTAP 9.11.1 開始，AIX 主機支援SnapMirror主動同步。  AIX 配置中的主集群是「活動」集群。

在 AIX 配置中，故障轉移會造成破壞。每次故障轉移時，您都需要在主機上執行重新掃描以還原 I/O 操作。

請參閱知識庫文章link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_to_configure_AIX_Host_for_SnapMirror_active_sync_in_ONTAP["如何設定用於 SnapMirror 主動同步的 AIX 主機"^]。

--
====
. 驗證參數設定以及是否為ONTAP LUN 列出了多個路徑：
+
[source, cli]
----
lsmpio
----
+
在以下AFF或FAS系統範例中，列出了NetApp的 PCM。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
# lsmpio -l hdisk1
name    path_id  status   path_status  parent  connection

hdisk1  0        Enabled  Non          fscsi6  203200a098ba7afe,5b000000000000
hdisk1  1        Enabled  Non          fscsi8  203100a098ba7afe,5b000000000000
hdisk1  2        Enabled  Sel,Opt      fscsi6  203000a098ba7afe,5b000000000000
hdisk1  3        Enabled  Sel,Opt      fscsi8  203800a098ba7afe,5b000000000000
#
lsattr -El hdisk1
*PCM             PCM/friend/NetAppDefaultPCM Path Control Module*                     False
PR_key_value    0x6d0000000002              Persistant Reserve Key Value            True
algorithm       round_robin                 Algorithm                               True
clr_q           no                          Device CLEARS its Queue on error        True
dist_err_pcnt   0                           Distributed Error Sample Time           True
dist_tw_width   50                          Distributed Error Sample Time           True
hcheck_cmd      inquiry                     Health Check Command                    True
hcheck_interval 30                          Health Check Interval                   True
hcheck_mode     nonactive                   Health Check Mode                       True
location                                    Location Label                          True
lun_id          0x5b000000000000            Logical Unit Number ID                  False
lun_reset_spt   yes                         LUN Level Reset                         True
max_transfer    0x100000                    Maximum TRANSFER Size                   True
node_name       0x204800a098ba7afe          FC Node Name                            False
pvid            none                        Physical volume identifier              False
q_err           yes                         Use QERR bit                            True
q_type          simple                      Queuing TYPE                            True
qfull_dly       2                           Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                          Queue DEPTH                             True
reassign_to     120                         REASSIGN time out value                 True
reserve_policy  PR_shared                   Reserve Policy                          True
rw_timeout      30                          READ/WRITE time out value               True
scsi_id         0xec409                     SCSI ID                                 False
start_timeout   60                          START unit time out value               True
timeout_policy  fail_path                   Active/Passive Disk Path Control Module True
ww_name         0x203200a098ba7afe          FC World Wide Name                      False
----
====
. 驗證ONTAP LUN 的路徑狀態：
+
[source, cli]
----
sanlun lun show
----
+
以下範例輸出顯示ASA、 AFF或FAS配置中ONTAP LUN 的正確路徑狀態。

+
[role="tabbed-block"]
====
.ASA 組態
--
ASA配置最佳化了到給定 LUN 的所有路徑，使其保持活動狀態（「主要」）。透過同時透過所有路徑提供 I/O 操作，可以提高效能。

.顯示範例
[%collapsible]
=====
[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------ ------- ------ ------- --------- ----------
host   vserver  AIX                      AIX MPIO
path   path     MPIO   host    vserver     path
state  type     path   adapter LIF       priority
------ ------- ------ ------- --------- ----------
up     primary  path0  fcs0    fc_aix_1     1
up     primary  path1  fcs0    fc_aix_2     1
up     primary  path2  fcs1    fc_aix_3     1
up     primary  path3  fcs1    fc_aix_4     1
----
=====
--
.AFF 或 FAS 組態
--
AFF 或 FAS 組態應該有兩個路徑群組，優先順序較高或較低。較高優先順序的主動 / 最佳化路徑由集合所在的控制器提供服務。較低優先順序的路徑是作用中的，但未最佳化，因為它們是由不同的控制器提供服務。非最佳化路徑只有在最佳化路徑無法使用時才會使用。

以下範例顯示具有兩個主動/最佳化（「主」）路徑和兩個主動/非最佳化（「次」）路徑的ONTAP LUN 的正確輸出：

.顯示範例
[%collapsible]
=====
[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------- ---------- ------ ------- ---------- ----------
host    vserver    AIX                        AIX MPIO
path    path       MPIO   host    vserver         path
state   type       path   adapter LIF         priority
------- ---------- ------ ------- ---------- ----------
up      secondary  path0  fcs0    fc_aix_1        1
up      primary    path1  fcs0    fc_aix_2        1
up      primary    path2  fcs1    fc_aix_3        1
up      secondary  path3  fcs1    fc_aix_4        1
----
=====
--
====




== 步驟 4：查看已知問題

沒有已知問題。



== 接下來呢？

link:hu-aix-command-reference.html["了解如何使用 AIX Host Utilities 工具"] 。
