---
sidebar: sidebar 
permalink: hu-solaris-command-reference.html 
keywords: host utilities, unified, solaris, 8.0, netapp, ontap 
summary: 介紹如何將 Solaris Host Utilities 8.0 與ONTAP結合使用 
---
= 使用 Solaris Host Utilities 指令驗證ONTAP儲存配置
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用 Solaris Host Utilities 範例指令參考，透過 Host Utilities 工具對NetApp儲存配置進行端對端驗證。



== 列出所有對應至主機的主機啟動器

您可以擷取對應至主機的所有主機啟動器清單。

[source, cli]
----
sanlun fcp show adapter -v
----
[role="tabbed-block"]
====
.8.0
--
.顯示 Solaris Host Utilities 8.0 的範例
[%collapsible]
=====
[listing]
----
adapter name:      qlc0
WWPN:              2100f4e9d40fe3e0
WWNN:              2000f4e9d40fe3e0
driver name:       qlc
model:             7023303
model description: 7101674, Sun Storage 16Gb FC PCIe Universal HBA, QLogic
serial number:     463916R+1912389772
hardware version:  Not Available
driver version:    230206-5.12
firmware version:  8.08.04
Number of ports:   1 of 2
port type:         Fabric
port state:        Operational
supported speed:   4 GBit/sec, 8 GBit/sec, 16 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c4

adapter name:      qlc1
WWPN:              2100f4e9d40fe3e1
WWNN:              2000f4e9d40fe3e1
driver name:       qlc
model:             7023303
model description: 7101674, Sun Storage 16Gb FC PCIe Universal HBA, QLogic
serial number:     463916R+1912389772
hardware version:  Not Available
driver version:    230206-5.12
firmware version:  8.08.04
Number of ports:   2 of 2
port type:         Fabric
port state:        Operational
supported speed:   4 GBit/sec, 8 GBit/sec, 16 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c5
----
=====
--
.6.2
--
.顯示 Solaris Host Utilities 6.2 的範例
[%collapsible]
=====
[listing]
----
adapter name:      qlc3
WWPN:              21000024ff17a301
WWNN:              20000024ff17a301
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   1 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  32 GBit/sec
OS device name:    /dev/cfg/c7

adapter name:      qlc2
WWPN:              21000024ff17a300
WWNN:              20000024ff17a300
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   2 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c6
----
=====
--
====


== 列出所有對應至主機的LUN

您可以擷取對應至主機的所有 LUN 清單。

[source, cli]
----
sanlun lun show -p -v all
----
[role="tabbed-block"]
====
.8.0
--
.顯示 Solaris Host Utilities 8.0 的範例
[%collapsible]
=====
[listing]
----

ONTAP Path: sanboot_unix:/vol/test1/lun1
       LUN: 0
       LUN Size: 21g
       Host Device: /dev/rdsk/c0t600A098038314B314E5D574632365A51d0s2
       Mode: C
       Multipath Provider: Sun Microsystems
       Multipath Policy: Native

----
=====
--
.6.2
--
.顯示 Solaris Host Utilities 6.2 的範例
[%collapsible]
=====
[listing]
----

                    ONTAP Path: data_vserver:/vol1/lun1
                           LUN: 1
                      LUN Size: 10g
                   Host Device: /dev/rdsk/c0t600A0980383044485A3F4E694E4F775Ad0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native

----
=====
--
====


== 列出從特定SVM/中對應至主機的所有LUN、列出對應至主機之特定LUN的所有屬性

您可以從特定 SVM 檢索對應到主機的所有 LUN 的清單。

[source, cli]
----
sanlun lun show -p -v <svm_name>
----
[role="tabbed-block"]
====
.8.0
--
.顯示 Solaris Host Utilities 8.0 的範例
[%collapsible]
=====
[listing]
----
ONTAP Path: sanboot_unix:/vol/test1/lun1
       LUN: 0
       LUN Size: 20g
       Host Device: /dev/rdsk/c0t600A098038314B314E5D574632365A51d0s2
       Mode: C
       Multipath Provider: Sun Microsystems
       Multipath Policy: Native
----
=====
--
.6.2
--
.顯示 Solaris Host Utilities 6.2 的範例
[%collapsible]
=====
[listing]
----
ONTAP Path: sanboot_unix:/vol/sol_boot/sanboot_lun
                           LUN: 0
                      LUN Size: 180.0g

----
=====
--
====


== 依主機裝置檔案名稱列出 ONTAP LUN 屬性

您可以透過指定主機裝置檔案名稱來擷取所有 ONTAP LUN 屬性的清單。

[source, cli]
----
sanlun lun show all
----
[role="tabbed-block"]
====
.8.0
--
.顯示 Solaris Host Utilities 8.0 的範例
[%collapsible]
=====
[source, cli]
----
controller(7mode/E-Series)/                                         device
vserver(cDOT/FlashRay)       lun-pathname                           filename
---------------------------------------------------------------------------------------------------------------
sanboot_unix                /vol/test1/lun1                         /dev/rdsk/
c0t600A098038314B314E5D574632365A51d0s2

host adapter    protocol lun size   product
---------------------------------------------
qlc1            FCP      20g        cDOT
----
=====
--
.6.2
--
.顯示 Solaris Host Utilities 6.2 的範例
[%collapsible]
=====
[listing]
----
controller(7mode/E-Series)/                                         device
vserver(cDOT/FlashRay)       lun-pathname                           filename
---------------------------------------------------------------------------------------------------------------
sanboot_unix                 /vol/sol_193_boot/chatsol_193_sanboot /dev/rdsk/c0t600A098038304437522B4E694E4A3043d0s2

host adapter    protocol lun size   product
---------------------------------------------
qlc3            FCP      180.0g     cDOT
----
=====
--
====