---
sidebar: sidebar 
permalink: hu-veritas-7x.html 
keywords: host utilities, veritas, infoscale, 7, netapp, ontap, sanhost, iscsi, red, hat linux, oracle, linux 
summary: 提供ONTAP Veritas Infoscale 7系列版本的VMware SAN主機組態設定指引 
---
= 配置 Veritas Infoscale 7 以支援 FC、FCoE 和 iSCSI 以及ONTAP存儲
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Linux Host Utilities 軟體為連接到ONTAP儲存的 Linux 主機提供管理和診斷工具。使用 Veritas Infoscale 7 的 Linux 主機實用程序，支援 Oracle Linux（基於 Red Hat 相容核心）、Red Hat Enterprise Linux (RHEL) 和 SUSE Linux Enterprise Server 主機，以支援使用ONTAP LUN 管理 FC、FCoE 和 iSCSI 協定作業。



== 步驟 1 ：選擇性啟用 SAN 開機

您可以將主機設定為使用 SAN 開機，以簡化部署並改善擴充性。

.開始之前
* 使用link:https://mysupport.netapp.com/matrix/#welcome["互通性對照表工具"^]驗證您的 Linux 作業系統，主機匯流排介面卡（ HBA ）， HBA 韌體， HBA 開機 BIOS 和 ONTAP 版本是否支援 SAN 開機。
* 請參閱 Veritas 支援入口網站（產品矩陣、平台查找和 HCL 矩陣）以驗證 SAN 啟動配置支援和已知問題。


.步驟
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["建立 SAN 啟動 LUN 並將其對應到主機"^]。
. 在伺服器BIOS中為SAN開機LUN對應的連接埠啟用SAN開機。
+
如需如何啟用HBA BIOS的相關資訊、請參閱廠商專屬的文件。

. 重新啟動主機並驗證作業系統是否正常運作，以確認組態是否成功。




== 步驟 2 ：安裝 Linux 主機公用程式

NetApp強烈推薦 link:hu-luhu-release-notes.html["安裝 Linux 主機實用程式"] 支援ONTAP LUN 管理，並協助技術支援收集配置資料。


NOTE: 安裝 Linux 主機公用程式不會變更 Linux 主機上的任何主機逾時設定。



== 步驟 3：確認主機上的 Veritas 動態多路徑配置

使用 Veritas 動態多路徑 (VxDMP) 和 Veritas Infoscale 7 來管理ONTAP LUN。

為確保 VxDMP 已正確配置到您的主機上，您需要驗證 VxDMP 配置，並檢查陣列支援庫 (ASL) 和陣列策略模組 (APM) 配置。NetApp儲存系統的 ASL 和 APM 軟體包是在 Veritas 軟體安裝過程中安裝的。


NOTE: 對於異質多路徑環境，包括 Veritas Infoscale、Linux Native Device Mapper 和 LVM 磁碟區管理器，請參閱 Veritas 產品管理文件以了解設定。

.開始之前
請確保您的配置符合系統需求。參見 link:https://mysupport.netapp.com/matrix/#welcome["互通性對照表工具"^] 以及 Veritas HCL 矩陣。

.步驟
. 確認ONTAP目標陣列已連接到 VxDMP 多路徑：
+
[source, cli]
----
vxdmpadm
----
+
.顯示範例
[%collapsible]
====
[listing]
----
# vxdmpadm listenclosure
ENCLR_NAME   ENCLR_TYPE  ENCLR_SNO     STATUS      ARRAY_TYPE    LUN_COUNT    FIRMWARE
=====================================================================================
sfrac0       SFRAC       804Xw$PqE52h  CONNECTED   ALUA          43           9800
# vxdmpadm getdmpnode
NAME       STATE    ENCLR-TYPE  PATHS  ENBL  DSBL ENCLR-NAME
===================================================================
sfrac0_47  ENABLED  SFRAC       4      4     0    sfrac0
----
====
. 檢查 ASL 和 APM 軟體包的配置。NetApp建議您使用 Veritas 支援入口網站上列出的最新支援軟體包。
+
.展示 ASL 和 APM 設定範例
[%collapsible]
====
[listing]
----
# vxdmpadm list dmpnode dmpnodename=sfrac0_47 | grep asl
asl        = libvxnetapp.so
# vxddladm listversion |grep libvxnetapp.so
libvxnetapp.so                  vm-8.0.0-rev-1   8.0

# rpm -qa |grep VRTSaslapm
VRTSaslapm-x.x.x.0000-RHEL8.X86_64
vxddladm listsupport libname=libvxnetapp.so
ATTR_NAME   ATTR_VALUE
=========================================
LIBNAME     libvxnetapp.so
VID         NETAPP
PID         All
ARRAY_TYPE  ALUA, A/A
----
====
. 為了在儲存故障轉移操作中獲得最佳系統配置，請確認您已設定以下 Veritas VxDMP 可調參數：
+
[cols="2*"]
|===
| 參數 | 設定 


| DMP_LUN_Retry逾時 | 60 


| DMP_path_age | 120 


| DMP_還原 時間間隔 | 60 
|===
. 將DMP可調參數設定為線上：
+
[source, cli]
----
# vxdmpadm settune dmp_tunable=value
----
. 確認可調參數設定是否正確：
+
[source, cli]
----
# vxdmpadm gettune
----
+
以下範例顯示了 SAN 主機上有效的 VxDMP 可調參數。

+
.顯示範例
[%collapsible]
====
[listing]
----
# vxdmpadm gettune

Tunable                    Current Value    Default Value
dmp_cache_open                      on                on
dmp_daemon_count                    10                10
dmp_delayq_interval                 15                15
dmp_display_alua_states             on                on
dmp_fast_recovery                   on                on
dmp_health_time                     60                60
dmp_iostats_state              enabled           enabled
dmp_log_level                        1                 1
dmp_low_impact_probe                on                on
dmp_lun_retry_timeout               60                30
dmp_path_age                       120               300
dmp_pathswitch_blks_shift            9                 9
dmp_probe_idle_lun                  on                on
dmp_probe_threshold                  5                 5
dmp_restore_cycles                  10                10
dmp_restore_interval                60               300
dmp_restore_policy         check_disabled   check_disabled
dmp_restore_state              enabled           enabled
dmp_retry_count                      5                 5
dmp_scsi_timeout                    20                20
dmp_sfg_threshold                    1                 1
dmp_stat_interval                    1                 1
dmp_monitor_ownership               on                on
dmp_monitor_fabric                  on                on
dmp_native_support                 off               off
----
====
. 配置協定逾時值：
+
[role="tabbed-block"]
====
.FC/FCoE
--
使用 FC 和 FCoE 的預設逾時值。

--
.iSCSI
--
設定 `replacement_timeout` 參數值設為 120。

iSCSI `replacement_timeout` 此參數控制 iSCSI 層在逾時路徑或會話重新建立之前應等待多長時間，然後再拒絕對其執行任何命令。NetApp建議設定以下值： `replacement_timeout` 在 iSCSI 設定檔中設定為 120。

[source, cli]
----
# grep replacement_timeout /etc/iscsi/iscsid.conf
node.session.timeo.replacement_timeout = 120
----
--
====
. 設定 RHEL 8 和 9 系列主機的主機「udev rport」值，以支援 Veritas Infoscale 環境在儲存故障轉移場景中的運作。
+
透過建立檔案來配置“udev rport”值 `/etc/udev/rules.d/40-rport.rules` 文件內容如下：

+
[listing]
----
# cat /etc/udev/rules.d/40-rport.rules
KERNEL=="rport-*", SUBSYSTEM=="fc_remote_ports", ACTION=="add", RUN+=/bin/sh -c 'echo 20 > /sys/class/fc_remote_ports/%k/fast_io_fail_tmo;echo 864000 >/sys/class/fc_remote_ports/%k/dev_loss_tmo'"
----
+

NOTE: 有關 Veritas 的所有其他特定設置，請參閱 Veritas Infoscale 標準產品文件。

. 驗證 ONTAP LUN 的參數設定和路徑狀態：
+
在AFF、 FAS或ASA組態中，單一ONTAP LUN 不應需要超過四條路徑。儲存故障時，超過四條路徑都可能導致問題。

+
以下範例顯示了ASA、 AFF或FAS配置中ONTAP LUN 的正確參數設定和路徑狀態。

+
[role="tabbed-block"]
====
.ASA 組態
--
ASA 組態可最佳化通往指定 LUN 的所有路徑，使其保持作用中。如此可同時透過所有路徑提供 I/O 作業、進而提升效能。

.顯示範例
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED (A)    Active/Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A) Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED (A)    Active/Optimized c14   SFRAC       sfrac0     -
----
=====
--
.AFF 或 FAS 組態
--
AFF 或 FAS 組態應該有兩個路徑群組，優先順序較高或較低。較高優先順序的主動 / 最佳化路徑由集合所在的控制器提供服務。較低優先順序的路徑是作用中的，但未最佳化，因為它們是由不同的控制器提供服務。非最佳化路徑只有在最佳化路徑無法使用時才會使用。

以下範例顯示 ONTAP LUN 的輸出，其中包含兩個主動 / 最佳化路徑和兩個主動 / 非最佳化路徑：

.顯示範例
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED     Active/Non-Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED     Active/Non-Optimized c14   SFRAC       sfrac0     -      -
----
=====
--
====




== 第四步：已知問題

沒有已知問題。



== 接下來呢？

* link:hu-luhu-command-reference.html["瞭解如何使用 Linux 主機公用程式工具"] 。

