---
sidebar: sidebar 
permalink: hu-wuhu-80.html 
keywords: windows, 7.2, host utilities, SAN, windows 
summary: Windows Host Utilities 包含一個安裝程序，該程序設定所需的 Windows 登錄和 HBA 參數，以便 Windows 主機正確處理ONTAP平台的儲存系統行為。 
---
= 為ONTAP儲存安裝 Windows Host Utilities 8.0
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Windows 主機公用程式可讓您將 Windows 主機電腦連接至 NetApp 儲存系統。

Windows 主機公用程式支援下列 Windows 版本：

* Windows 2025
* Windows 2022
* Windows 2019
* Windows 2016


Windows Host Utilities 包含一個安裝程序，該程序設定所需的 Windows 登錄機碼和主機匯流排適配器 (HBA) 參數，以便 Windows 主機可以正確處理ONTAP平台的儲存系統行為。

安裝 Host Utilities 軟體時、安裝程式會設定所需的 Windows 登錄和 HBA 參數。

下列程式和檔案會安裝在Windows主機電腦上。預設目錄為「C:\Program Files\NetApp\Windows Host Utilities」。

|===
| 方案 | 目的 


| 「\NetAppQCLi\fcconfig.exe」 | 由安裝程式用來設定 HBA 參數。 


| 「\NetAppQCLI/fcconfig.ini`」 | 由安裝程式用來設定 HBA 參數。 


| 「an版本」 | 顯示主機公用程式和 FC HBA 的版本。 
|===
主機公用程式支援不同的 Windows 主機組態、通訊協定和多重路徑選項。如需詳細資訊，請參閱 https://mysupport.netapp.com/matrix/["互通性對照表工具"^]。



== 步驟 1：驗證主機和儲存系統配置

在安裝 Windows Host Utilities 之前，請先驗證您的主機和儲存系統配置是否受支援<<supported-windows-versions-80,支援的 Windows 版本>>。

.步驟
. 檢查中支援的組態 http://mysupport.netapp.com/matrix["互通性對照表工具"^]。
. 檢查 Windows Server 主機版本所需的修補程序link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["SAN主機Windows文件"]。
+
例如，link:https://docs.netapp.com/us-en/ontap-sanhost/hu-windows-2025.html["為 ONTAP 儲存設備設定 Windows Server 2025"]文件提供了 Windows Server 2025 安裝 Windows 修補程式的說明。

. link:https://docs.netapp.com/us-en/ontap/san-admin/verify-license-fc-iscsi-task.html["新增 iSCSI 或 FCP 許可證"^] 。
. 啟動目標服務。
. 驗證您的纜線。
+
請參閱 https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN組態參考"^]了解詳細的佈線和配置資訊。





== 步驟 2：設定 FC HBA 和交換機

安裝及設定一或多個支援的 FC 主機匯流排介面卡（ HBA ）、以便 FC 連線至儲存系統。

Windows 主機公用程式安裝程式會設定所需的 FC HBA 設定。


CAUTION: 您應該只允許 Windows Host Utilities 安裝程式設定 HBA 參數。這可確保 Windows 主機能夠正確處理ONTAP平台的儲存系統行為。

.步驟
. 根據 HBA 廠商提供的指示、安裝一或多個支援的 FC HBA 。
. 取得支援的HBA驅動程式和管理公用程式、並依照HBA廠商提供的指示進行安裝。
. https://docs.netapp.com/us-en/ontap/san-management/index.html["將 HBA 連接到 FC 交換器或直接連接到儲存系統"^] 。
. https://docs.netapp.com/us-en/ontap/san-config/fibre-channel-fcoe-zoning-concept.html["根據 FC 交換器文件在 FC 交換器上建立區域"^] 。
. 對於ONTAP，按 WWPN 對交換器進行區域劃分。請務必使用邏輯介面 (LIF) 的 WWPN，而不是儲存控制器上的實體連接埠的 WWPN。請參閱 https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN組態參考"^]了解更多。




== 步驟 3：安裝 Windows 主機實用程式

安裝程式安裝 Windows Host Utilities 套件並設定 Windows 註冊表和 HBA 設定。

.關於這項工作
您可以選擇在安裝 Windows Host Utilities 軟體包時包含多路徑支援。安裝程式會提示您選擇以下選項：

* 選擇 `MPIO` 如果從 Windows 主機或虛擬機器到儲存系統有多條路徑、
* 選擇 `no MPIO`僅當您使用儲存系統的單一路徑時。


您也可以使用 Windows 命令列提示符號選擇多路徑支援。

對於 Hyper-V 用戶機，如果您選擇多路徑支持，則原始（直通）磁碟不會出現在客戶機作業系統中。您可以使用原始磁碟或 MPIO，但不能在來賓作業系統中同時使用它們。


CAUTION: 如果您不安裝 MPIO 軟體， Windows 作業系統可能會將每個路徑視為獨立的磁碟。這可能導致資料毀損。


NOTE: 在 Hyper-V 虛擬機器中執行的 Windows XP 或 Windows Vista 不支援 MPIO 。

.步驟
您可以互動方式或使用 Windows 命令列安裝主機實用程式。新的 Host Utilities 安裝套件必須位於 Windows 主機可存取的路徑中。

[role="tabbed-block"]
====
.以互動方式安裝
--
透過執行安裝程式並依照指示以互動方式安裝 Windows Host Utilities 軟體包。

. 從下載可執行文件 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/8.0/downloads["NetApp 支援網站"^]。
. 變更至您下載執行檔的目錄。
. 運行 `netapp_windows_host_utilities_8.0.0_x64`文件並按照螢幕上的指示進行操作。
. 出現提示時、重新啟動Windows主機。


--
.非交互安裝
--
使用 Windows 命令列執行 Host Utilities 的非互動式安裝。安裝完成後系統自動重新啟動。

. 在 Windows 命令提示字元中輸入下列命令：
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` 為的名稱 `.msi` 適用於您 CPU 架構的檔案。
** 多重路徑會指定是否安裝MPIO支援。允許的值為「 0 」表示「否」、「 1 」表示「是」。
** 「inst_path」是安裝主機公用程式檔案的路徑。預設路徑為「C:\Program Files\NetApp\Windows Host Utilities」。





NOTE: 若要查看記錄和其他功能的標準 Microsoft Installer （ MSI ）選項、請輸入 `msiexec /help` 在 Windows 命令提示字元下。例如、 `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` 命令會顯示記錄資訊。

--
====


== 接下來呢？

link:hu-wuhu-configuration.html["了解ONTAP儲存的 Windows 主機實用程式配置"]
