---
sidebar: sidebar 
permalink: hu_aix_72_sanbooting_aix.html 
keywords: host utilities, aix, netapp, ontap, configure, discover, configuring, discovering 
summary: 說明如何使用AIX探索及設定LUN 
---
= （不含PowerVM的AIX MPIO）使用AIX探索及設定LUN
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
當您使用沒有PowerVM的AIX時、可以使用cfgmgr命令 讓主機探索LUN。您不需要重新啟動主機即可探索LUN。若要確認主機已探索到LUN、您可以使用sanlun公用程式。


NOTE: 後續步驟不適用於執行PowerVM環境的主機。

.步驟
. 以root身分登入主機。
. 在AIX主機上、輸入下列命令以探索新建立的LUN：
+
《cfgmgr'》

+
「cfgmgr'命令有助於：

+
** 用於登入Fabric的啟動器。
** 用於檢查新裝置的系統。
** 用於建立新裝置項目的系統。


. 若要顯示所有的AIX磁碟、包括NetApp LUN、請輸入下列命令：
+
「lsdev-Cc disk」

+
LUN在主機上顯示為磁碟。您可以使用這些磁碟、就像使用主機上的本機磁碟一樣。主機設定安裝為主機公用程式一部分的ODM檔案會使LUN顯示為NetApp FCP磁碟。

+
記下hdisk執行個體編號。您可以在執行路徑組態時使用它們。

+
以下是lsdev-Cc disk命令在使用FC的環境中產生的輸出類型。

+
[listing]
----
# lsdev -Cc disk
hdisk0 Available 08-08-00-5,0 16 Bit LVD SCSI Disk Drive
hdisk1 Available 08-08-00-8,0 16 Bit LVD SCSI Disk Drive
hdisk2 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk3 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk4 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk5 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
----
. 輸入下列命令以取得設定的相關資訊：
+
《lsattr -EL hdisk_name》

+
此命令會產生下列輸出。

+
[listing]
----
# lsattr -El hdisk65
PCM   PCM/friend/NetApp   PCM Path Control Module          False
PR_key_value    none                             Persistant Reserve Key Value            True
algorithm       round_robin                      Algorithm                               True
clr_q           no                               Device CLEARS its Queue on error        True
dist_err_pcnt   0                                Distributed Error Sample Time           True
dist_tw_width   50                               Distributed Error Sample Time           True
hcheck_cmd      inquiry                          Health Check Command                    True
hcheck_interval 30                               Health Check Interval                   True
hcheck_mode     nonactive                        Health Check Mode                       True
location                                         Location Label                          True
lun_id          0x2000000000000                  Logical Unit Number ID                  False
lun_reset_spt   yes                              LUN Level Reset                         True
max_transfer    0x100000                         Maximum TRANSFER Size                   True
node_name       0x500a0980894ae0e0               FC Node Name                            False
pvid            00067fbad453a1da0000000000000000 Physical volume identifier              False
q_err           yes                              Use QERR bit                            True
q_type          simple                           Queuing TYPE                            True
qfull_dly       2                                Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                               Queue DEPTH                             True
reassign_to     120                              REASSIGN time out value                 True
reserve_policy  no_reserve                       Reserve Policy                          True
rw_timeout      30                               READ/WRITE time out value               True
scsi_id         0xd10001                         SCSI ID                                 False
start_timeout   60                               START unit time out value               True
ww_name         0x500a0984994ae0e0               FC World Wide Name                      False
----
. 如果您的組態支援ALUA、您可以使用它來設定路徑優先順序。確認已啟用ALUA：
+
「LUN igroup show -instance igroup_name」

+
.. 如果未啟用ALUA、請啟用它：
+
「igroup set igroup_name alua yes」



. 如果您的組態不支援ALUA、則必須執行DotPaths公用程式來設定路徑優先順序。當您安裝主機公用程式時、便會安裝DotPaths公用程式。如果啟用ALUA、請勿使用dotPaths公用程式。
+
.. 若要設定所有Data ONTAP 的LUN優先順序、請輸入：
+
"DotPaths（路徑）"

.. 若要設定特定磁碟集的優先順序、請輸入：
+
「DotPaths（-HQV）[hdiskN ...（hdiskN ...）」

+
使用「-v」選項可啟用詳細模式並顯示所有優先順序。使用「-q'」選項可查詢所有或個別的磁碟優先順序。



. 若要驗證主機是否已找到LUN、請輸入下列命令：
+
《# sanlun LUN show》（# sanlun LUN show）

+
.範例
此範例顯示MPIO多重路徑環境中「左LUN show」命令的典型輸出。

+
[listing]
----
sanlun lun show -p

                    ONTAP Path: fas3170-aix03:/vol/ibmbc_aix01b14_fcp_vol8/ibmbc-aix01b14_fcp_lun0
                           LUN: 8
                      LUN Size: 3g
           Controller CF State: Cluster Enabled
            Controller Partner: fas3170-aix04
                   Host Device: hdisk9
                          Mode: 7
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
--------- ----------- ------ ------- ---------------------------------------------- ----------
host      controller  AIX            controller                                     AIX MPIO
path      path        MPIO   host    target                                         path
state     type        path   adapter port                                           priority
--------- ----------- ------ ------- ---------------------------------------------- ----------
up        secondary   path0  fcs0    3b                                             1
up        primary     path1  fcs0    3a                                             1
up        secondary   path2  fcs0    3a                                             1
up        primary     path3  fcs0    3b                                             1
up        secondary   path4  fcs0    4b                                             1
up        secondary   path5  fcs0    4a                                             1
up        primary     path6  fcs0    4b                                             1
up        primary     path7  fcs0    4a                                             1
up        secondary   path8  fcs1    3b                                             1
up        primary     path9  fcs1    3a                                             1
up        secondary   path10 fcs1    3a                                             1
up        primary     path11 fcs1    3b                                             1
up        secondary   path12 fcs1    4b                                             1
up        secondary   path13 fcs1    4a                                             1
up        primary     path14 fcs1    4b                                             1
up        primary     path15 fcs1    4a                                             1
----

