---
sidebar: sidebar 
permalink: hu_aix_61.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: 說明如何搭配ONTAP 使用IBM AIX 7.2和/或PowerVM VIOS 3.1搭配使用 
---
= AIX主機公用程式6.1
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
AIX 統一主機公用程式可協助您管理連接至 AIX 主機的 NetApp ONTAP 儲存設備。



== SAN工具套件

AIX主機公用程式是NetApp主機軟體、可在IBM AIX主機上提供命令列工具套件。此工具套件會在您安裝NetApp主機公用程式套件時安裝。此套件提供「資源」公用程式、可協助您管理LUN和HBA。「lanlun」命令會傳回對應至主機的LUN資訊、多重路徑、以及建立啟動器群組所需的資訊。

* 範例 *

在以下範例中、「左LUN show」命令會傳回LUN資訊。

[listing]
----
#sanlun lun show all

controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: 此工具套件適用於Host Utilities的所有組態和傳輸協定。因此、部分內容會套用至一個組態、而非另一個組態。使用未使用的元件不會影響您的系統效能。


NOTE: 在AIX和PowerVM/VIOS OS版本上均支援SAN工具套件。



== 安裝AIX主機公用程式

NetApp AIX主機公用程式軟體套件可在上取得 https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host%2BUtilities%2B-%2BSAN&platform=Linux["NetApp 支援網站"^] 在壓縮的tar.gz檔案中。

您必須安裝AIX主機公用程式套件、才能將AIX MPIO與NetApp ONTAP 之間的儲存設備搭配使用。

您可以從NetApp支援網站下載包含主機公用程式軟體套件的壓縮檔案。下載檔案之後、您必須解壓縮檔案、才能取得安裝Host Utilities所需的兩個軟體套件。

*步驟*

. 登入您的主機。
+
** 在AIX主機上、以* root*登入。
** 在PowerVM主機上、以* padmin*身分登入、然後輸入OEM_setup_env命令成為root。


. 從NetApp支援網站下載包含主機公用程式的壓縮檔案複本至主機上的目錄。
. 前往內含下載內容的目錄。
. 解壓縮檔案並解壓縮SAN Toolkit軟體套件。
+
「tar -xvf ntit_AIX_host_utilitis_6.1.tar .gz」

+
解壓縮檔案時會建立下列目錄：「ntap_AIX_host_utilities _6.1」。此目錄將有下列子目錄之一：MPIO、non-MPIO或SAN_Tool_Kit。

. 安裝AIX MPIO：
+
「installp -aXYd /var/tmp_ntit_aix_host_utilities_6.1/MPIO netapp.MPIO主機公用程式套件」

. 安裝SAN工具套件：
+
「installp -aXYd /var/tmp/ntip_AIX_host_utilites_6.1/SAN_Tool_Kit NetApp.SAN_toolitu'

. 重新啟動主機。
. 驗證安裝：
+
《Anlun版本》


