---
sidebar: sidebar 
permalink: hu_aix_61.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: 說明如何搭配ONTAP 使用IBM AIX 7.2和/或PowerVM VIOS 3.1搭配使用 
---
= 安裝適用於 ONTAP 儲存設備的 AIX 主機公用程式 6.1
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AIX Host Utilities 可協助您管理連接到 AIX 主機的ONTAP儲存。  NetApp強烈建議安裝 AIX Host Utilities 來改善ONTAP儲存管理並協助NetApp支援收集有關您的配置的資訊。

AIX Host Utilities 6.1 支援以下傳輸協定和 AIX 環境：

* FC、FCoE 和 iSCSI
* AIX Microsoft 多路徑 I/O (MPIO)
* PowerVM
+
如需有關 PowerVM 的詳細資訊、請參閱 IBM PowerVM Live Partition Mobility Red Book 。



.關於這項工作
* 您需要安裝帶有 AIX MPIO 的 AIX Host Utilities SAN Toolkit 來管理連接到 AIX 主機的ONTAP儲存。
* 當您安裝 AIX Host Utilities 時，它們不會變更 AIX 主機上的任何設定。


.開始之前
* 使用link:https://mysupport.netapp.com/matrix/#welcome["互通性對照表工具"^]驗證您的 AIX OS、協定和ONTAP版本是否支援 SAN 啟動。
* 透過運行 `chdev -l <fscsi_device> -a dyntrk=ye`AIX 主機上的指令。


.步驟
. 登入您的主機。
+
[role="tabbed-block"]
====
.AIX
--
在AIX主機上、以* root*登入。

--
.PowerVM
--
在 PowerVM 主機上：

.. 以 *padmin* 登入。
.. 成為 root 用戶：
+
[source, cli]
----
oem_setup_env
----


--
====
. 前往 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads["NetApp 支援網站"^] 並將包含主機公用程式的壓縮檔案下載到主機上的目錄。
. 前往內含下載內容的目錄。
. 解壓縮檔案並解壓縮SAN Toolkit軟體套件。
+
[source, cli]
----
tar -xvf ntap_aix_host_utilities_6.1.tar.gz
----
+
解壓縮檔案時會建立下列目錄：「ntap_AIX_host_utilities _6.1」。此目錄將有下列子目錄之一：MPIO、non-MPIO或SAN_Tool_Kit。

. 安裝AIX MPIO：
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit
----
. 安裝SAN工具套件：
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit
----
. 重新啟動主機。
. 驗證安裝：
+
[source, cli]
----
sanlun version
----




== 接下來呢？

link:hu-aix-san-toolkit.html["了解 AIX SAN 工具包"] 。
