---
sidebar: sidebar 
permalink: hu_hpux_11iv3.html 
keywords: host utilities, hp_ux, 11iv3, netapp, ontap 
summary: 在 HP-UX 11i v3 主機上安裝 Linux Host Utilities 以使用ONTAP LUN 管理 FCP 和 iSCSI 協定操作。 
---
= 使用ONTAP儲存為 FCP 和 iSCSI 設定 HP-UX 11i v3
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
HP-UX Host Utilities 軟體為連接到ONTAP儲存的 HP-UX 主機提供管理和診斷工具。在 HP-UX 11i v3 主機上安裝 HP-UX Host Utilities 時，您可以使用 Host Utilities 來協助您管理ONTAP LUN 的 FCP 和 iSCSI 協定作業。



== 步驟 1 ：選擇性啟用 SAN 開機

配置您的主機以使用 SAN 啟動來簡化部署並提高可擴充性。  SAN 啟動是將 SAN 連線磁碟 (LUN) 設定為 HP-UX 主機的啟動裝置的過程。  Host Utilities 支援在 HP-UX 環境中使用 FC 和 FCoE 協定進行 SAN 引導。

.步驟
. 使用link:https://mysupport.netapp.com/matrix/#welcome["互通性對照表工具"^]驗證您的 Linux 作業系統，主機匯流排介面卡（ HBA ）， HBA 韌體， HBA 開機 BIOS 和 ONTAP 版本是否支援 SAN 開機。
. 請依照 HP-UX 供應商文件中有關設定 SAN 啟動的最佳實務進行操作。




== 步驟 2：安裝 HP-UX 主機實用程式

NetApp強烈建議安裝 HP-UX Host Utilities 來支援ONTAP LUN 管理並協助技術支援收集設定資料。

link:hu_hpux_60.html["安裝 HP-UX Host Utilities 6.0"]



== 步驟 3 ：確認主機的多重路徑組態

使用 HP-UX 11i v3 的多路徑來管理ONTAP LUN。多路徑可讓您在主機和儲存系統之間配置多條網路路徑。若一條路徑發生故障，流量仍可透過其餘路徑繼續傳輸。

安裝 HP-UX Host Utilities 後，請確認您是否已為ONTAP LUN 設定了NetApp所建議的設定。

.關於這項工作
HP-UX Host Utilities 支援本機 Microsoft 多路徑 I/O (MPIO) 和 Veritas 動態多路徑。以下步驟適用於 Native MPIO 解決方案。

.步驟
. 安裝 HP-UX Host Utilities 時，會自動為ONTAP LUN 載入以下建議的預設設定。
+
.顯示參數設定
[%collapsible]
====
[cols="2*"]
|===
| 參數 | 使用預設值 


| 暫時性_秒 | 120 


| LEG/Mpath_enable | 是的 


| MAX_q_深度 | 8. 


| 路徑_失敗_秒 | 120 


| load_bal_policy | 循環配置資源 


| Lua_enabled_ | 是的 


| ESD_SECS | 30 
|===
====
. 驗證 ONTAP LUN 的參數設定和路徑狀態：
+
[source, cli]
----
sanlun lun show
----
+
預設多路徑參數支援ASA、 AFF和FAS配置。以下範例輸出顯示了ASA、 AFF或FAS配置中ONTAP LUN 的正確參數設定和路徑狀態。

+
[role="tabbed-block"]
====
.ASA 組態
--
ASA 組態可最佳化通往指定 LUN 的所有路徑，使其保持作用中。如此可同時透過所有路徑提供 I/O 作業、進而提升效能。

.顯示範例
[%collapsible]
=====
[listing]
----
# sanlun lun show -p vs39:/vol/hpux_vol_1_1/hpux_lun

                    ONTAP Path: vs39:/vol/hpux_vol_1_1/hpux_lun
                           LUN: 2
                      LUN Size: 30g
                   Host Device: /dev/rdisk/disk25
                          Mode: C
            Multipath Provider: None
-------- ---------- -------------------- ------- --------------
host     vserver    /dev/dsk
path     path       filename             host    vserver
state    type       or hardware path     adapter LIF
-------- ---------- -------------------- ------- --------------
up       primary    /dev/dsk/c4t0d2      fcd0    248_1c_hp
up       primary    /dev/dsk/c6t0d2      fcd0    246_1c_hp
up       primary    /dev/dsk/c10t0d2     fcd1    246_1d_hp
up       primary    /dev/dsk/c8t0d2      fcd1    248_1d_hp
----
=====
--
.AFF 或 FAS 組態
--
AFF 或 FAS 組態應該有兩個路徑群組，優先順序較高或較低。較高優先順序的主動 / 最佳化路徑由集合所在的控制器提供服務。較低優先順序的路徑是作用中的，但未最佳化，因為它們是由不同的控制器提供服務。非最佳化路徑只有在最佳化路徑無法使用時才會使用。

以下範例顯示 ONTAP LUN 的輸出，其中包含兩個主動 / 最佳化路徑和兩個主動 / 非最佳化路徑：

.顯示範例
[%collapsible]
=====
[listing]
----
# sanlun lun show -p vs39:/vol/vol24_3_0/lun24_0
                    ONTAP Path: vs39:/vol/vol24_3_0/lun24_0
                           LUN: 37
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk942
                          Mode: C
              Multipath Policy: A/A
            Multipath Provider: Native
------- ---------- ------ ------- ---------- ---------- --------------
host    vserver     /dev/dsk                            HP A/A
path    path        filename          host    vserver   path failover
state   type        or hardware path adapter    LIF     priority
------- ---------- ------ ------- ---------- ---------- --------------
up       primary    /dev/dsk/c39t4d5   fcd0    hpux_3     0
up       primary    /dev/dsk/c41t4d5   fcd1    hpux_4     0
up       secondary  /dev/dsk/c40t4d5   fcd0    hpux_3     1
up       secondary  /dev/dsk/c42t4d5   fcd1    hpux_4     1
----
=====
--
====




== 步驟 4：查看已知問題

帶有ONTAP儲存版本的 HP-UX 11i v3 有以下已知問題：

[cols="4*"]
|===
| NetApp錯誤ID | 標題 | 說明 | 合作夥伴ID 


| 1447287.14 | SnapMirror 主動式同步組態中隔離主叢集上的 AUFO 事件會導致 HP-UX 主機暫時中斷 | 當 SnapMirror 主動同步組態中的隔離主叢集上發生自動非計畫性容錯移轉（ AUFO ）事件時、就會發生此問題。在HP-UX主機上恢復I/O可能需要120秒以上、但這可能不會造成任何I/O中斷或錯誤訊息。此問題會導致雙事件故障、因為主要與次要叢集之間的連線中斷、而且主要叢集與中介器之間的連線也會中斷。這是罕見的事件、與其他AUFO事件不同。 | 不適用 


| 1344935 | HP-UX 11.31 Host會在ASA 進行功能性設定時、間歇性回報路徑狀態不正確。 | 路徑報告問題ASA 與不符合需求的組態。 | 不適用 


| 1306354 | 建立HP-UX LVM會傳送超過1MB區塊大小的I/O | 在Sing All SAN Array中、SCSI傳輸長度上限為1 MB。ONTAP若要限制連接ONTAP 到Sing All SAN Array時、從HP-UX主機傳輸的最大傳輸長度、必須將HP-UX SCSI子系統允許的最大I/O大小設為1 MB。如需詳細資訊、請參閱HP-UX廠商文件。 | 不適用 
|===


== 下一步

link:hu_hpux_60_cmd.html["了解如何使用 HP-UX Host Utilities 工具"] 。
