---
sidebar: sidebar 
permalink: hu_hpux_11iv3.html 
keywords: host utilities, hp_ux, 11iv3, netapp, ontap 
summary: 說明如何搭配ONTAP 使用IBM AIX 7.2和/或PowerVM VIOS 3.1搭配使用 
---
= 將HP-UX 11i v3搭配NetApp ONTAP 功能使用
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== 安裝HP-UX主機公用程式

您可以從NetApp支援網站下載包含主機公用程式軟體套件的壓縮檔案。取得檔案後、您必須解壓縮檔案、才能取得安裝Host Utilities所需的軟體套件。

.步驟
. 從下載內含主機公用程式的壓縮檔案複本 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["NetApp 支援網站"^] 到主機上的目錄。
. 前往內含下載內容的目錄。
. 解壓縮檔案。
+
"gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz`

. 輸入下列命令以安裝軟體：
+
「winstall -s /netapp_hpux_host_utilities_6.0_ia_pa.depot netapp_santoolkit'

. 重新啟動主機。




== SAN工具套件

當您安裝NetApp主機公用程式套件時、會自動安裝此工具套件。此套件提供「資源」公用程式、可協助您管理LUN和HBA。「lanlun」命令會傳回對應至主機的LUN資訊、多重路徑、以及建立啟動器群組所需的資訊。

.範例
在以下範例中、「左LUN show」命令會傳回LUN資訊。

[listing]
----
#sanlun lun show

controller(7mode)/                            device                         host     lun
vserver(Cmode)    lun-pathname               filename                       adapter protocol  size  mode
--------------------------------------------------------------------------------
sanboot_unix      /vol/hpux_215_boot_en_0/goot_hpux_215_lun /dev/rdsk/c11t0d0 fcd0   FCP      150g   C
sanboot_unix      /vol/hpux_215_boot_en_0/goot_hpux_215_lun /dev/rdsk/c24t0d0 fcd1   FCP      150g   C
sanboot_unix      /vol/hpux_215_boot_en_0/goot_hpux_215_lun /dev/rdsk/c21t0d0 fcd1   FCP      150g   C
sanboot_unix      /vol/hpux_215_boot_en_0/goot_hpux_215_lun /dev/rdsk/c12t0d0 fcd0   FCP      150g   C
----


== SAN開機

.您需要的產品
如果您決定使用SAN開機、則組態必須支援SAN開機。您可以使用 link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["NetApp 互通性對照表工具"^] 驗證是否ONTAP 支援您的作業系統、HBA、HBA韌體和HBA開機BIOS及BIOS版本。

SAN開機是將SAN附加磁碟（LUN）設定為HP-UX主機的開機裝置的程序。主機公用程式支援在HP-UX環境中使用FC和FCoE傳輸協定進行SAN開機。



== 多重路徑

多重路徑可讓您在主機與儲存系統之間設定多個網路路徑。如果其中一條路徑故障、則其餘路徑上的流量會繼續傳輸。若要讓主機擁有多個LUN路徑、必須啟用多重路徑。HP-UX主機公用程式會根據您的組態、支援不同的多重路徑解決方案。以下是原生多路徑解決方案。



=== 非ASA組態

對於非 ASA 組態、應該有兩個路徑群組、其優先順序不同。優先順序較高的路徑為「主動/最佳化」、表示它們是由集合體所在的控制器提供服務。優先順序較低的路徑為作用中、但未最佳化、因為它們是從不同的控制器提供。未最佳化的路徑只有在沒有可用的最佳化路徑時才會使用。

.範例
下列範例顯示ONTAP 使用兩個主動/最佳化路徑和兩個主動/非最佳化路徑的正確輸出：

[listing]
----
# sanlun lun show -p vs39:/vol/vol24_3_0/lun24_0
                    ONTAP Path: vs39:/vol/vol24_3_0/lun24_0
                           LUN: 37
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk942
                          Mode: C
              Multipath Policy: A/A
            Multipath Provider: Native
------- ---------- ------ ------- ---------- ---------- --------------
host    vserver     /dev/dsk                            HP A/A
path    path        filename          host    vserver   path failover
state   type        or hardware path adapter    LIF     priority
------- ---------- ------ ------- ---------- ---------- --------------
up       primary    /dev/dsk/c39t4d5   fcd0    hpux_3     0
up       primary    /dev/dsk/c41t4d5   fcd1    hpux_4     0
up       secondary  /dev/dsk/c40t4d5   fcd0    hpux_3     1
up       secondary  /dev/dsk/c42t4d5   fcd1    hpux_4     1
----


=== 所有 SAN 陣列組態

在 ASA 組態中、通往指定 LUN 的所有路徑均為作用中且最佳化。如此可同時透過所有路徑提供 I/O 作業、進而提升效能。

.範例
下列範例顯示ONTAP 適用於某個實體LUN的正確輸出：


NOTE: 從適用於HP-UX 11iv3的32：8開始、支援所有SAN Array ASA （支援）組態ONTAP

[listing]
----
# sanlun lun show -p vs39:/vol/hpux_vol_1_1/hpux_lun

                    ONTAP Path: vs39:/vol/hpux_vol_1_1/hpux_lun
                           LUN: 2
                      LUN Size: 30g
                   Host Device: /dev/rdisk/disk25
                          Mode: C
            Multipath Provider: None
-------- ---------- -------------------- ------- --------------
host     vserver    /dev/dsk
path     path       filename             host    vserver
state    type       or hardware path     adapter LIF
-------- ---------- -------------------- ------- --------------
up       primary    /dev/dsk/c4t0d2      fcd0    248_1c_hp
up       primary    /dev/dsk/c6t0d2      fcd0    246_1c_hp
up       primary    /dev/dsk/c10t0d2     fcd1    246_1d_hp
up       primary    /dev/dsk/c8t0d2      fcd1    248_1d_hp
----


== 建議設定

以下是建議的HPUX 11i v3和NetApp ONTAP 還原LUN參數設定。NetApp使用HP-UX的預設設定。

[cols="2*"]
|===
| 參數 | 使用預設值 


| 暫時性_秒 | 120 


| LEG/Mpath_enable | 是的 


| MAX_q_深度 | 8. 


| 路徑_失敗_秒 | 120 


| load_bal_policy | 循環配置資源 


| Lua_enabled_ | 是的 


| ESD_SECS | 30 
|===


== 已知問題與限制

[cols="4*"]
|===
| NetApp錯誤ID | 標題 | 說明 | 合作夥伴ID 


| 1447287.14 | 在SMBC組態中、隔離主叢集上的AUFO事件會導致HP-UX主機暫時中斷 | 當SnapMirror營運不中斷（SMBC）組態中的隔離主叢集發生自動非計畫性容錯移轉（AUFO）事件時、就會發生此問題。在HP-UX主機上恢復I/O可能需要120秒以上、但這可能不會造成任何I/O中斷或錯誤訊息。此問題會導致雙事件故障、因為主要與次要叢集之間的連線中斷、而且主要叢集與中介器之間的連線也會中斷。這是罕見的事件、與其他AUFO事件不同。 | 不適用 


| 1344935 | HP-UX 11.31 Host會在ASA 進行功能性設定時、間歇性回報路徑狀態不正確。 | 路徑報告問題ASA 與不符合需求的組態。 | 不適用 


| 1306354 | 建立HP-UX LVM會傳送超過1MB區塊大小的I/O | 在Sing All SAN Array中、SCSI傳輸長度上限為1 MB。ONTAP若要限制連接ONTAP 到Sing All SAN Array時、從HP-UX主機傳輸的最大傳輸長度、必須將HP-UX SCSI子系統允許的最大I/O大小設為1 MB。如需詳細資訊、請參閱HP-UX廠商文件。 | 不適用 
|===