---
sidebar: sidebar 
permalink: hu_luhu_71_rn.html 
keywords: host utilities, linux, 7.1, netapp, ontap, release, notes, linux 
summary: Linux Unified Host Utilities 7.1版本資訊 
---
= Linux Unified Host Utilities 7.1版本說明
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
版本資訊說明新功能與增強功能、已知問題與限制、以及使用 ONTAP 儲存系統設定及管理特定主機的重要注意事項。

如需主機公用程式所支援之作業系統版本和更新的詳細資訊、請參閱 link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp 互通性對照表工具"^]。



== 新增功能

Linux 主機公用程式 7.1 版本包含下列新功能與增強功能：

* Linux 主機公用程式現在稱為 Linux 統一主機公用程式、因為它支援執行 SANtricity 的 NetApp E 系列儲存系統、以及執行 ONTAP 的 AFF 、 FAS 和 ASA 系統。
+

NOTE: 本文提及的任何主機公用程式或Linux主機公用程式、都是指Linux Unified Host Utilities。

* 現在支援下列作業系統：
+
** SUSE Linux Enterprise Server 15系列
** Oracle VM 3.2系列
** Oracle Linux 6和7系列
** Red Hat Enterprise Linux 6和7系列
** SUSE Linux Enterprise Server 11 SP4
** KVM和Xen、RHEV 6.4和6.5
** Citrix XenServer


* 在 Red Hat Enterprise Linux （ RHEL ） 6 和 RHEL 7 主機上、現在支援用於設定伺服器設定檔的調整套件。您可以使用 `tuned-adm` 根據環境設定不同設定檔的命令。例如、您也可以將虛擬來賓設定檔作為來賓虛擬機器、並可將企業儲存設定檔用於使用企業儲存陣列 LUN 的組態。使用這些經過調整的套件、可改善 ONTAP 的處理量和延遲。
* 增加了 Broadcom Emulex 和 Marvell Qlogic 對 32GB FC 適配器的支持。



NOTE: NetApp會繼續與Host Utilities合作、在初次發行後新增功能支援。如需支援功能及新增功能的最新資訊、請參閱 link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp 互通性對照表工具"^]。



== 已在此版本中修正

在 SUSE Linux Enterprise Server 12 SP1 、 OL 7.2 、 RHEL 7.2 和 RHEL 6.8 中執行命令時、發生間歇性主機作業系統故障問題 `sanlun lun show -p`、在此版本中已修正。



== 已知問題與限制

Linux 主機公用程式 7.1 版本有下列已知問題和限制。

[cols="10, 30, 30"]
|===
| NetApp錯誤ID | 標題 | 說明 


| 1457017 | 「anlun」安裝會發出與「libdevmapper.so」和「libnl.so」程式庫相關的警告訊息。這些警告不會影響到「暫停」套件的功能。 | 當您在 SAN 主機上執行 Linux Unified Host Utilities CLI 命令「 sanlun FCP show adapter -v 」時、命令會失敗、並顯示錯誤訊息、顯示主機匯流排介面卡（ HBA ）探索所需的程式庫相依性不可為
位於：

[root@hostname~]# sanlun FCP show adapter -v
無法找到 /usr/lib64/libHBAAPI.so 程式庫
確定安裝程式庫的套件已安裝並載入
請參閱 NetApp 線上錯誤 - link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1508554["1508554"^]。 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp線上錯誤"^] 提供大多數已知問題的完整資訊、包括可能的建議因應措施。
