---
sidebar: sidebar 
permalink: hu_luhu_71.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: 說明如何搭配ONTAP 使用Linux Unified Host Utilities 7.1搭配使用 
---
= 安裝 Linux Unified Host Utilities 7.1
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Linux 統一化主機公用程式可協助您管理連接至 Linux 主機的 NetApp ONTAP 儲存設備。NetApp 強烈建議您安裝 Linux 統一化主機公用程式、但這不是強制性的。公用程式不會變更Linux主機上的任何設定。這些公用程式可改善管理、並協助NetApp客戶支援部門收集您的組態相關資訊。

支援下列 Linux 套裝作業系統：

* Red Hat Enterprise Linux
* SUSE Linux Enterprise Server
* Oracle Linux
* Oracle VM
* Citrix XenServer


.您需要的產品
NetApp Linux Unified Host Utilities軟體套件可在上取得 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp 支援網站"^] 在32位元或64位元.rpm檔案中。

* 為了確保作業可靠、您必須確認整個iSCSI、FC或FCoE組態均受到支援。
+
您可以使用 https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp 互通性對照表工具"^] 以驗證組態。

* 您必須安裝廠商支援網站上提供的主機匯流排介面卡（ HBA ）管理套件。
+
管理軟體可讓 SAN 工具組命令收集 FC HBA 的相關資訊、例如其 WWPN 。適用於 `sanlun fcp show adapter` 命令若要運作、請確認下列套件已正確安裝：

+
** Marvell QLogic HBA – QConverteConsole CLI
** Broadcom Emulex HBA - OneCommand Manager 核心應用程式 CLI
** Marvell Brocade HBA – Brocade Command Utility CLI


* 每個 Linux 發行套件可用的 RPM 套件「 libhbaapi 」和「 libhbalinux 」應安裝在主機作業系統上。



NOTE: Linux Unified Host Utilities 軟體不支援 NVMe over Fibre Channel （ NVMe / FC ）和 NVMe over TCP （ NVMe / TCP ）主機傳輸協定。

.步驟
. 如果您目前已安裝Linux Unified Host Utilities版本、請使用下列命令將其移除：
+
[source, cli]
----
rpm -e netapp_linux_unified_host_utilities-7-1
----
+
若為舊版 Linux 主機公用程式、請移至安裝主機公用程式軟體的目錄、然後輸入 uninstall 命令以移除已安裝的套件。

. 從下載32位元或64位元Linux Unified Host Utilities軟體套件 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp 支援網站"^] 到您的主機。
. 移至您下載軟體套件的目錄、然後使用下列命令進行安裝：
+
[source, cli]
----
rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm
----
+
* 輸出範例 *

+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----
. 驗證安裝：
+
[source, cli]
----
sanlun version
----
+
* 輸出範例 *

+
[listing]
----
sanlun version 7.1.386.1644
----




== Linux 核心的建議驅動程式設定

當您設定 FC 環境時、若使用與 Linux 核心搭售的原生收件匣驅動程式、則可以使用驅動程式的預設值。



== SAN工具套件

Linux Unified Host Utilities是NetApp主機軟體、可在Linux主機上提供命令列工具套件。

當您安裝NetApp主機公用程式套件時、會自動安裝此工具套件。此套件提供「資源」公用程式、可協助您管理LUN和HBA。「lanlun」命令會傳回對應至主機的LUN資訊、多重路徑、以及建立啟動器群組所需的資訊。

.範例
在以下範例中、「左LUN show」命令會傳回LUN資訊。

[source, cli]
----
# sanlun lun show all
----
輸出範例：

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----
[NOTE]
====
* 此工具套件適用於Host Utilities的所有組態和傳輸協定。因此、部分內容會套用至一個組態、而非另一個組態。使用未使用的元件不會影響您的系統效能。
* Citrix XenServer、Oracle VM和Red Hat Enterprise Virtualization Hypervisor不支援SAN工具套件。


====