---
sidebar: sidebar 
permalink: hu_ol_85.html 
keywords: host utilities, oracle, linux, 8.5, netapp, ontap 
summary: 說明如何搭配ONTAP 使用Oracle Linux 8.5搭配使用 
---
= 搭配 ONTAP 使用 Oracle Linux 8.5
:toc: macro
:hardbreaks:
:toclevels: 1P
:allow-uri-read: 
:toc: 
:toclevels: 1P
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== 安裝Linux Unified Host Utilities

NetApp Linux Unified Host Utilities軟體套件可在上取得 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["NetApp 支援網站"^] 在64位元.rpm檔案中。

NetApp 強烈建議您安裝 Linux 統一化主機公用程式、但這不是強制性的。公用程式不會變更Linux主機上的任何設定。這些公用程式可改善管理、並協助NetApp客戶支援部門收集您的組態相關資訊。

.您需要的產品
如果您目前已安裝 Linux Unified Host Utilities 版本、您應該升級或移除該版本、然後使用下列步驟來安裝最新版本。

.步驟
. 從下載64位元Linux Unified Host Utilities軟體套件 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["NetApp 支援網站"^] 到您的主機。
. 安裝軟體套件：
+
「rpm -ivh netapp_Linux統一化_host_utilities - 7-1.x86_64」




NOTE: 您可以使用本文所提供的組態設定來設定連線至的雲端用戶端 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] 和 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX for ONTAP Sf"^]。



== SAN工具套件

當您安裝NetApp主機公用程式套件時、會自動安裝此工具套件。此套件提供「資源」公用程式、可協助您管理LUN和HBA。「lanlun」命令會傳回對應至主機的LUN資訊、多重路徑、以及建立啟動器群組所需的資訊。

.範例
在以下範例中、「左LUN show」命令會傳回LUN資訊。

[source, cli]
----
# sanlun lun show all
----
輸出範例：

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN開機

.您需要的產品
如果您決定使用SAN開機、則組態必須支援SAN開機。您可以使用 link:https://mysupport.netapp.com/matrix/imt.jsp?components=91863;&solution=1&isHWU&src=IMT["NetApp 互通性對照表工具"^] 驗證是否ONTAP 支援您的作業系統、HBA、HBA韌體和HBA開機BIOS及BIOS版本。

.步驟
. 將SAN開機LUN對應至主機。
. 確認有多個路徑可供使用。
+

NOTE: 在主機作業系統啟動並在路徑上執行後、就會有多個路徑可供使用。

. 在伺服器BIOS中為SAN開機LUN對應的連接埠啟用SAN開機。
+
如需如何啟用HBA BIOS的相關資訊、請參閱廠商專屬的文件。

. 重新啟動主機、確認開機成功。




== 多重路徑

對於Oracle Linux（OL）8.5、/etc/multipath.conf檔案必須存在、但您不需要對檔案進行特定變更。OL 8.5是以所有必要設定來編譯、以辨識及正確管理ONTAP 各種LUN。

您可以使用「multiPath -ll」命令來驗證ONTAP 您的各個LUN的設定。

以下各節提供LUN對應非ASA角色的多重路徑輸出範例。



=== 非ASA組態

對於非 ASA 組態、應該有兩個路徑群組、其優先順序不同。優先順序較高的路徑為「主動/最佳化」、表示它們是由集合體所在的控制器提供服務。優先順序較低的路徑為作用中、但未最佳化、因為它們是從不同的控制器提供。未最佳化的路徑只有在沒有可用的最佳化路徑時才會使用。

.範例
下列範例顯示ONTAP 使用兩個主動/最佳化路徑和兩個主動/非最佳化路徑的正確輸出：

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb 69:624 active ready running
| |- 16:0:5:35 sdun 66:752 active ready running
|-+- policy='service-time 0' prio=10 status=enabled
|- 15:0:0:35 sdaj 66:48 active ready running
|- 15:0:1:35 sdbx 68:176 active ready running
----

NOTE: 請勿使用過多的路徑來通往單一LUN。不需要超過四個路徑。在儲存設備故障期間、可能會有八個以上的路徑發生問題。



=== 所有 SAN 陣列組態

在 ASA 組態中、通往指定 LUN 的所有路徑均為作用中且最佳化。如此可同時透過所有路徑提供 I/O 作業、進而提升效能。

.範例
下列範例顯示ONTAP 適用於某個實體LUN的正確輸出：

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:6   sdbz 68:208  active ready running
  |- 11:0:11:6  sddn 71:80   active ready running
  |- 11:0:15:6  sdfb 129:208 active ready running
  |- 12:0:1:6   sdgp 132:80  active ready running
----

NOTE: 請勿使用過多的路徑來通往單一LUN。不需要超過4個路徑。在儲存設備故障期間、超過8個路徑可能會導致路徑問題。



== 建議設定

Oracle Linux 8.5作業系統經過編譯、可辨識ONTAP 出各種不完整的LUN、並自動針對ASA 各種版本設定正確的所有組態參數。

。 `multipath.conf` 檔案必須存在、多重路徑常駐程式才能啟動、但您可以使用下列命令來建立空的零位元組檔案：

`touch /etc/multipath.conf`

第一次建立此檔案時、您可能需要啟用和啟動多重路徑服務：

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
* 無需直接在中新增任何內容 `multipath.conf` 檔案、除非您有不想由多重路徑管理的裝置、或是現有的設定會覆寫預設值。
* 若要排除不想要的裝置、請將下列語法新增至 `multipath.conf` 檔案。
+
[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
+
更換 `<DevId>` 使用 `WWID` 要排除的裝置字串。



.範例
在此範例中、 `sda` 是我們需要新增至黑名單的本機SCSI磁碟。

.步驟
. 執行下列命令來判斷WWID：
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
. 新增 `WWID` 至中的黑名單 `/etc/multipath.conf`：
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


您應該隨時檢查 `/etc/multipath.conf` 舊版設定的檔案、尤其是在預設值區段中、可能會覆寫預設設定。

下表說明了關鍵 `multipathd` 支援的參數ONTAP 和所需的值。如果某個主機連接到其他廠商的LUN、且其中任何參數都被覆寫、則需要稍後在中的節能區段加以修正 `multipath.conf` 特別適用於ONTAP 整個LUN的檔案。如果沒有這麼做、ONTAP 則可能無法如預期般運作。只有在完全瞭解影響的情況下、才應諮詢 NetApp 和 / 或作業系統廠商、以覆寫這些預設值。

[cols="2*"]
|===
| 參數 | 設定 


| DETECT（偵測）_prio | 是的 


| 開發損失_tmo | 無限 


| 容錯回復 | 立即 


| fast_io_f故障_tmo | 5. 


| 功能 | 2 pg_init_retries 50 


| Flip_on_last刪除 | 是的 


| 硬體處理常式 | 0 


| no_path_retry | 佇列 


| path_checker_ | Tur 


| path_grouping_policy | 群組_by_prio 


| path_selector | 服務時間0 


| Polling_時間 間隔 | 5. 


| 優先 | ONTAP 


| 產品 | LUN.* 


| Retain附加的硬體處理常式 | 是的 


| RR_weight | 統一 


| 使用者易記名稱 | 否 


| 廠商 | NetApp 
|===
.範例
下列範例說明如何修正被覆寫的預設值。在這種情況下、「multiPath.conf」檔案會定義「path_checker'」和「no_path_retry」的值、這些值與ONTAP 不兼容的現象是什麼。如果因為主機仍連接其他SAN陣列而無法移除、則可針對ONTAP 具有裝置例項的LUN、特別修正這些參數。

[listing]
----
defaults {
 path_checker readsector0
 no_path_retry fail
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 no_path_retry queue
 path_checker tur
 }
}
----

NOTE: 若要設定Oracle Linux 8.5 RedHat Enterprise核心（RHCK）、請使用 link:hu_rhel_85.html#recommended-settings["建議設定"] 適用於Red Hat Enterprise Linux（RHEL）8.5。



== KVM設定

您也可以使用建議的設定來設定核心型虛擬機器（KVM）。由於LUN已對應至Hypervisor、因此無需變更KVM設定。



== 已知問題與限制

Oracle Linux 8.5沒有已知問題。


NOTE: 如需Oracle Linux（Red Hat相容核心）已知問題、請參閱 link:hu_rhel_85.html#known-problems-and-limitations["已知問題"] 相關Red Hat Enterprise Linux版本文件中的一節。
