---
sidebar: sidebar 
permalink: hu_ol_68.html 
keywords: host utilities, oracle, linux, 6.8, netapp, ontap 
summary: 說明如何搭配ONTAP 使用Oracle Linux 6.8 with介紹 
---
= 使用Oracle Linux 6.8搭配NetApp ONTAP 功能
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== 安裝Linux Unified Host Utilities

NetApp Linux Unified Host Utilities軟體套件可在上取得 link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["NetApp 支援網站"^] 在32位元和64位元的.rpm檔案中。如果您不知道哪一個檔案適合您的組態、請使用 link:https://mysupport.netapp.com/matrix/#welcome["NetApp 互通性對照表工具"^] 驗證您需要哪一個。

強烈建議安裝Linux Unified Host Utilities、但並非必要。公用程式不會變更Linux主機上的任何設定。這些公用程式可改善管理、並協助NetApp客戶支援部門收集您的組態相關資訊。

.您需要的產品
如果您目前安裝的是Linux Unified Host Utilities版本、您應該將其升級或移除、然後使用下列步驟來安裝最新版本。

. 從下載32位元或64位元Linux Unified Host Utilities軟體套件 link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["NetApp 支援網站"^] 站台到主機。
. 使用下列命令安裝軟體套件：
+
「rpm -ivh netapp_Linux統一化_host_utilities - 7-1.x86_64」




NOTE: 您可以使用本文所提供的組態設定來設定連線至的雲端用戶端 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] 和 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX for ONTAP Sf"^]。



== SAN工具套件

當您安裝NetApp主機公用程式套件時、會自動安裝此工具套件。此套件提供「資源」公用程式、可協助您管理LUN和HBA。「lanlun」命令會傳回對應至主機的LUN資訊、多重路徑、以及建立啟動器群組所需的資訊。

.範例
在以下範例中、「左LUN show」命令會傳回LUN資訊。

[listing]
----
# sanlun lun show all
----
輸出範例：

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN開機

.您需要的產品
如果您決定使用SAN開機、則組態必須支援SAN開機。您可以使用 https://mysupport.netapp.com/matrix/imt.jsp?components=74908;74907;&solution=1&isHWU&src=IMT["NetApp 互通性對照表工具"^] 驗證是否ONTAP 支援您的作業系統、HBA、HBA韌體和HBA開機BIOS及BIOS版本。

.步驟
. 將SAN開機LUN對應至主機。
. 確認有多個路徑可供使用。
+

NOTE: 在主機作業系統啟動並在路徑上執行後、就會有多個路徑可供使用。

. 在伺服器BIOS中為SAN開機LUN對應的連接埠啟用SAN開機。
+
如需如何啟用HBA BIOS的相關資訊、請參閱廠商專屬的文件。

. 重新啟動主機、確認開機成功。




== 多重路徑

對於Oracle Linux 6.8、/etc/multipath.conf檔案必須存在、但您不需要對檔案進行特定變更。Oracle Linux 6.8是以辨識及正確管理ONTAP 支援LUN所需的所有設定所編譯。若要啟用ALUA處理常式、請執行下列步驟：

.步驟
. 建立initrd-image的備份。
. 將下列參數值附加至核心、以便ALUA和非ALUA正常運作：「rdaloaddriver=scsi_d_alua」
+
....
kernel /vmlinuz-3.8.13-68.1.2.el6uek.x86_64 ro root=/dev/mapper/vg_ibmx3550m421096-lv_root rd_NO_LUKSrd_LVM_LV=vg_ibmx3550m421096/lv_root LANG=en_US.UTF-8 rd_NO_MDSYSFONT=latarcyrheb-sun16 crashkernel=256M KEYBOARDTYPE=pc KEYTABLE=us rd_LVM_LV=vg_ibmx3550m421096/lv_swap rd_NO_DM rhgb quiet rdloaddriver=scsi_dh_alua
....
. 使用「mkitrd」命令重新建立initrd-image。Oracle 6x及更新版本可使用以下命令：命令：「mkitrd -f /boot/ initrd-"uname -r"。imguname -r"或命令：「Dracut -f」
. 重新啟動主機。
. 確認的輸出 `cat /proc/cmdline` 命令以確保設定完成。您可以使用 `multipath -ll` 命令以驗證ONTAP 您的LUN的設定。應該有兩種路徑群組具有不同的優先順序。優先順序較高的路徑為「主動/最佳化」、這表示它們是由集合體所在的控制器提供服務。優先順序較低的路徑為作用中、但未最佳化、因為它們是從不同的控制器提供。未最佳化的路徑只有在沒有可用的最佳化路徑時才會使用。


.範例
下列範例顯示ONTAP 使用兩個主動/最佳化路徑和兩個主動/非最佳化路徑的正確輸出。

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 0:0:26:37 sdje 8:384   active ready running
| |- 0:0:25:37 sdik 135:64  active ready running
|-+- policy='round-robin 0' prio=10 status=enabled
  |- 0:0:18:37 sdda 70:128  active ready running
  |- 0:0:19:37 sddu 71:192  active ready running
----

NOTE: 請勿使用過多的路徑來通往單一LUN。不需要超過四個路徑。在儲存設備故障期間、可能會有八個以上的路徑發生問題。



== 建議設定

Oracle Linux 6.8作業系統經過編譯、可辨識ONTAP 出各種不完整的LUN、並自動正確設定所有組態參數。

。 `multipath.conf` 檔案必須存在、多重路徑常駐程式才能啟動、但您可以使用下列命令來建立空的零位元組檔案：

`touch /etc/multipath.conf`。

第一次建立此檔案時、可能需要啟用及啟動多重路徑服務。

[listing]
----
# chkconfig multipathd on
# /etc/init.d/multipathd start
----
* 無需直接在中新增任何內容 `multipath.conf` 除非您有不想要多重路徑管理的裝置、或現有的設定會覆寫預設值、否則請勿使用檔案。
* 您可以將下列語法新增至 `multipath.conf` 要排除不需要的裝置的檔案：
+
** 將 <DevId> 取代為您要排除的裝置 WWID 字串：
+
[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




.範例
在此範例中、 `sda` 是我們需要新增至黑名單的本機SCSI磁碟。

.步驟
. 執行下列命令來判斷WWID：
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
. 將此 WWID 新增至中的「黑名單」區段 `/etc/multipath.conf`：
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


您應該隨時檢查 `/etc/multipath.conf` 舊版設定的檔案、尤其是在預設值區段中、可能會覆寫預設設定。

下表說明了關鍵 `multipathd` 支援的參數ONTAP 和所需的值。如果主機已從其他廠商連接至 LUN 、而且這些參數中的任何一個都會被覆寫、則必須在中的稍後方例項加以修正 `multipath.conf` 特別適用於ONTAP 整個LUN的檔案。如果沒有這麼做、ONTAP 則可能無法如預期般運作。只有在完全瞭解影響的情況下、您才應諮詢 NetApp 和 / 或作業系統廠商、以覆寫這些預設值。

[cols="2*"]
|===
| 參數 | 設定 


| DETECT（偵測）_prio | 是的 


| 開發損失_tmo | "無限遠" 


| 容錯回復 | 立即 


| fast_io_f故障_tmo | 5. 


| 功能 | "3 queue_if_no_path pg_init_retries 50" 


| Flip_on_last刪除 | "是" 


| 硬體處理常式 | 「0」 


| no_path_retry | 佇列 


| path_checker_ | "周" 


| path_grouping_policy | "群組by_prio" 


| path_selector | "循環資源0" 


| Polling_時間 間隔 | 5. 


| 優先 | 「NetApp」ONTAP 


| 產品 | LUN.* 


| Retain附加的硬體處理常式 | 是的 


| RR_weight | "統一" 


| 使用者易記名稱 | 否 


| 廠商 | NetApp 
|===
.範例
下列範例說明如何修正被覆寫的預設值。在這種情況下、「multiPath.conf」檔案會定義「path_checker'」和「detect_prio'」的值、這些值與ONTAP 不相容於哪些LUN。如果因為主機仍連接其他SAN陣列而無法移除、則可針對ONTAP 具有裝置例項的LUN、特別修正這些參數。

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: 若要設定Oracle Linux 6.8 RedHat Enterprise核心（RHCK）、請使用 link:hu_rhel_68.html#recommended-settings["建議設定"] 適用於Red Hat Enterprise Linux（RHEL）6.8。



== 已知問題與限制

Oracle 6.8沒有已知問題。


NOTE: 如需Oracle Linux（Red Hat相容核心）已知問題、請參閱 link:hu_rhel_68.html#known-problems-and-limitations["已知問題"] 適用於Red Hat Enterprise Linux（RHEL）6.8。



== 版本資訊



=== ASM鏡射

自動儲存管理（ ASM ）鏡射可能需要變更 Linux 多重路徑設定、以允許 ASM 識別問題並切換至替代故障群組。大部分關於「不完整」的ASM組態ONTAP 都使用外部備援、這表示資料保護是由外部陣列提供、而ASM不會鏡射資料。某些站台使用具有一般備援的ASM來提供雙向鏡像、通常是跨不同站台。請參閱 link:https://www.netapp.com/us/media/tr-3633.pdf["Oracle資料庫ONTAP"^] 以取得更多資訊。
