---
sidebar: sidebar 
permalink: hu_rhel_84.html 
keywords: host utilities, red hat, rhel, linux, 8.4, netapp, ontap 
summary: 說明如何搭配ONTAP 使用Red Hat Enterprise Linux 8.4搭配使用功能 
---
= 搭配 ONTAP 使用 Red Hat Enterprise Linux 8.4
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用 ONTAP SAN 主機組態設定、將 Red Hat Enterprise Linux 8.4 與 ONTAP 設定為目標。



== 安裝 Linux 主機公用程式

您可以從下載 NetApp Linux 主機公用程式軟體套件作為 64-bit.rpm 檔案link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp 支援網站"^]。

NetApp 強烈建議您安裝 Linux 主機公用程式，但這不是強制性的。公用程式不會變更Linux主機上的任何設定。這些公用程式可改善管理、並協助NetApp客戶支援部門收集您的組態相關資訊。

.步驟
. 將 64 位元 Linux 主機公用程式軟體套件從下載 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp 支援網站"^]至主機。
. 安裝軟體套件：
+
「rpm -ivh netapp_Linux統一化_host_utilities - 7-1.x86_64」




NOTE: 您可以使用本文所提供的組態設定來設定連線至的雲端用戶端 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] 和 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX for ONTAP Sf"^]。



== SAN工具套件

當您安裝NetApp主機公用程式套件時、會自動安裝此工具套件。此套件提供「資源」公用程式、可協助您管理LUN和HBA。「lanlun」命令會傳回對應至主機的LUN資訊、多重路徑、以及建立啟動器群組所需的資訊。

.範例
在以下範例中、「左LUN show」命令會傳回LUN資訊。

[source, cli]
----
# sanlun lun show all
----
輸出範例：

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN開機

.開始之前
如果您決定使用SAN開機、則組態必須支援SAN開機。您可以使用link:https://imt.netapp.com/matrix/#welcome["互通性對照表工具"^]驗證是否支援 OS ， HBA ， HBA 韌體和 HBA 開機 BIOS ，以及 ONTAP 版本。

.步驟
. 將SAN開機LUN對應至主機。
. 確認有多個路徑可供使用。
+

NOTE: 在主機作業系統啟動並在路徑上執行之後，就可以使用多個路徑。

. 在伺服器BIOS中為SAN開機LUN對應的連接埠啟用SAN開機。
+
如需如何啟用HBA BIOS的相關資訊、請參閱廠商專屬的文件。

. 重新啟動主機、確認開機成功。




== 多重路徑

對於Red Hat Enterprise Linux（RHEL）8.4、必須存在/etc/multipath.conf檔案、但您不需要對檔案進行特定變更。RHEL 8.4的編譯包含所有必要設定、可辨識及正確管理ONTAP 各種LUN。

您可以使用「multiPath -ll」命令來驗證ONTAP 您的各個LUN的設定。

下列各節提供對應至 ASA 和非 ASA 角色之 LUN 的多重路徑輸出範例。



=== 所有 SAN 陣列組態

所有 SAN 陣列（ ASA ）組態都會最佳化通往指定 LUN 的所有路徑，使其保持作用中。如此可同時透過所有路徑提供 I/O 作業、進而提升效能。

.範例
以下範例顯示 ONTAP LUN 的正確輸出。

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
----

NOTE: 單一 LUN 不應需要四個以上的路徑。如果路徑超過四條，可能會在儲存設備故障期間造成路徑問題。



=== 非 ASA 組態

對於非 ASA 組態、應該有兩個路徑群組、其優先順序不同。優先順序較高的路徑為主動 / 最佳化、表示它們由集合所在的控制器提供服務。優先順序較低的路徑是作用中的、但未最佳化、因為它們是由不同的控制器提供服務。非最佳化路徑只有在最佳化路徑無法使用時才會使用。

.範例
下列範例顯示ONTAP 使用兩個主動/最佳化路徑和兩個主動/非最佳化路徑的正確輸出。

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----

NOTE: 單一 LUN 不應需要四個以上的路徑。如果路徑超過四條，可能會在儲存設備故障期間造成路徑問題。



== 建議設定

RHEL 8.4作業系統經過編譯、可辨識ONTAP 出各種不完整的LUN、並自動針對ASA 各種不適用的ASA組態、正確設定所有組態參數。

該 `multipath.conf`檔案必須存在、多重路徑常駐程式才能啟動。如果此檔案不存在，您可以使用命令建立空白的零位元組檔案 `touch /etc/multipath.conf`。

第一次建立 `multipath.conf`檔案時、您可能需要使用下列命令來啟用和啟動多重路徑服務：

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
除非您有不想要多重路徑管理的裝置、或是現有的設定會覆寫預設值、否則不需要直接將裝置新增至 `multipath.conf`檔案。您可以將下列語法新增至檔案、以您要排除的裝置 WWID 字串取代 <DevId> 、來排除不需要的 `multipath.conf`裝置：

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
在下列範例中，您將決定裝置的 WWID ，並將裝置新增至 `multipath.conf`檔案。

.步驟
. 判斷 WWID ：
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
360030057024d0730239134810c0cb833
----
+
`sda`是您要新增至黑名單的本機 SCSI 磁碟。

. 新增 `WWID` 至中的黑名單 `/etc/multipath.conf`：
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


您應該一律檢查 `/etc/multipath.conf`檔案，尤其是在「預設值」區段中，以瞭解可能會覆寫預設設定的舊版設定。

下表說明 `multipathd` ONTAP LUN 的關鍵參數及必要值。如果主機連接至其他廠商的 LUN 、且這些參數中的任何一個被覆寫、則需要在 `multipath.conf`檔案中以特定方式套用至 ONTAP LUN 的形式、在稍後加以修正。如果沒有這麼做、ONTAP 則可能無法如預期般運作。只有在完全瞭解影響的情況下、您才應諮詢 NetApp 和 / 或作業系統廠商、以覆寫這些預設值。

[cols="2*"]
|===
| 參數 | 設定 


| DETECT（偵測）_prio | 是的 


| 開發損失_tmo | "無限遠" 


| 容錯回復 | 立即 


| fast_io_f故障_tmo | 5. 


| 功能 | "2 pg_init_retries 50" 


| Flip_on_last刪除 | "是" 


| 硬體處理常式 | 「0」 


| no_path_retry | 佇列 


| path_checker_ | "周" 


| path_grouping_policy | "群組by_prio" 


| path_selector | "服務時間0" 


| Polling_時間 間隔 | 5. 


| 優先 | 「NetApp」ONTAP 


| 產品 | LUN.* 


| Retain附加的硬體處理常式 | 是的 


| RR_weight | "統一" 


| 使用者易記名稱 | 否 


| 廠商 | NetApp 
|===
.範例
下列範例說明如何修正被覆寫的預設值。在這種情況下、「multiPath.conf」檔案會定義「path_checker'」和「no_path_retry」的值、這些值與ONTAP 不兼容的現象是什麼。如果因為主機仍連接其他SAN陣列而無法移除、則可針對ONTAP 具有裝置例項的LUN、特別修正這些參數。

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----


== 設定 KVM 設定

您不需要設定核心型虛擬機器的設定，因為 LUN 會對應至 Hypervisor 。



== 已知問題

在 ONTAP 版本中、 RHEL 8.4 沒有已知問題。
