---
sidebar: sidebar 
permalink: hu_solaris_113.html 
keywords: host utilities, solaris, 113, netapp, ontap 
summary: 說明如何安裝Solaris主機公用程式 
---
= 將 Solaris 11.3 與 ONTAP 搭配使用
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用 ONTAP SAN 主機組態設定、將 Solaris 11.3 設定為 ONTAP 作為目標。



== 安裝 Solaris 主機公用程式

您可以從下載包含主機公用程式軟體套件的壓縮檔案 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["NetApp 支援網站"^]。取得檔案後、您必須將其解壓縮、才能取得安裝主機公用程式所需的軟體套件。

.步驟
. 從下載內含主機公用程式的壓縮檔案複本 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["NetApp 支援網站"^] 到主機上的目錄。
. 前往內含下載內容的目錄。
. 擷取檔案。
+
以下範例解壓縮SPARC系統的檔案。對於x86至64平台、請使用x86/x64套件。

+
「gunzip NetApp_solaris主機公用程式_6_2N20170913_0304_SPARC.Tar.gz」

. 使用「tar xvf」命令將檔案解壓縮。
+
「tar xvf netapp_solaris主機公用程式_6_2N20170913_0301_SPARC.tar」

. 將您從tar檔案擷取的套件新增至主機。
+
「pkadd -d NTAPSANTool.pkg」

+
這些套件會新增至「/opt/NTAP/SANToolkit / bin」目錄。

+
若要完成安裝、您必須使用設定環境的主機參數（本例中為 MPxIO ） `host_config` 命令。

+
「host_config」命令的格式如下：

+
/`opt/NTAP/SANToolkit / bin / host_config \<-setup>\<-protocol FCP | iscsi| mixed>\<-multipathmpxio| dmp | non（非）[-mc60 | 90| 120]

+
「host_config」命令會執行下列動作：

+
** 變更 x86 和 SPARC 系統的 Fibre Channel 和 SCSI 驅動程式設定
** 提供兩種MPxIO組態的SCSI逾時設定
** 設定VID/PID資訊
** 啟用或停用ALUA
** 設定MPxIO所使用的ALUA設定、以及x86和SPARC系統的SCSI驅動程式。


. 重新啟動主機。




== SAN工具套件

當您安裝 NetApp 主機公用程式套件時、工具套件會自動安裝。此套件提供 `sanlun` 公用程式、可協助您管理 LUN 和 HBA 。。 `sanlun` 命令會傳回對應至主機的 LUN 、多重路徑及建立啟動器群組所需的資訊。

.範例
在以下範例中、「左LUN show」命令會傳回LUN資訊。

[listing]
----
#sanlun lun show

controller(7mode)/                 device                                            host             lun
vserver(Cmode)     lun-pathname    filename                                         adapter protocol  size  mode
------------------------------------------------------------------------------------------------------
data_vserver       /vol/vol1/lun1  /dev/rdsk/c0t600A098038314362692451465A2F4F39d0s2  qlc1  FCP       60g   C
data_vserver       /vol/vol2/lun2  /dev/rdsk/c0t600A098038314362705D51465A626475d0s2  qlc1  FCP       20g   C
----


== SAN開機

.您需要的產品
如果您決定使用SAN開機、則組態必須支援SAN開機。您可以使用 link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["NetApp 互通性對照表工具"^] 驗證是否ONTAP 支援您的作業系統、HBA、HBA韌體和HBA開機BIOS及BIOS版本。

SAN開機是將SAN附加磁碟（LUN）設定為Solaris主機的開機裝置的程序。

您可以使用FC傳輸協定設定SAN開機LUN、以便在Solaris MPxIO環境中運作、並執行Solaris Host Utilities。您用來設定SAN開機LUN的方法可能會因Volume Manager和檔案系統而異。請參閱 https://docs.netapp.com/us-en/ontap-sanhost/hu_solaris_62.html["安裝 Solaris 主機公用程式"^] 如需 Solaris MPIO 環境中 SAN Booting LUN 的詳細資訊、請參閱。



== 多重路徑

多重路徑可讓您在主機與儲存系統之間設定多個網路路徑。如果其中一條路徑故障、則其餘路徑上的流量會繼續傳輸。



=== 非 ASA 組態

對於非 ASA 組態、應該有兩個路徑群組、其優先順序不同。優先順序較高的路徑為主動 / 最佳化、表示它們由集合所在的控制器提供服務。優先順序較低的路徑是作用中的、但未最佳化、因為它們是由不同的控制器提供服務。非最佳化路徑只有在最佳化路徑無法使用時才會使用。

.範例
下列範例顯示ONTAP 使用兩個主動/最佳化路徑和兩個主動/非最佳化路徑的正確輸出：

路徑優先順序會顯示在OS原生的「mpathadm show Lu <LUN>」命令中、每個LUN的「*存取狀態*」區段。



=== 所有 SAN 陣列組態

在所有 SAN 陣列（ ASA ）組態中、通往指定 LUN 的所有路徑均為作用中且最佳化。如此可同時透過所有路徑提供 I/O 作業、進而提升效能。

.範例
下列範例顯示ONTAP 適用於某個實體LUN的正確輸出：

「sanlun」命令的輸出與ASA 不適用於ASA組態的輸出相同。

路徑優先順序會顯示在OS原生的「mpathadm show Lu <LUN>」命令中、每個LUN的「*存取狀態*」區段。

[listing]
----
#sanlun lun show -pv sparc-s7-16-49:/vol/solaris_vol_1_0/solaris_lun

                    ONTAP Path: sparc-s7-16-49:/vol/solaris_vol_1_0/solaris_lun
                           LUN: 0
                      LUN Size: 30g
                   Host Device: /dev/rdsk/c0t600A098038314362692451465A2F4F39d0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native
----

NOTE: 從適用於Solaris主機的《支援所有SAN陣列ASA （EJUSTE）組態ONTAP 》（英文）的《支援所有SAN陣列（英文）》



== 建議設定

以下是建議使用NetApp ONTAP 支援LUN的Solaris 11.3 SPARC和x86_64參數設定。這些參數值由Host Utilities設定。

[cols="2*"]
|===
| 參數 | 價值 


| 節流最大值 | 8. 


| Not Ready重試次數 | 300 


| Busy_retries | 30 


| 重設重試次數 | 30 


| 節流最小值 | 2. 


| timeout_retries | 10. 


| 實體區塊大小 | 4096 
|===


=== 推薦MetroCluster 的設定

根據預設、如果通往LUN的所有路徑都遺失、則Solaris作業系統在20秒後將會失敗I/O。這是由所控制 `fcp_offline_delay` 參數。的預設值 `fcp_offline_delay` 適用於標準ONTAP 的叢集。不過MetroCluster 、在不完整的組態中、其價值是 `fcp_offline_delay` 必須增加至* 120 *、以確保I/O在作業期間不會提早逾時、包括非計畫性容錯移轉。如需更多資訊及預設設定的建議變更、請參閱知識庫文章 https://kb.netapp.com/onprem/ontap/metrocluster/Solaris_host_support_considerations_in_a_MetroCluster_configuration["Solaris主機支援MetroCluster 考量的功能"^]。



== Oracle Solaris虛擬化

* Solaris虛擬化選項包括Solaris邏輯網域（也稱為LDom或Oracle VM Server for SPARC）、Solaris動態網域、Solaris區域及Solaris Container。儘管這些技術是以非常不同的架構為基礎、但這些技術通常被重新標記為「Oracle虛擬機器」。
* 在某些情況下、可同時使用多個選項、例如特定Solaris邏輯網域內的Solaris Container。
* NetApp通常支援使用這些虛擬化技術、其中Oracle支援整體組態、且任何直接存取LUN的分割區均列於上 https://mysupport.netapp.com/matrix/imt.jsp?components=95803;&solution=1&isHWU&src=IMT["NetApp 互通性對照表"^] 支援的組態。這包括根容器、LDOM IO網域、以及使用NPIV存取LUN的LDOM。
* 僅使用虛擬化儲存資源（例如「vdsk」）的分割區和（或）虛擬機器不需要特定資格、因為它們無法直接存取NetApp LUN。只有直接存取基礎LUN的分割區/虛擬機器（例如LDOM IO網域）才能在中找到 https://mysupport.netapp.com/matrix/imt.jsp?components=95803;&solution=1&isHWU&src=IMT["NetApp 互通性對照表"^]。




=== 虛擬化的建議設定

當LUN在LDOM內作為虛擬磁碟裝置使用時、LUN的來源會被虛擬化遮罩、而LDOM將無法正確偵測區塊大小。為避免此問題、必須針對Oracle錯誤15824910修補LDOM作業系統、並建立「VDC-.conf」檔案、將虛擬磁碟的區塊大小設為4096。如需詳細資訊、請參閱Oracle Doc 2157669.1。

若要驗證修補程式、請執行下列步驟：

.步驟
. 建立zPool。
. 對zpool執行「zdb -C」、確認* ashift*的值為12。
+
如果* ashift*的值不是12、請確認已安裝正確的修補程式、然後重新檢查VDC-.conf的內容

+
在* ashift*顯示值12之前、請勿繼續。




NOTE: 可在各種版本的Solaris上取得Oracle錯誤15824910的修補程式。如果需要協助來判斷最佳核心修補程式、請聯絡Oracle。



== SnapMirror 主動同步的建議設定

為了驗證在 SnapMirror 主動式同步環境中發生非計畫性站台容錯移轉切換時、 Solaris 用戶端應用程式不會中斷運作、您必須在 Solaris 11.3 主機上設定下列設定。此設定會覆寫容錯移轉模組 `f_tpgs` 防止執行偵測到衝突的程式碼路徑。


NOTE: 從 9.9.1 開始、 ONTAP 11.3 主機支援 SnapMirror 主動式同步設定組態。

依照指示設定置換參數：

.步驟
. 建立組態檔 `/etc/driver/drv/scsi_vhci.conf` 對於連接至主機的NetApp儲存類型、輸入內容類似下列項目：
+
[listing]
----
scsi-vhci-failover-override =
"NETAPP  LUN","f_tpgs"
----
. 使用 `devprop` 和 `mdb` 用於驗證置換參數是否已成功套用的命令：
+
「root@host-a:~# devprop -v -n /scsi_vhci-vhci-容 錯移轉-置換scsi-vhci-容 錯移轉= NetApp LUN + f_tpgs root@host-a:~#回應「* scsi_vhc_structip:print -x WWNDE_info dev_child |:mdb_print siv_print siv_print siv_devi資訊列印siv_dev_mdb_devi

+
[listing]
----
svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----



NOTE: 之後 `scsi-vhci-failover-override` 已套用、 `conf` 已新增至 `svl_fops_name`。
如需其他資訊及預設設定的建議變更、請參閱NetApp知識庫文章 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Solaris_Host_support_recommended_settings_in_SnapMirror_Business_Continuity_(SM-BC)_configuration["Solaris 主機支援 SnapMirror 主動式同步組態中的建議設定"^]。



== 已知問題

Solaris 11.3 with ONTAP 版本有下列已知問題：

[cols="4*"]
|===
| NetApp錯誤ID | 標題 | 說明 | Oracle ID 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1366780["1366780"^] | x86架構上的Emulex 32G HBA在GB期間發生Solaris LIF問題 | 適用於x86_64平台上的Emulex韌體12.6.x版及更新版本 | SR 3-24746803021 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1368957["1368957"^] | Solaris 11.x 'cfgadm -c configuration' 會導致端點對端 Emulex 組態發生 I/O 錯誤 | 執行中 `cfgadm -c configure` 在 Emulex 端點對端組態上、會導致 I/O 錯誤。ONTAP 9.5P17 、 9.6P14 、 9.7P13 和 9.8P2 中已修正此問題 | 不適用 
|===