---
sidebar: sidebar 
permalink: hu_solaris_62.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: 說明如何搭配ONTAP 使用Linux Unified Host Utilities 7.1搭配使用 
---
= Solaris Host Utilities 6.2
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


.您需要的是 #8217 ；需要的是什麼
* 為了確保作業可靠、您必須確認整個iSCSI、FC或FCoE組態均受到支援。


您可以使用 link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["NetApp 互通性對照表工具"^] 以驗證組態。



== SAN工具套件

Solaris主機公用程式是NetApp主機軟體、可在Oracle Solaris主機上提供命令列工具套件。此工具套件會在您安裝NetApp主機公用程式套件時安裝。此套件提供「資源」公用程式、可協助您管理LUN和HBA。「lanlun」命令會傳回對應至主機的LUN資訊、多重路徑、以及建立啟動器群組所需的資訊。

在以下範例中、「左LUN show」命令會傳回LUN資訊。

[listing]
----
#sanlun lun show all
controller(7mode)/ device host lun
vserver(Cmode)                     lun-pathname       filename                                       adapter protocol size mode
-----------------------------------------------------------------------------------------------------------------------------------
data_vserver                     /vol/vol1/lun1     /dev/rdsk/c0t600A098038304437522B4E694E49792Dd0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol0/lun2     /dev/rdsk/c0t600A098038304437522B4E694E497938d0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol2/lun3     /dev/rdsk/c0t600A098038304437522B4E694E497939d0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol3/lun4     /dev/rdsk/c0t600A098038304437522B4E694E497941d0s2 qlc3   FCP       10g cDOT


----

NOTE: 此工具套件適用於Host Utilities的所有組態和傳輸協定。因此、部分內容會套用至一個組態、而非另一個組態。使用未使用的元件不會影響您的系統效能。



== 安裝Solaris主機公用程式

Solaris Host Utilities 6.2支援多種Solaris環境和多種傳輸協定。主要主機公用程式環境包括：

* 原生作業系統搭配MPxIO、搭配使用SPARC處理器或x8/64處理器的系統光纖通道（FC）或iSCSI傳輸協定。
* 在使用SPARC處理器的系統上搭配FC或iSCSI傳輸協定的Veritas動態多重路徑（DMP）、以及在使用x8/64處理器的系統上搭配iSCSI傳輸協定。



NOTE: NetApp Solaris主機公用程式軟體套件可在上取得 link:https://mysupport.netapp.com/site/["NetApp 支援網站"^] 以壓縮檔案格式提供給處理器。您可以從Support網站下載適用於您環境的Host Utilities軟體套件。

.步驟
. 以root身分登入主機。
. 從下載內含主機公用程式的壓縮檔案複本 link:https://mysupport.netapp.com/site/["NetApp 支援網站"^] 到主機上的目錄。
+
在準備本文件時、壓縮檔案稱為：

+
** SPARC CPU：「NetApp_solaris主機公用程式_6_2_SPARC.tar.gz」
** x86/x64 CPU：「netapp_solaris主機公用程式_6_2_amd.tar.gz」


. 前往內含下載內容的目錄。
. 使用gunzip命令解壓縮檔案
+
gunzip NetApp_solution_host_utilitutions_6_2_SPARC.tar.gz

. 解壓縮檔案。您可以使用 `tar xvf` 執行此作業的命令。
+
"# tar xvf netapp_solaris主機公用程式_6_2_SPARC.tar

. 將您從tar檔案擷取的套件新增至主機。您可以使用「pkgadd」命令來執行此作業。
+
這些套件會新增至「/opt/NTAP/SANToolkit / bin」目錄。以下範例使用「pkgadd（軟體組新增））指令來安裝Solaris安裝套件：

+
按#鍵

. 使用「pkginfo」命令或「ls - al」命令、確認工具組已成功安裝。
+
[listing]
----
# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Jul 22  2019 .
drwxr-xr-x   3 root     sys            3 Jul 22  2019 ..
drwxr-xr-x   2 root     sys            6 Jul 22  2019 bin
-r-xr-xr-x   1 root     sys       432666 Sep 13  2017 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 7962
drwxr-xr-x   2 root     sys            6 Jul 22  2019 .
drwxr-xr-x   3 root     sys            4 Jul 22  2019 ..
-r-xr-xr-x   1 root     sys      2308252 Sep 13  2017 host_config
-r-xr-xr-x   1 root     sys          995 Sep 13  2017 san_version
-r-xr-xr-x   1 root     sys      1669204 Sep 13  2017 sanlun
-r-xr-xr-x   1 root     sys          677 Sep 13  2017 vidpid.dat

# (cd /usr/share/man/man1; ls -al host_config.1 sanlun.1)
-r-xr-xr-x   1 root     sys        12266 Sep 13  2017 host_config.1
-r-xr-xr-x   1 root     sys         9044 Sep 13  2017 sanlun.1
----
. 完成後、您必須使用「/opt/ntap/SANToolkit / bin/host_config」命令來設定環境的主機參數：
+
** MPxIO
** Veritas DMP


. 驗證安裝：
+
《Anlun版本》





== 命令參考範例



=== 列出所有對應至主機的主機啟動器

[listing]
----
# sanlun fcp show adapter -v
adapter name:      qlc3
WWPN:              21000024ff17a301
WWNN:              20000024ff17a301
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   1 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  32 GBit/sec
OS device name:    /dev/cfg/c7

adapter name:      qlc2
WWPN:              21000024ff17a300
WWNN:              20000024ff17a300
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   2 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c6
----


=== 列出所有對應至主機的LUN

[listing]
----
# sanlun lun show -p -v all

                    ONTAP Path: data_vserver:/vol1/lun1
                           LUN: 1
                      LUN Size: 10g
                   Host Device: /dev/rdsk/c0t600A0980383044485A3F4E694E4F775Ad0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native

----


=== 列出從特定SVM/中對應至主機的所有LUN、列出對應至主機之特定LUN的所有屬性

[listing]
----
# sanlun lun show -p -v sanboot_unix`
ONTAP Path: sanboot_unix:/vol/sol_boot/sanboot_lun
                           LUN: 0
                      LUN Size: 180.0g

----


=== 依ONTAP 主機裝置檔案名稱列出LUN屬性

[listing]
----
# sanlun lun show all

controller(7mode/E-Series)/                                         device
vserver(cDOT/FlashRay)       lun-pathname                           filename
---------------------------------------------------------------------------------------------------------------
sanboot_unix                 /vol/sol_193_boot/chatsol_193_sanboot /dev/rdsk/c0t600A098038304437522B4E694E4A3043d0s2

host adapter    protocol lun size   product
---------------------------------------------
qlc3            FCP      180.0g     cDOT
----