---
sidebar: sidebar 
permalink: hu_solaris_62.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: 說明如何將 Solaris 主機公用程式 6.2 與 ONTAP 搭配使用 
---
= 安裝適用於 ONTAP 儲存設備的 Solaris 主機公用程式 6.2
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Solaris Host Utilities 可協助您管理連接到 Solaris 主機的ONTAP儲存並協助技術支援收集設定資料。

Solaris Host Utilities 支援多種 Solaris 環境和多種傳輸協定。以下是主要的 Solaris Host Utilities 環境：

* 使用 SPARC 處理器或 x86/64 處理器的系統上的具有 MPxIO 和光纖通道 (FC) 或 iSCSI 協定的本機作業系統。
* Veritas Dynamic Multipathing （ DMP ）搭配使用 SPARC 處理器的系統上的 FC 或 iSCSI 傳輸協定、或是使用 x86_64 處理器的系統上的 iSCSI 傳輸協定。


Solaris Host Utilities 6.2 支援以下 Solaris 系列：

* Solaris 11.x
* Solaris 10.x


.開始之前
驗證您的 iSCSI、FC 或 FCoE 配置是否受支援。您可以使用link:https://imt.netapp.com/matrix/#welcome["互通性對照表工具"^]驗證您的配置。

.步驟
. 以 root 身分登入您的主機。
. 從下載包含主機實用程式的壓縮檔案副本link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["NetApp 支援網站"^]到 Solaris 主機上的目錄：
+
[role="tabbed-block"]
====
.SPARC CPU
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
--
.x86/x64 CPU
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_amd.tar.gz
----
--
====
. 前往 Solaris 主機上包含下載內容的目錄。
. 使用解壓縮檔案 `gunzip` 命令：
+
[source, cli]
----
gunzip netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
. 使用提取文件 `tar xvf`命令：
+
[source, cli]
----
tar xvf netapp_solaris_host_utilities_6_2_sparc.tar
----
. 將你從 tar 檔案中提取的軟體包加入你的主機
+
[source, cli]
----
pkgadd
----
+
這些套件會新增至「/opt/NTAP/SANToolkit / bin」目錄。

+
以下範例使用 `pkgadd`命令來安裝 Solaris 安裝套件：

+
[source, cli]
----
pkgadd -d ./NTAPSANTool.pkg
----
. 使用以下命令之一確認工具包已成功安裝：
+
[source, cli]
----
pkginfo
----
+
[source, cli]
----
ls - al
----
+
.顯示範例輸出
[%collapsible]
====
[listing]
----
# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Jul 22  2019 .
drwxr-xr-x   3 root     sys            3 Jul 22  2019 ..
drwxr-xr-x   2 root     sys            6 Jul 22  2019 bin
-r-xr-xr-x   1 root     sys       432666 Sep 13  2017 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 7962
drwxr-xr-x   2 root     sys            6 Jul 22  2019 .
drwxr-xr-x   3 root     sys            4 Jul 22  2019 ..
-r-xr-xr-x   1 root     sys      2308252 Sep 13  2017 host_config
-r-xr-xr-x   1 root     sys          995 Sep 13  2017 san_version
-r-xr-xr-x   1 root     sys      1669204 Sep 13  2017 sanlun
-r-xr-xr-x   1 root     sys          677 Sep 13  2017 vidpid.dat

# (cd /usr/share/man/man1; ls -al host_config.1 sanlun.1)
-r-xr-xr-x   1 root     sys        12266 Sep 13  2017 host_config.1
-r-xr-xr-x   1 root     sys         9044 Sep 13  2017 sanlun.1
----
====
. 為您的 MPxIO 或 Veritas DMP 環境設定主機參數：
+
[source, cli]
----
/opt/NTAP/SANToolkit/bin/host_config
----
. 驗證安裝：
+
[source, cli]
----
sanlun version
----




== 接下來呢？

link:hu-solaris-san-toolkit.html["了解 SAN 工具包"] 。
