---
sidebar: sidebar 
permalink: hu_solaris_113.html 
keywords: host utilities, solaris, 113, netapp, ontap 
summary: 說明如何安裝 Solaris 主機公用程式 
---
= 使用ONTAP儲存為 FCP 和 iSCSI 配置 Solaris 11.3
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Solaris Host Utilities 軟體為連接到ONTAP儲存的 Solaris 主機提供管理和診斷工具。在 Solaris 11.3 主機上安裝 Solaris Host Utilities 時，您可以使用 Host Utilities 來協助您管理ONTAP LUN 的 FCP 和 iSCSI 協定作業。



== 步驟 1 ：選擇性啟用 SAN 開機

您可以設定主機以使用 SAN 啟動來簡化部署並提高可擴充性。如果您的配置不支援 SAN 啟動，您可以使用本機啟動。

[role="tabbed-block"]
====
.SAN開機
--
SAN 啟動是將 SAN 連線磁碟 (LUN) 設定為 Solaris 主機的啟動裝置的過程。您可以設定 SAN 啟動 LUN，以在使用 FC 協定並執行 Solaris Host Utilities 的 Solaris MPxIO 環境中運作。設定 SAN 啟動 LUN 的方法取決於您的磁碟區管理器和檔案系統。

.步驟
. 使用link:https://mysupport.netapp.com/matrix/#welcome["互通性對照表工具"^]驗證您的 Solaris 作業系統、協定和ONTAP版本是否支援 SAN 啟動。
. 請依照 Solaris 供應商文件中有關設定 SAN 啟動的最佳實務進行操作。


--
.本機開機
--
透過在本機硬碟上安裝 Solaris OS 執行本機引導，例如，安裝在 SSD、SATA 或 RAID 上。

--
====


== 步驟 2：安裝 Solaris 主機實用程式

NetApp強烈建議安裝 Solaris Host Utilities 來支援ONTAP LUN 管理並協助技術支援收集設定資料。


NOTE: 安裝 Solaris Host Utilities 會更改 Solaris 主機上的某些逾時設定。

link:hu_solaris_62.html["安裝 Solaris Host Utilities 6.2"] 。



== 步驟 3 ：確認主機的多重路徑組態

您可以使用 Solaris 11.3 的多路徑來管理ONTAP LUN。

多路徑可讓您在主機和儲存系統之間配置多條網路路徑。若一條路徑發生故障，流量仍可透過其餘路徑繼續傳輸。

.步驟
. Solaris Host Utilities 載入NetApp針對 SPARC 和 x86_64 處理器所建議的參數設定。
+
.顯示參數設定
[%collapsible]
====
[cols="2*"]
|===
| 參數 | 價值 


| 節流最大值 | 8. 


| Not Ready重試次數 | 300 


| Busy_retries | 30 


| 重設重試次數 | 30 


| 節流最小值 | 2. 


| timeout_retries | 10. 


| 實體區塊大小 | 4096 


| 磁碟排序 | 錯誤的 


| 快取非揮發性 | 真的 
|===
====
. 如果您的儲存配置包括MetroCluster、Oracle Solaris 虛擬化或SnapMirror活動同步，請變更預設值：
+
[role="tabbed-block"]
====
.MetroCluster
--
預設情況下，如果到 LUN 的所有路徑都遺失，Solaris OS 將在 *20 秒* 後無法執行 I/O 操作。這是由 `fcp_offline_delay`範圍。預設值為 `fcp_offline_delay`適用於標準ONTAP集群。但是，在MetroCluster配置中，您必須增加 `fcp_offline_delay`至 *120 秒*，以確保 I/O 在操作期間不會過早逾時，包括計劃外的故障轉移。

有關MetroCluster預設設定的其他資訊和建議更改，請參閱知識庫文章 https://kb.netapp.com/onprem/ontap/metrocluster/Solaris_host_support_considerations_in_a_MetroCluster_configuration["Solaris主機支援MetroCluster 考量的功能"^]。

--
.Oracle Solaris虛擬化
--
** Solaris 虛擬化選項包括 Solaris 邏輯域（也稱為 LDOM 或 Oracle VM Server for SPARC）、Solaris 動態域、Solaris 區域和 Solaris 容器。這些技術也被稱為「Oracle虛擬機器」。
** 您可以一起使用多個選項，例如，特定 Solaris 邏輯域內的 Solaris 容器。
** NetApp支援使用 Solaris 虛擬化技術，其中整體配置由 Oracle 支持，並且任何可直接存取 LUN 的分區都列在link:https://imt.netapp.com/matrix/#welcome["IMT"]在受支援的配置中。這包括根容器、LDOM I/O 域和使用 NPIV 存取 LUN 的 LDOM。
** 僅使用虛擬化儲存資源的分區或虛擬機，例如 `vdsk`，不需要特定資格，因為他們無法直接存取ONTAP LUN。您只需驗證對底層 LUN 具有直接存取權限的分割區或虛擬機器（例如 LDOM I/O 網域）是否會列在link:https://imt.netapp.com/matrix/#welcome["IMT"^]。


.步驟
當 LUN 用作 LDOM 內的虛擬磁碟設備時，LUN 的來源會被虛擬化屏蔽，且 LDOM 無法正確偵測區塊大小。為了防止此問題：

.. 為 LDOM OS 修補_Oracle Bug 15824910_
.. 創建一個 `vdc.conf`將虛擬磁碟的區塊大小設定為 `4096`。有關詳細信息，請參閱 Oracle DOC：2157669.1。
.. 驗證補丁安裝以確保已正確配置建議的設定：
+
... 建立 zpool：
+
[source, cli]
----
zpool create zpool_name disk_list
----
... 執行 `zdb -C` 檢查 zpool 並驗證 *ashift* 的值是否爲 `12`。
+
如果 *ashift* 的值不是 `12`，重新運行 `zdb -C11`，並驗證是否安裝了正確的補丁並重新檢查 `vdc.conf`。

+
直到 *ashift* 顯示值 `12`。






NOTE: 針對多個 Solaris 版本上的 Oracle 錯誤 15824910 提供了補丁。如果您需要協助確定最佳核心補丁，請聯絡 Oracle。

--
.SnapMirror主動同步
--
從ONTAP 9.9.1 開始，Solaris 主機支援SnapMirror主動同步設定配置。若要驗證在SnapMirror主動同步環境中發生排程外站點故障轉移切換時 Solaris 用戶端應用程式是否不會中斷，必須設定 `scsi-vhci-failover-override`Solaris 主機上的設定。此設定覆蓋故障轉移模組 `f_tpgs`阻止執行偵測到矛盾的程式碼路徑。

.步驟
.. 建立設定檔 `/etc/driver/drv/scsi_vhci.conf`對於連接到主機的NetApp儲存類型，其項目類似於以下範例：
+
[listing]
----
scsi-vhci-failover-override =
"NETAPP  LUN","f_tpgs"
----
.. 驗證覆蓋參數是否已成功套用：
+
[source, cli]
----
devprop
----
+
[source, cli]
----
mdb
----
+
.顯示範例
[%collapsible]
=====
[listing]
----
root@host-A:~# devprop -v -n /scsi_vhci scsi-vhci-failover-override      scsi-vhci-failover-override=NETAPP  LUN + f_tpgs
root@host-A:~# echo "*scsi_vhci_dip::print -x struct dev_info devi_child | ::list struct dev_info devi_sibling| ::print struct dev_info devi_mdi_client| ::print mdi_client_t ct_vprivate| ::print struct scsi_vhci_lun svl_lun_wwn svl_fops_name"| mdb -k
----
[listing]
----
svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----
=====



NOTE: 之後 `scsi-vhci-failover-override` 已套用、 `conf` 已新增至 `svl_fops_name`。如需更多資訊及預設設定的建議變更、請參閱 NetApp 知識庫文件 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Solaris_Host_support_recommended_settings_in_SnapMirror_Business_Continuity_(SM-BC)_configuration["Solaris 主機支援 SnapMirror 主動式同步組態中的建議設定"^]。

--
====
. 驗證使用ONTAP LUN 的 zpools 是否支援 4 KB 對齊的 I/O：
+
.. 請確認您的 Solaris 主機已安裝最新的支援儲存庫更新（SRU）：
+
[source, cli]
----
pkg info entire`
----
.. 驗證ONTAP LUN 是否具有 `ostype`作為“Solaris”，與 LUN 大小無關：
+
[source, cli]
----
lun show -vserver` <vsersver_name>
----
+
.顯示範例
[%collapsible]
====
[listing]
----
chat-a800-31-33-35-37::*> lun show -vserver solaris_fcp -path /vol/sol_195_zpool_vol_9/lun -fields ostype
vserver     path                         ostype
----------- ---------------------------- -------
solaris_fcp /vol/sol_195_zpool_vol_9/lun solaris
----
====


. 驗證ONTAP LUN 的輸出：
+
[source, cli]
----
sanlun lun show
----
+
對於ASA、 AFF或FAS配置，您應該會看到與下列範例類似的輸出：

+
.顯示範例
[%collapsible]
====
[listing]
----
root@sparc-s7-55-148:~# sanlun lun show -pv

                    ONTAP Path: Solaris_148_siteA:/vol/Triage/lun
                           LUN: 0
                      LUN Size: 20g
                   Host Device: /dev/rdsk/c0t600A098038314B32685D573064776172d0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native
----
====
. 驗證ONTAP LUN 的路徑狀態：
+
[source, cli]
----
mpathadm show lu <LUN>`
----
+
以下範例輸出顯示ASA、 AFF或FAS配置中ONTAP LUN 的正確路徑狀態。輸出中每個 LUN 的路徑優先權都顯示在「存取狀態」中。

+
[role="tabbed-block"]
====
.ASA 組態
--
ASA 組態可最佳化通往指定 LUN 的所有路徑，使其保持作用中。如此可同時透過所有路徑提供 I/O 作業、進而提升效能。

.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----
root@sparc-s7-55-82:~# mpathadm show lu /dev/rdsk/c0t600A098038313953495D58674777794Bd0s2
Logical Unit:  /dev/rdsk/c0t600A098038313953495D58674777794Bd0s2
        mpath-support:  libmpscsi_vhci.so
        Vendor:  NETAPP
        Product:  LUN C-Mode
        Revision:  9171
        Name Type:  unknown type
        Name:  600a098038313953495d58674777794b
        Asymmetric:  yes
        Current Load Balance:  round-robin
        Logical Unit Group ID:  NA
        Auto Failback:  on
        Auto Probing:  NA

        Paths:
                Initiator Port Name:  100000109bd30070
                Target Port Name:  20b9d039ea593393
                Logical Unit Number:  0
                Override Path:  NA
                Path State:  OK
                Disabled:  no

                Initiator Port Name:  100000109bd30070
                Target Port Name:  20b8d039ea593393
                Logical Unit Number:  0
                Override Path:  NA
                Path State:  OK
                Disabled:  no

                Initiator Port Name:  100000109bd3006f
                Target Port Name:  20b3d039ea593393
                Logical Unit Number:  0
                Override Path:  NA
                Path State:  OK
                Disabled:  no

                Initiator Port Name:  100000109bd3006f
                Target Port Name:  20b4d039ea593393
                Logical Unit Number:  0
                Override Path:  NA
                Path State:  OK
                Disabled:  no

        Target Port Groups:
                ID:  1003
                Explicit Failover:  no
                Access State:  *active optimized*
                Target Ports:
                        Name:  20b9d039ea593393
                        Relative ID:  8

                        Name:  20b4d039ea593393
                        Relative ID:  3

                ID:  1002
                Explicit Failover:  no
                Access State:  *active optimized*
                Target Ports:
                        Name:  20b8d039ea593393
                        Relative ID:  7

                        Name:  20b3d039ea593393
                        Relative ID:  2
----
=====
--
.AFF 或 FAS 組態
--
AFF 或 FAS 組態應該有兩個路徑群組，優先順序較高或較低。較高優先順序的主動 / 最佳化路徑由集合所在的控制器提供服務。較低優先順序的路徑是作用中的，但未最佳化，因為它們是由不同的控制器提供服務。非最佳化路徑只有在最佳化路徑無法使用時才會使用。

下列範例顯示ONTAP 使用兩個主動/最佳化路徑和兩個主動/非最佳化路徑的正確輸出：

.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----
root@chatsol-54-195:~# mpathadm show lu /dev/rdsk/c0t600A0980383044376C3F4E694E506E44d0s2
Logical Unit:  /dev/rdsk/c0t600A0980383044376C3F4E694E506E44d0s2
        mpath-support:  libmpscsi_vhci.so
        Vendor:  NETAPP
        Product:  LUN C-Mode
        Revision:  9171
        Name Type:  unknown type
        Name:  600a0980383044376c3f4e694e506e44
        Asymmetric:  yes
        Current Load Balance:  round-robin
        Logical Unit Group ID:  NA
        Auto Failback:  on
        Auto Probing:  NA

        Paths:

                Initiator Port Name:  100000109b56c5fb
                Target Port Name:  205200a098ba7afe
                Logical Unit Number:  1
                Override Path:  NA
                Path State:  OK
                Disabled:  no

                Initiator Port Name:  100000109b56c5fb
                Target Port Name:  205000a098ba7afe
                Logical Unit Number:  1
                Override Path:  NA
                Path State:  OK
                Demoted:  yes
                Disabled:  no

                Initiator Port Name:  100000109b56c5fa
                Target Port Name:  204f00a098ba7afe
                Logical Unit Number:  1
                Override Path:  NA
                Path State:  OK
                Demoted:  yes
                Disabled:  no

                Initiator Port Name:  100000109b56c5fa
                Target Port Name:  205100a098ba7afe
                Logical Unit Number:  1
                Override Path:  NA
                Path State:  OK
                Disabled:  no

        Target Port Groups:
                ID:  1001
                Explicit Failover:  no
                Access State:  *active not optimized*
                Target Ports:
                        Name:  205200a098ba7afe
                        Relative ID:  8

                        Name:  205100a098ba7afe
                        Relative ID:  7

                ID:  1000
                Explicit Failover:  no
                Access State:  *active optimized*
                Target Ports:
                        Name:  205000a098ba7afe
                        Relative ID:  6

                        Name:  204f00a098ba7afe
                        Relative ID:  5
----
=====
--
====




== 步驟 4：查看已知問題

適用於具有ONTAP儲存的 FCP 和 iSCSI 的 Solaris 11.3 版本有下列已知問題：

[cols="4*"]
|===
| NetApp錯誤ID | 標題 | 說明 | Oracle ID 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1366780["1366780"^] | x86架構上的Emulex 32G HBA在GB期間發生Solaris LIF問題 | 適用於x86_64平台上的Emulex韌體12.6.x版及更新版本 | SR 3-24746803021 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1368957["1368957"^] | Solaris 11.x 'cfgadm -c configuration' 會導致端點對端 Emulex 組態發生 I/O 錯誤 | 執行中 `cfgadm -c configure` 在 Emulex 端點對端組態上、會導致 I/O 錯誤。ONTAP 9.5P17 、 9.6P14 、 9.7P13 和 9.8P2 中已修正此問題 | 不適用 
|===


== 接下來呢？

link:hu-solaris-command-reference.html["了解如何使用 Solaris Host Utilities 工具"] 。
