---
sidebar: sidebar 
permalink: hu_ubuntu_2004.html 
keywords: host utilities, red hat, rhel, linux, 20.04, netapp, ontap, ubuntu 
summary: 說明如何搭配 ONTAP 使用 Ubuntu 20.04 
---
= 搭配 ONTAP 使用 Ubuntu 20.04
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您可以使用 ONTAP SAN 主機組態設定、將 ONTAP 設定為目標。


NOTE: Ubuntu 20.04 作業系統無法使用 NetApp Linux Unified Host Utilities 軟體套件。



== SAN開機

.您需要的產品
如果您決定使用SAN開機、則組態必須支援SAN開機。您可以使用 link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["NetApp 互通性對照表工具"^] 驗證是否ONTAP 支援您的作業系統、HBA、HBA韌體和HBA開機BIOS及BIOS版本。

.步驟
. 將SAN開機LUN對應至主機。
. 確認有多個路徑可供使用。
+

NOTE: 在主機作業系統啟動並在路徑上執行後、就會有多個路徑可供使用。

. 在伺服器BIOS中為SAN開機LUN對應的連接埠啟用SAN開機。
+
如需如何啟用HBA BIOS的相關資訊、請參閱廠商專屬的文件。

. 重新啟動主機、確認開機成功。




== 多重路徑

對於 Ubuntu 20.04 `/etc/multipath.conf` 檔案必須存在、但您不需要對檔案進行特定變更。Ubuntu 20.04 是以辨識及正確管理 ONTAP LUN 所需的所有設定進行編譯。

您可以使用「multiPath -ll」命令來驗證ONTAP 您的各個LUN的設定。

下列各節提供對應至 ASA 和非 ASA 角色之 LUN 的多重路徑輸出範例。



=== 所有 SAN 陣列組態

在所有 SAN 陣列（ ASA ）組態中、通往指定 LUN 的所有路徑均為作用中且最佳化。如此可同時透過所有路徑提供 I/O 作業、進而提升效能。

.範例
下列範例顯示ONTAP 適用於某個實體LUN的正確輸出：

[listing]
----
# multipath -ll
3600a098038314559533f524d6c652f62 dm-24 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:1:13 sdm  8:192  active ready running
  |- 11:0:3:13 sdah 66:16  active ready running
  |- 12:0:1:13 sdbc 67:96  active ready running
  `- 12:0:3:13 sdbx 68:176 active ready running
----

NOTE: 單一 LUN 不應需要四個以上的路徑。在儲存設備故障期間、可能會有八個以上的路徑發生問題。



=== 非 ASA 組態

對於非 ASA 組態、應該有兩個路徑群組、其優先順序不同。優先順序較高的路徑為主動 / 最佳化、表示它們由集合所在的控制器提供服務。優先順序較低的路徑是作用中的、但未最佳化、因為它們是由不同的控制器提供服務。非最佳化路徑只有在最佳化路徑無法使用時才會使用。

.範例
下列範例顯示ONTAP 使用兩個主動/最佳化路徑和兩個主動/非最佳化路徑的正確輸出：

[listing]
----
# multipath -ll
3600a098038314837352453694b542f4a dm-0 NETAPP,LUN C-Mode
size=160G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 14:0:3:0 sdbk 67:224 active ready running
| `- 15:0:2:0 sdbl 67:240 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:0:0 sda  8:0    active ready running
  `- 15:0:1:0 sdv  65:80  active ready running
----

NOTE: 單一 LUN 不應需要四個以上的路徑。在儲存設備故障期間、可能會有八個以上的路徑發生問題。



== 建議設定

Ubuntu 20.04 作業系統是為了辨識 ONTAP LUN 、並自動為 ASA 和非 ASA 組態正確設定所有組態參數。您可以使用下列建議設定、進一步最佳化主機組態的效能。

該 `multipath.conf`檔案必須存在、多重路徑常駐程式才能啟動。如果此檔案不存在、您可以使用下列命令來建立空的零位元組檔案：

`touch /etc/multipath.conf`

第一次建立 `multipath.conf`檔案時、您可能需要使用下列命令來啟用和啟動多重路徑服務：

[listing]
----
# chkconfig multipathd on
# /etc/init.d/multipathd start
----
除非您有不想要多重路徑管理的裝置、或是現有的設定會覆寫預設值、否則不需要直接將任何項目新增至 `multipath.conf`檔案。若要排除不想要的裝置、請 `multipath.conf`將下列語法新增至檔案、以您要排除的裝置 WWID 字串取代 <DevId> ：

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
.範例
以下範例決定裝置的 WWID 、並將其新增至 `multipath.conf`檔案。

.步驟
. 判斷 WWID ：
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda`是您要新增至黑名單的本機 SCSI 磁碟。

. 新增 `WWID` 至中的黑名單 `/etc/multipath.conf`：
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


您應該隨時檢查 `/etc/multipath.conf` 舊版設定的檔案、尤其是在預設值區段中、可能會覆寫預設設定。

下表說明 `multipathd` ONTAP LUN 的關鍵參數及必要值。如果主機連接至其他廠商的 LUN 、且這些參數中的任何一個被覆寫、則必須在 `multipath.conf`檔案中以特定套用至 ONTAP LUN 的形式、在稍後的節段中加以修正。如果沒有此修正、 ONTAP LUN 可能無法如預期般運作。您只能在諮詢 NetApp 、作業系統廠商或兩者之後、以及完全瞭解影響時、才應覆寫這些預設值。

[cols="2*"]
|===
| 參數 | 設定 


| DETECT（偵測）_prio | 是的 


| 開發損失_tmo | "無限遠" 


| 容錯回復 | 立即 


| fast_io_f故障_tmo | 5. 


| 功能 | "2 pg_init_retries 50" 


| Flip_on_last刪除 | "是" 


| 硬體處理常式 | 「0」 


| no_path_retry | 佇列 


| path_checker_ | "周" 


| path_grouping_policy | "群組by_prio" 


| path_selector | "服務時間0" 


| Polling_時間 間隔 | 5. 


| 優先 | 「NetApp」ONTAP 


| 產品 | LUN.* 


| Retain附加的硬體處理常式 | 是的 


| RR_weight | "統一" 


| 使用者易記名稱 | 否 


| 廠商 | NetApp 
|===
.範例
下列範例說明如何修正被覆寫的預設值。在此案例中 `multipath.conf` 檔案定義的值 `path_checker` 和 `no_path_retry` 與ONTAP 不兼容的如果因為其他SAN陣列仍連接至主機而無法移除這些參數、則可針對ONTAP 具有裝置例項的LUN、特別修正這些參數。

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry     fail
}

devices {
   device {
      vendor         "NETAPP"
      product         "LUN"
      no_path_retry    queue
      path_checker     tur
   }
}
----


=== KVM 設定

您也可以使用建議的設定來設定核心型虛擬機器（KVM）。由於LUN已對應至Hypervisor、因此無需變更KVM設定。



== 已知問題

使用 ONTAP 版本的 Ubuntu 20.04 沒有已知問題。
