---
sidebar: sidebar 
permalink: hu_vsphere_6.html 
keywords: host utilities, veritas, infoscale, 6.5. 6.7, netapp, ontap 
summary: 說明如何搭配ONTAP 使用Veritas Infoscale 6.5與6.7 for Linux搭配使用 
---
= 搭配 ONTAP 使用 VMware vSphere 6.5 和 6.7
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用 ONTAP SAN 主機組態設定來設定 vSphere 6.5.x 和 6.7.x 版本搭配 FC 、 FCoE 和 iSCSI 通訊協定。



== Hypervisor SAN開機

.開始之前
如果您決定使用SAN開機、則組態必須支援SAN開機。您可以使用link:https://imt.netapp.com/matrix/#welcome["互通性對照表工具"^]驗證是否支援 OS ， HBA ， HBA 韌體和 HBA 開機 BIOS ，以及 ONTAP 版本。

.步驟
. 將SAN開機LUN對應至主機。
. 確認有多個路徑可供使用。
+

NOTE: 在主機作業系統啟動並在路徑上執行後、就會有多個路徑可供使用。

. 在伺服器BIOS中為SAN開機LUN對應的連接埠啟用SAN開機。
+
如需如何啟用HBA BIOS的相關資訊、請參閱廠商專屬的文件。

. 重新啟動主機、確認開機成功。




== 多重路徑

ESXi 提供一個稱為原生多路徑外掛程式（ NMP ）的可延伸多重路徑模組，可管理子外掛程式，儲存陣列類型外掛程式（ Storage Array Type Plugins ，簡稱 SATP ）和路徑選擇外掛程式（ CSP ）。ESXi預設提供這些SATP規則。

對於 ONTAP 儲存設備，「 VMW_SATA_ALUA 」外掛程式預設會使用「 VMW_PSP_RR 」做為路徑選擇原則（ PSP ）。您可以執行下列命令來確認 PSP ：

*「esxcli儲存設備NMP Satp規則清單- s VMW_SATP_ALUA*」

[listing]
----
Name           Device  Vendor    Model     Driver  Transport  Options
-------------  ------  ------    -------   ------  ---------  -------
VMW_SATP_ALUA           LSI      INF-01-00                reset_on_attempted_reserve
VMW_SATP_ALUA           NETAPP                            reset_on_attempted_reserve

Rule Group  Claim Options  Default PSP  PSP Options  Description
----------  -------------  -----------  -----------  ------------
system        tpgs_on         VMW_PSP_MRU       NetApp E-Series arrays with ALUA support
system        tpgs_on          MW_PSP_RR 	      NetApp arrays with ALUA support

----
<stdin> 中存在未解析的指令 - include::_include/hu/reuse_hu_asa_configuration.adoc[]

*「esxcli儲存設備NMP裝置清單- d naa.600a098038304759563f4e783757443*」

[listing]
----
fc.20000024ff171d37:21000024ff171d37-fc.202300a098ea5e27:204a00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba4:C0:T0:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=6,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff171d36:21000024ff171d36-fc.202300a098ea5e27:201d00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba3:C0:T1:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=AO,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff171d36:21000024ff171d36-fc.202300a098ea5e27:201b00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba3:C0:T0:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff171d37:21000024ff171d37-fc.202300a098ea5e27:201e00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba4:C0:T1:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=AO,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----
在上述範例中、LUN已從NetApp儲存設備對應4個路徑（4個主動最佳化路徑）。



=== 非 ASA 組態

對於非 ASA 組態、應該有兩個路徑群組、其優先順序不同。優先順序較高的路徑為主動 / 最佳化。這表示它們由集合所在的控制器提供服務。優先順序較低的路徑是作用中的，但未最佳化，因為它們是由不同的控制器提供服務。非最佳化路徑只有在最佳化路徑無法使用時才會使用。

.範例
下列範例顯示ONTAP 使用兩個主動/最佳化路徑和兩個主動/非最佳化路徑的正確輸出。

*「esxcli儲存設備NMP路徑清單- d naa.600a0980383135330772b4d673979372f*」

[listing]
----
fc.20000090fae0ec8e:10000090fae0ec8e-fc.201000a098dfe3d1:200b00a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba3:C0:T2:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=ANO,RTP_id=29,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000090fae0ec8e:10000090fae0ec8e-fc.201000a098dfe3d1:200700a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba3:C0:T3:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=25,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000090fae0ec8f:10000090fae0ec8f-fc.201000a098dfe3d1:200800a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba4:C0:T2:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=26,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000090fae0ec8f:10000090fae0ec8f-fc.201000a098dfe3d1:200c00a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba4:C0:T3:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=ANO,RTP_id=30,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----
在上述範例中、LUN已從NetApp儲存設備對應4個路徑（2個主動最佳化路徑、2個主動-未最佳化路徑）。



== VVOL

虛擬磁碟區（vVols）是VMware物件類型、對應於虛擬機器（VM）磁碟、以及其快照和快速複製。

VMware vSphere的VMware vSphere支援VASA Provider for VMware、提供整合點、讓VMware vCenter能夠運用vVols型儲存設備。ONTAP ONTAP當您部署ONTAP VMware vCenter工具時、它會自動登錄vCenter伺服器並啟用VASA Provider。

當您使用 vCenter UI 建立 vVols 資料存放區時，它會引導您建立 FlexVols 做為資料存放區的備份儲存區。 ESXi 主機會使用傳輸協定端點（ PE ）來存取 vVols 資料存放區。在 SAN 環境中，會在資料存放區中的每個 FlexVol volume Volume 磁碟區上建立一個 4 MB LUN ，以作為 PE 使用。SAN PE是管理邏輯單元（ALU）；VVols是附屬邏輯單元（SLU）。

使用vVols時、適用SAN環境的標準要求與最佳實務做法、包括（但不限於）下列各項：

. 在每個您要使用的SVM上、每個節點至少建立一個SAN LIF。最佳實務做法是每個節點至少建立兩個節點、但不超過必要。
. 消除任何單點故障。使用多個虛擬交換器時、請在不同的網路子網路上使用多個VMkernel網路介面、或使用多個實體NIC連接至多個實體交換器、以提供HA和增加處理量。
. 視主機連線需求設定分區和（或）VLAN。
. 確保所有必要的啟動器都已登入所需SVM上的目標LIF。



NOTE: 您必須部署ONTAP VMware vSphere的支援功能、才能啟用VASA Provider。VASA Provider 將為您管理所有的 igroup 設定、因此無需在 vVols 環境中建立或管理 iGroups 。

NetApp 目前不建議將任何 vVols 設定從預設值變更。

如需特定版本的 ONTAP 工具，請參閱；如需特定版本的 vSphere 和 ONTAP ，請參閱 https://imt.netapp.com/matrix/#welcome["互通性對照表工具"^]舊版 VASA Provider 。

有關配置和管理 vVols 的詳細信息，請參閱 ONTAP Tools for VMware vSphere 文檔以及 https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-overview.html["VMware vSphere 搭配 ONTAP"^]和link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vvols-overview.html["使用 ONTAP 工具的虛擬磁碟區（ vVols ） 10."^]。



== 建議設定



=== ATS鎖定

ATS鎖定是VAAI相容儲存設備和升級的VMFS5的*強制性*、因此需要搭配ONTAP 使用支援VMware的LUN、才能達到適當的互通性和最佳的VMFS共享儲存I/O效能。如需啟用ATS鎖定的詳細資訊、請參閱VMware文件。

[cols="4*"]
|===
| 設定 | 預設 | 推薦ONTAP | 說明 


| 硬體加速鎖定 | 1. | 1. | 有助於啟用「原子測試與設定（ATS）鎖定」 


| 磁碟IOPs | 1000 | 1. | IOPS限制：循環配置資源（循環配置）PSP預設為IOPS上限1000。在此預設情況下、會在發出1000個I/O作業之後使用新路徑。 


| 磁碟/QFullSampleSize | 0 | 32 | ESXi開始節流之前所需的佇列已滿或忙碌條件數。 
|===

NOTE: 針對所有對應至VMware vSphere的LUN啟用空間分配設定、以便取消對應以正常運作。如需詳細資料、請參閱 https://docs.netapp.com/ontap-9/index.jsp["資訊文件ONTAP"^]。



=== 客體作業系統逾時

您可以使用建議的客體作業系統調整來手動設定虛擬機器。調整更新之後、您必須重新開機客體、更新才會生效。

* GOS逾時值：*

[cols="2*"]
|===
| 客體作業系統類型 | 逾時 


| Linux變體 | 磁碟逾時= 60 


| Windows | 磁碟逾時= 60 


| Solaris | 磁碟逾時= 60次重試= 300次未就緒重試= 300次重試= 30次最大節流= 32次最小節流= 8 
|===


=== 驗證 vSphere 可調整的功能

使用以下命令驗證「HardwareAcceleratedLocking」設定：

*「esxcli系統設定進階清單」-選項/vmas3/HardwareAcceleratedLocked*

[listing]
----
   Path: /VMFS3/HardwareAcceleratedLocking
   Type: integer
   Int Value: 1
   Default Int Value: 1
   Min Value: 0
   Max Value: 1
   String Value:
   Default String Value:
   Valid Characters:
   Description: Enable hardware accelerated VMFS locking (requires compliant hardware). Please see http://kb.vmware.com/kb/2094604 before disabling this option.
----


=== 驗證磁碟 IOPs 設定

使用下列命令來驗證IOPs設定：

*「esxcli儲存設備NMP裝置清單- d naa.600a098038304731783f506670553355*」

[listing]
----
naa.600a098038304731783f506670553355
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304731783f506670553355)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1,bytes=10485760,useANO=0; lastPathIndex=0: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L82, vmhba3:C0:T0:L82
   Is USB: false
----


=== 驗證 QFullSampleSize

使用下列命令來驗證QFullSampleSize..

*「esxcli系統設定進階清單」-選項/Disk/QFullSampleSize*

[listing]
----
   Path: /Disk/QFullSampleSize
   Type: integer
   Int Value: 32
   Default Int Value: 0
   Min Value: 0
   Max Value: 64
   String Value:
   Default String Value:
   Valid Characters:
   Description: Default I/O samples to monitor for detecting non-transient queue full condition. Should be nonzero to enable queue depth throttling. Device specific QFull options will take precedence over this value if set.
----


== 已知問題

VMware vSphere 6.5 與 6.7 搭配 ONTAP 版本有下列已知問題：

[cols="21%,20%,14%,27%"]
|===
| *作業系統版本* | * NetApp錯誤ID* | *標題* | *說明* 


| ESXi 6.5與ESXi 6.7.x | 1413424 | WFC RDM LUN在測試期間失敗 | 在所有7-mode C-cmode叢集控制器上進行儲存容錯移轉測試期間、Windows 2019、Windows 2016和Windows 2012等Windows虛擬機器之間的Windows容錯移轉叢集原始裝置對應失敗。 


| ESXi 6.5.x和ESXi 6.7.x | 1256473.12 | 在Emulex介面卡上測試時出現PLOGI問題 |  
|===
.相關資訊
* link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-overview.html["VMware vSphere 搭配 ONTAP"^]
* link:https://kb.vmware.com/s/article/2031038["VMware vSphere 5.x、6.x及7.x支援NetApp MetroCluster 功能（2031038）"^]
* link:https://kb.vmware.com/s/article/83370["NetApp ONTAP 搭配 NetApp SnapMirror 與 VMware vSphere Metro Storage 叢集（ VMSC ）進行主動同步"^]

