---
sidebar: sidebar 
permalink: hu_wuhu_72.html 
keywords: windows, 7.2, host utilities, SAN, windows 
summary: Windows 主機公用程式包含一個安裝程式，可設定所需的 Windows 登錄和 HBA 參數，讓 Windows 主機正確處理 ONTAP 和 E 系列平台的儲存系統行為。 
---
= 安裝 Windows 主機公用程式 7.2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Windows 主機公用程式可讓您將 Windows 主機電腦連接至 NetApp 儲存系統。

Windows 主機公用程式支援下列 Windows 版本：

* Windows 2022
* Windows 2019
* Windows 2016
* Windows 2012R2
* Windows 2012


Windows 主機公用程式包含一個安裝程式，可設定所需的 Windows 登錄和主機匯流排介面卡（ HBA ）參數，讓 Windows 主機能夠正確處理 ONTAP 和 E 系列平台的儲存系統行為。

安裝 Host Utilities 軟體時、安裝程式會設定所需的 Windows 登錄和 HBA 參數。

下列程式和檔案會安裝在Windows主機電腦上。預設目錄為「C:\Program Files\NetApp\Windows Host Utilities」。

|===
| 方案 | 目的 


| 《emulexhba.reg》 | 疑難排解程式；只有在技術支援人員的指示下才執行此程式。 


| 「\NetAppQCLi\fcconfig.exe」 | 由安裝程式用來設定 HBA 參數。 


| 「\NetAppQCLI/fcconfig.ini`」 | 由安裝程式用來設定 HBA 參數。 


| 「\NetAppQCLI/*。*」 | 由安裝程式用來設定 QLogic FC HBA 參數。 


| 「an版本」 | 顯示主機公用程式和 FC HBA 的版本。 
|===
主機公用程式支援不同的 Windows 主機組態、通訊協定和多重路徑選項。如需詳細資訊，請參閱 https://mysupport.netapp.com/matrix/["互通性對照表工具"^]。



== 驗證您的主機和儲存系統組態

安裝主機公用程式之前、您必須先確認主機公用程式版本是否支援主機和儲存系統組態、以便正確安裝軟體。

.步驟
. 檢查中支援的組態 http://mysupport.netapp.com/matrix["互通性對照表工具"^]。
. 檢查中個別主機所需的 Hotfix link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["SAN主機Windows文件"]。
+

NOTE: 。 link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["使用Windows Server 2022 ONTAP 搭配使用"] 文件提供相關指示 link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html#installing-windows-hotfixes["安裝Windows修補程式"] 適用於Windows伺服器2022。請參閱主機組態類別中的 Windows 文件、以尋找舊版 Windows 伺服器的相關 Hotfix 資訊。

. 新增 iSCSI 、 FCP 或 NVMe 授權、然後啟動目標服務。
+

NOTE: FC 和 iSCSI 通訊協定不需要在使用 SANtricity Storage Manager 的 E 系列儲存系統上取得授權。

. 驗證您的纜線。
+
請參閱 https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN組態參考"^] 您的 ONTAP 或版本說明文件 https://docs.netapp.com/us-en/e-series/install-hw-cabling/index.html["E 系列硬體纜線"^] 以取得詳細的纜線和組態資訊。





== 設定FC HBA和交換器

安裝及設定一或多個支援的 FC 主機匯流排介面卡（ HBA ）、以便 FC 連線至儲存系統。

Windows 主機公用程式安裝程式會設定所需的 FC HBA 設定。


CAUTION: 請勿手動變更 HBA 設定。

.步驟
. 根據 HBA 廠商提供的指示、安裝一或多個支援的 FC HBA 。
. 取得支援的HBA驅動程式和管理公用程式、並依照HBA廠商提供的指示進行安裝。
. 將 HBA 連接至 FC 交換器或直接連接至儲存系統。
. 根據 FC 交換器文件、在 FC 交換器上建立區域。
. 對於 ONTAP 、請將交換器分區為 WWPN 。請務必使用邏輯介面（生命體）的 WWPN 、而非儲存控制器上實體連接埠的 WWPN 。請參閱 https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN組態參考"^] 如需詳細資訊、請參閱文件。




== 安裝主機公用程式

安裝程式會安裝Host Utilities套件、並設定Windows登錄和HBA設定。

安裝 Windows 主機公用程式軟體套件時，您必須指定是否包含多重路徑支援。安裝程式會提示您輸入下列選項。您也可以從Windows命令提示字元執行無訊息（無人值守）安裝。

.多重路徑支援
* 選擇 `MPIO` 如果從 Windows 主機或虛擬機器到儲存系統有多條路徑、
* 選擇 `no MPIO` 僅當您使用單一路徑通往儲存系統時。


Windows XP 和 Windows Vista 系統無法使用 Microsoft 多重路徑 I/O （ MPIO ）選項；這些客體作業系統不支援多重路徑 I/O 。對於Hyper-V來賓作業系統、如果您選擇多重路徑支援、則原始（傳遞）磁碟不會出現在來賓作業系統中。您可以使用原始磁碟、也可以使用MPIO、但不能在客體作業系統中同時使用這兩種磁碟。

您可以互動式或使用命令列來安裝主機公用程式。新的主機公用程式安裝套件必須位於Windows主機可存取的路徑中。依照互動式或從 Windows 命令列安裝主機公用程式的指示進行。

[role="tabbed-block"]
====
.以互動方式安裝
--
若要以互動方式安裝主機公用程式軟體套件、您必須執行主機公用程式安裝程式、然後依照提示進行。

.步驟
. 從下載執行檔 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.2/downloads["NetApp 支援網站"^]。
. 變更至您下載執行檔的目錄。
. 執行 `netapp_windows_host_utilities_7.2_x64` 請歸檔並遵循畫面上的指示。
. 出現提示時、重新啟動Windows主機。


--
.從命令列安裝
--
您可以在 Windows 命令提示字元中輸入適當的命令，以執行 Host Utilities 的無訊息（無人值守）安裝。安裝完成後、系統會自動重新開機。

.步驟
. 在 Windows 命令提示字元中輸入下列命令：
+
「Msiexec /i installer.msi /quiet多重路徑=｛0 | 1｝[InstallalDIR=inst_path]」

+
** `installer` 為的名稱 `.msi` 適用於您 CPU 架構的檔案。
** 多重路徑會指定是否安裝MPIO支援。允許的值為「 0 」表示「否」、「 1 」表示「是」。
** 「inst_path」是安裝主機公用程式檔案的路徑。預設路徑為「C:\Program Files\NetApp\Windows Host Utilities」。





NOTE: 若要查看記錄和其他功能的標準 Microsoft Installer （ MSI ）選項、請輸入 `msiexec /help` 在 Windows 命令提示字元下。例如、 `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` 命令會顯示記錄資訊。

--
====