---
sidebar: sidebar 
permalink: hu_wuhu_upgrade.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Windows 主機公用程式包含一個安裝程式，可設定所需的 Windows 登錄和 HBA 參數，讓 Windows 主機正確處理 ONTAP 和 E 系列平台的儲存系統行為。 
---
= 升級適用於ONTAP儲存的 Windows Host Utilities
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您可以依照安裝說明以互動方式或使用 Windows 命令列來升級ONTAP儲存配置中的 Windows Host Utilities 軟體。您需要將新的 Windows Host Utilities 安裝軟體安裝在 Windows 主機可存取的路徑上。

[role="tabbed-block"]
====
.互動式升級
--
透過執行 Host Utilities 安裝程式並依照指示以互動方式升級 Windows Host Utilities 軟體。

.步驟
. 變更至您下載執行檔的目錄。
. 執行執行檔、並依照畫面上的指示進行。
. 出現提示時、重新啟動Windows主機。
. 重新開機完成後、請檢查主機公用程式版本：
+
.. 開啟*控制台*。
.. 前往*程式與功能*、並查看主機公用程式版本。




--
.非互動升級
--
使用 Windows 命令列執行非互動式 Windows Host Utilities 軟體升級。

.步驟
. 在 Windows 命令提示字元中輸入下列命令：
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` 為的名稱 `.msi` 適用於您 CPU 架構的檔案。
** 多重路徑可指定是否安裝 Microsoft 多重路徑 I/O （ MPIO ）支援。允許的值為「 0 」表示「否」、「 1 」表示「是」。
** 「inst_path」是安裝主機公用程式檔案的路徑。預設路徑為「C:\Program Files\NetApp\Windows Host Utilities」。





NOTE: 若要查看記錄和其他功能的標準 Microsoft Installer （ MSI ）選項、請輸入 `msiexec /help` 在 Windows 命令提示字元下。例如、 `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` 命令會顯示記錄資訊。

安裝完成後、系統會自動重新開機。

--
====