---
sidebar: sidebar 
permalink: nvme_rhel_81.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: 說明如何使用ONTAP 支援功能為RHEL 8.1設定NVMe/FC 
---
= 適用於 ONTAP 的 RHEL 8.1 的 NVMe / FC 主機組態
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
適用於 Red Hat Enterprise Linux （ RHEL ） 8.1 的 ONTAP 9.6 或更新版本支援 NVMe / FC 。RHEL 8.1 主機可透過相同的 FC 啟動器介面卡連接埠、同時執行 NVMe 和 SCSI 流量。請參閱 link:https://hwu.netapp.com/Home/Index["Hardware Universe"^] 以取得支援的FC介面卡和控制器清單。

請參閱 link:https://mysupport.netapp.com/matrix/["NetApp 互通性對照表工具"^] 以取得最新的支援組態清單。



== 已知限制

* 原生 NVMe / FC 自動連線指令碼在中無法使用 `nvme-cli` 套件：您可以使用主機匯流排介面卡（ HBA ）廠商提供的外部自動連線指令碼。
* NVMe 多重路徑預設為停用。因此、您需要手動啟用。
* 預設不會啟用循環配置資源負載平衡。您可以撰寫來啟用此功能 `udev` 規則。
* 目前不支援使用 NVMe 型傳輸協定進行 SAN 開機。




== 啟用NVMe/FC

您可以使用下列程序來啟用 NVMe / FC 。

.步驟
. 在伺服器上安裝Red Hat Enterprise Linux 8.1。
. 安裝完成後、請確認您正在執行指定的 RHEL 核心：
+
[listing]
----
# uname -r
4.18.0-147.el8.x86_64
----
+
請參閱 link:https://mysupport.netapp.com/matrix/["NetApp 互通性對照表工具"^] 以取得最新的支援版本清單。

. 安裝 `nvme-cli-1.8.1-3.el8` 套件：
+
[listing]
----
# rpm -qa|grep nvme-cli
nvme-cli-1.8.1-3.el8.x86_64
----
. 啟用核心內建NVMe多重路徑：
+
[listing]
----
# grubby –args=nvme_core.multipath=Y –update-kernel /boot/vmlinuz-4.18.0-147.el8.x86_64
----
. 將下列字串新增為另一個位於的 udev 規則 `/lib/udev/rules.d/71-nvme-iopolicy-netapp-ONTAP.rules`。這可為 NVMe 多重路徑啟用循環負載平衡：
+
[listing]
----
# Enable round-robin for NetApp ONTAP
ACTION==”add”, SUBSYSTEM==”nvme-subsystem”, ATTR{model}==”NetApp ONTAP Controller”, ATTR{iopolicy}=”round-robin
----
. 在 RHEL 8.1 主機上、檢查主機 NQN 字串位於 `/etc/nvme/hostnqn` 並確認它符合 ONTAP 陣列上對應子系統的主機 NQN 字串：
+
[listing]
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:75953f3b-77fe-4e03-bf3c-09d5a156fbcd
----
+
[listing]
----
*> vserver nvme subsystem host show -vserver vs_nvme_10
Vserver Subsystem Host NQN
------- --------- -------------------------------------- -----------
rhel_141_nvme_ss_10_0
nqn.2014-08.org.nvmexpress:uuid:75953f3b-77fe-4e03-bf3c-09d5a156fbcd
----
+

NOTE: 如果主機 NQN 字串不相符、請使用 `vserver modify` 用於更新對應 ONTAP 陣列子系統上主機 NQN 字串的命令、以符合的主機 NQN 字串 `/etc/nvme/hostnqn` 在主機上。

. 重新啟動主機。




== 設定適用於NVMe / FC的Broadcom FC介面卡

您可以使用下列程序來設定 Broadcom FC 介面卡。

.步驟
. 確認您使用的是支援的介面卡。請參閱 link:https://mysupport.netapp.com/matrix/["NetApp 互通性對照表工具"^] 以取得最新的支援介面卡清單。
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
LPe32002-M2
LPe32002-M2
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/modeldesc
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. 複製並安裝 Broadcom lpfc 外盒驅動程式和自動連線指令碼：
+
[listing]
----
# tar -xvzf elx-lpfc-dd-rhel8-12.4.243.20-ds-1.tar.gz
# cd elx-lpfc-dd-rhel8-12.4.2453.20-ds-1
# ./elx_lpfc_install-sh -i -n
----
+

NOTE: 與作業系統搭售的原生驅動程式稱為收件匣驅動程式。如果您下載的是外箱驅動程式（作業系統版本未隨附的驅動程式）、則下載中會包含自動連線指令碼、並應作為驅動程式安裝程序的一部分進行安裝。

. 重新啟動主機。
. 確認您使用的是推薦的 Broadcom lpfc 韌體、外箱驅動程式和自動連線套件版本：
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
12.4.243.20, sil-4.2.c
12.4.243.20, sil-4.2.c
----
+
[listing]
----
# cat /sys/module/lpfc/version
0:12.4.243.20
----
+
[listing]
----
# rpm -qa | grep nvmefc
nvmefc-connect-12.6.61.0-1.noarch
----
. 請確認 `lpfc_enable_fc4_type` 設為 3 ：
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. 驗證啟動器連接埠是否已啟動並正在執行：
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x10000090fae0ec61
0x10000090fae0ec62
----
+
[listing]
----
# cat /sys/class/fc_host/host*/port_state
Online
Online
----
. 確認 NVMe / FC 啟動器連接埠已啟用、正在執行、而且您可以看到目標生命：
+
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 NVME 2947 SCSI 2977 ELS 250
NVME LPORT lpfc0 WWPN x10000090fae0ec61 WWNN x20000090fae0ec61 DID x012000 ONLINE
NVME RPORT WWPN x202d00a098c80f09 WWNN x202c00a098c80f09 DID x010201 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203100a098c80f09 WWNN x202c00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE
NVME Statistics
…
----




== 啟用Broadcom NVMe / FC的1MB I/O大小

ONTAP 會在識別控制器資料中報告 8 的 MDTS （ MAX Data 傳輸大小）。這表示最大 I/O 要求大小最多可達 1MB 。若要針對 Broadcom NVMe / FC 主機發出大小為 1 MB 的 I/O 要求，您應該將參數值 `lpfc_sg_seg_cnt`從預設值 64 增加 `lpfc`至 256 。


NOTE: 下列步驟不適用於 Qlogic NVMe / FC 主機。

.步驟
. 將 `lpfc_sg_seg_cnt`參數設定為 256 ：
+
[listing]
----
cat /etc/modprobe.d/lpfc.conf
----
+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. 執行 `dracut -f`命令，然後重新啟動主機：
. 確認 `lpfc_sg_seg_cnt`為 256 ：
+
[listing]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----
+
預期值為 256 。





== 驗證NVMe/FC

您可以使用下列程序來驗證 NVMe / FC 。

.步驟
. 驗證下列NVMe / FC設定。
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. 確認已建立命名空間。
+
[listing]
----
# nvme list
Node SN Model Namespace Usage Format FW Rev
---------------- -------------------- -----------------------
/dev/nvme0n1 80BADBKnB/JvAAAAAAAC NetApp ONTAP Controller 1 53.69 GB / 53.69 GB 4 KiB + 0 B FFFFFFFF
----
. 驗證全日空路徑的狀態。
+
[listing]
----
# nvme list-subsys/dev/nvme0n1
Nvme-subsysf0 – NQN=nqn.1992-08.com.netapp:sn.341541339b9511e8a9b500a098c80f09:subsystem.rhel_141_nvme_ss_10_0
\
+- nvme0 fc traddr=nn-0x202c00a098c80f09:pn-0x202d00a098c80f09 host_traddr=nn-0x20000090fae0ec61:pn-0x10000090fae0ec61 live optimized
+- nvme1 fc traddr=nn-0x207300a098dfdd91:pn-0x207600a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme2 fc traddr=nn-0x207300a098dfdd91:pn-0x207500a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
+- nvme3 fc traddr=nn-0x207300a098dfdd91:pn-0x207700a098dfdd91 host traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live inaccessible
----
. 驗證NetApp外掛ONTAP 程式是否適用於各種不實裝置。
+
[listing]
----

# nvme netapp ontapdevices -o column
Device   Vserver  Namespace Path             NSID   UUID   Size
-------  -------- -------------------------  ------ ----- -----
/dev/nvme0n1   vs_nvme_10       /vol/rhel_141_vol_10_0/rhel_141_ns_10_0    1        55baf453-f629-4a18-9364-b6aee3f50dad   53.69GB

# nvme netapp ontapdevices -o json
{
   "ONTAPdevices" : [
   {
        Device" : "/dev/nvme0n1",
        "Vserver" : "vs_nvme_10",
        "Namespace_Path" : "/vol/rhel_141_vol_10_0/rhel_141_ns_10_0",
         "NSID" : 1,
         "UUID" : "55baf453-f629-4a18-9364-b6aee3f50dad",
         "Size" : "53.69GB",
         "LBA_Data_Size" : 4096,
         "Namespace_Size" : 13107200
    }
]
----

