---
sidebar: sidebar 
permalink: nvme_aix.html 
keywords: nvme, linux, rhel, red hat, enterprise, aix, ontap 
summary: 如何使用 ONTAP 設定適用於 AIX 的 NVMe / FC 主機 
---
= 適用於 AIX 與 ONTAP 的 NVMe / FC 主機組態
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您可以在 IBM AIX 和 VIOS/PowerVM 主機上啟用 NVMe / FC 、並使用 ONTAP 儲存設備作為目標。如需支援組態的詳細資訊、請參閱 link:https://mysupport.netapp.com/matrix/["NetApp 互通性對照表工具"^]。

下列支援可用於具有 ONTAP 的 AIX 主機的 NVMe / FC 主機組態：

* 從 ONTAP 9.13.1 開始、 IBM AIX 7.2 TL5 SP6 、 AIX 7.3 TL1 SP2 和 VIOS 3.1.4.21 版本均新增 NVMe over Fibre Channel （ NVMe / FC ）支援、同時支援實體和虛擬堆疊的 SAN 開機。如需設定 SAN 開機支援的詳細資訊、請參閱 IBM 文件。
* NVMe / FC 僅支援 Power9 和 Power10 IBM 伺服器。
* NVMe 裝置不需要個別的 PCM （路徑控制模組）、例如 Huk for AIX SCSI MPIO 支援。
* VIOS 3.1.4.21 引進 NetApp （ VIOS/PowerVM ）的虛擬化支援。使用 Power10 IBM 伺服器透過 NPIV （ N_portID 虛擬化）儲存虛擬化模式支援這項功能（僅限 _ ）。


.您需要的產品
* 確認您擁有 32 GB FC Emulex 介面卡（ EN1A 、 EN1B 、 EN1L 、 EN1M ）或 64 GB FC 介面卡（ EN1N 、 EN1P ）、以及介面卡韌體 12.4.257.30 及更新版本。
* 如果您有 MetroCluster 組態、 NetApp 建議您變更 AIX NVMe / FC 預設 APD （ All Path Down ）時間、以支援 MetroCluster 非計畫性切換事件、以避免 AIX 作業系統強制縮短 I/O 逾時。如需更多資訊及建議的預設設定變更、請參閱公開報告 1553249 。
* 依預設、 AIX 主機作業系統的 ANATT 值為 30 秒。IBM 提供一項臨時修復（ iFix ）、將 ANATT 值上限設為 60 秒；您需要從 IBM 網站安裝 iFix 、以確保所有 ONTAP 工作流程都不會中斷營運。
+

NOTE: 對於 NVMe / FC AIX 支援、您需要在 AIX OS 的 GA 版本上安裝 iFix 。VIOS/PowerVM 作業系統不需要此功能。

+
iFix 詳細資料如下：

+
** 對於 AIX 72-TL5-SP6-2320 層級、請安裝 `IJ46710s6a.230509.epkg.Z` 套件：
** 對於 AIX 73-TL1-SP2-2320 層級、請安裝 `IJ46711s2a.230509.epkg.Z` 套件：
+
如需管理 iFix 的詳細資訊、請參閱 link:http://www-01.ibm.com/support/docview.wss?uid=isg3T1012104["管理 AIX 上的臨時修復"^]。

+

NOTE: 您需要在 AIX 版本上安裝 iFix 、但先前未安裝與相關的 iFix `devices.pciex.pciexclass.010802.rte` 在系統上。如果存在這些 iFix 、則會與新安裝發生衝突。

+
下表示範在非虛擬化模式下指派給 AIX LPAR （ AIX 邏輯分割區）或實體 / 原生堆疊的 HBA ：

+
[cols="10,10,10,10,10"]
|===
| 主機作業系統 | 強大架構 | Power FW 版本 | 模式 | 註解 


.2+| AIX 7.2 TL5 SP6. | Power9. | FW 950 或更新版本 | 實體堆疊 | 可透過 TS012877410 取得 iFix 。 


| Power10 | FW 1010 或更新版本 | 實體堆疊 | 支援 SAN 開機。可透過 TS012877410 取得 iFix 。 


.2+| AIX 7.3 TL1 SP2 | Power9. | FW 950 或更新版本 | 實體堆疊 | 可透過 TS012877410 取得 iFix 。 


| Power10 | FW 1010 或更新版本 | 實體與虛擬堆疊 | 可透過 TS012877410 取得 iFix 。 
|===
+
下表示範在虛擬化模式下、指派給 VIOS 且支援 NPIV 的 HBA ：

+
[cols="10,10,10,10,10"]
|===
| 主機作業系統 | 強大架構 | Power FW 版本 | 模式 | 註解 


| Vios / PowerVM 3.1.4.21 | Power10 | FW 1010 或更新版本 | 虛擬堆疊 | 從 AIX 7.3 TL1 SP2 for VIOCc 開始支援 
|===






== 已知限制

適用於 AIX （含 ONTAP ）的 NVMe / FC 主機組態具有下列已知限制：

* AIX 主機上的 QLogic/Marvel 32G FC HBA 不支援 NVMe / FC 。
* 使用 Power9 IBM 伺服器的 NVMe / FC 裝置不支援 SAN 開機。




== 多重路徑

IBM MPIO （多路徑 I/O ）用於 NVMe 多重路徑、在您安裝 AIX OS 時、預設會提供。

您可以使用驗證是否已為 AIX 主機啟用 NVMe 多重路徑 `lsmpio` 命令：

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
* 輸出範例 *

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8         Enabled  Sel,Opt       nvme12  fcnvme0, 9
hdisk1  9         Enabled  Sel,Non       nvme65  fcnvme1, 9
hdisk1  10        Enabled  Sel,Opt       nvme37  fcnvme1, 9
hdisk1  11        Enabled  Sel,Non       nvme60  fcnvme0, 9
----


== 設定NVMe/FC

您可以使用下列程序來設定適用於 Broadcom / Emulex 介面卡的 NVMe / FC 。

.步驟
. 確認您使用的是支援的介面卡。如需最新的支援介面卡清單、請參閱 link:https://mysupport.netapp.com/matrix/["NetApp 互通性對照表工具"^]。
. 根據預設、實體 FC 會啟用 NVMe / FC 傳輸協定支援；不過、虛擬 I/O 伺服器（ VIOS ）上的虛擬光纖通道（ VFC ）會停用 NVMe / FC 傳輸協定支援。擷取停用 NVMe / FC 支援的介面卡清單：
+
[listing]
----
$ lsmap -all -npiv
----
+
* 輸出範例 *

+
[listing]
----
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost0      U9105.22A.785DB61-V2-C2                 4 s1022-iop-mcc- AIX
Status:LOGGED_IN
FC name:fcs4                    FC loc code:U78DA.ND0.WZS01UY-P0-C7-T0
Ports logged in:3
Flags:0xea<LOGGED_IN,STRIP_MERGE,SCSI_CLIENT,NVME_CLIENT>
VFC client name:fcs0            VFC client DRC:U9105.22A.785DB61-V4-C2
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost1      U9105.22A.785DB61-V2-C3                 4
Status:NOT_LOGGED_IN
FC name:                        FC loc code:
Ports logged in:0
Flags:0x81<NOT_MAPPED,NOT_CONNECTED>
VFC client name:                VFC client DRC:
----
. 在介面卡上執行以啟用對 NVMe / FC 傳輸協定的支援 `ioscli vfcctrl` 在 VIOS 上執行命令：
+
[listing]
----
$  vfcctrl -enable -protocol nvme -vadapter vfchost0
----
+
* 輸出範例 *

+
[listing]
----
The "nvme" protocol for "vfchost0" is enabled.
----
. 確認已在介面卡上啟用支援：
+
[listing]
----
# lsattr -El vfchost0
----
+
* 輸出範例 *

+
[listing]
----
alt_site_wwpn       WWPN to use - Only set after migration   False
current_wwpn  0     WWPN to use - Only set after migration   False
enable_nvme   yes   Enable or disable NVME protocol for NPIV True
label               User defined label                       True
limit_intr    false Limit NPIV Interrupt Sources             True
map_port      fcs4  Physical FC Port                         False
num_per_nvme  0     Number of NPIV NVME queues per range     True
num_per_range 0     Number of NPIV SCSI queues per range     True
----
. 為所有目前的介面卡或選取的介面卡啟用 NVMe / FC 傳輸協定：
+
.. 為所有介面卡啟用 NVMe / FC 傳輸協定：
+
... 變更 `dflt_enabl_nvme` 的屬性值 `viosnpiv0` 將虛擬裝置傳送至 `yes`。
... 設定 `enable_nvme` 屬性值至 `yes` 適用於所有 VFC 主機裝置。
+
[listing]
----
# chdev -l viosnpiv0 -a dflt_enabl_nvme=yes
----
+
[listing]
----
# lsattr -El viosnpiv0
----
+
* 輸出範例 *

+
[listing]
----
bufs_per_cmd    10  NPIV Number of local bufs per cmd                    True
dflt_enabl_nvme yes Default NVME Protocol setting for a new NPIV adapter True
num_local_cmds  5   NPIV Number of local cmds per channel                True
num_per_nvme    8   NPIV Number of NVME queues per range                 True
num_per_range   8   NPIV Number of SCSI queues per range                 True
secure_va_info  no  NPIV Secure Virtual Adapter Information              True
----


.. 變更以啟用所選介面卡的 NVMe / FC 傳輸協定 `enable_nvme` VFC 主機裝置屬性的值 `yes`。


. 請確認 `FC-NVMe Protocol Device` 已在伺服器上建立：
+
[listing]
----
# [root@aix_server /]: lsdev |grep fcnvme
----
+
* 輸出 *

+
[listing]
----
fcnvme0       Available 00-00-02    FC-NVMe Protocol Device
fcnvme1       Available 00-01-02    FC-NVMe Protocol Device
----
. 從伺服器記錄主機 NQN ：
+
[listing]
----
# [root@aix_server /]: lsattr -El fcnvme0
----
+
* 輸出範例 *

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
+
[listing]
----
[root@aix_server /]: lsattr -El fcnvme1
----
+
* 輸出範例 *

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
+
.. 檢視分割區 UUID ：
+
[listing]
----
[root@aix_server /]: lsattr -El sys0 -a partition_uuid
----
+
* 輸出範例 *

+
[listing]
----
partition_uuid 64e039bd-27d2-421c-858d-8a378dec31e8 Partition UUID False
----


. 檢查主機 NQN 、並確認它符合 ONTAP 陣列上對應子系統的主機 NQN 字串：
+
[listing]
----
::> vserver nvme subsystem host show -vserver vs_s922-55-lpar2
----
+
* 輸出範例 *

+
[listing]
----
Vserver         Subsystem                Host NQN
------- --------- ----------------------------------------------------------
vs_s922-55-lpar2 subsystem_s922-55-lpar2 nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8
----
. 確認啟動器連接埠已啟動並正在執行、您可以看到目標生命體。




== 驗證NVMe/FC

您需要驗證 ONTAP 命名空間是否正確反映在主機上。執行下列命令以執行：

[listing]
----
# [root@aix_server /]: lsdev -Cc disk |grep NVMe
----
* 輸出範例 *

[listing]
----
hdisk1  Available 00-00-02 NVMe 4K Disk
----
您可以檢查多重路徑狀態：

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
* 輸出範例 *

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8        Enabled  Sel,Opt      nvme12  fcnvme0, 9
hdisk1  9        Enabled  Sel,Non      nvme65  fcnvme1, 9
hdisk1  10       Enabled  Sel,Opt      nvme37  fcnvme1, 9
hdisk1  11       Enabled  Sel,Non      nvme60  fcnvme0, 9
----


== 已知問題

適用於 AIX 與 ONTAP 的 NVMe / FC 主機組態有下列已知問題：

[cols="10,30,30"]
|===
| Burt ID | 標題 | 說明 


| 1553249) | 要修改的 AIX NVMe / FC 預設 APD 時間、以支援 MCC 非計畫性切換事件 | 根據預設、 NVMe / FC 的全路徑關機（ APD ）逾時值為 20 秒。  然而、 ONTAP MetroCluster 自動非計畫性切換（ AUSO ）和 tiebreaker 啟動的切換工作流程、可能會比 APD 逾時時間長一點、導致 I/O 錯誤。 


| 1546017. | AIX NVMe / FC CAP ANATT 為 60s 、而非 ONTAP 所宣傳的 120s | ONTAP 在控制器識別中通告 ANA （非對稱式命名空間存取）轉換逾時時間為 120 秒。目前、透過 iFix 、 AIX 會從控制器識別讀取 ANA 轉換逾時、但如果超過該限制、則有效地將其鎖定至 60 秒。 


| 1541386 | AAIX NVMe / FC 在 ANATT 到期後符合 EIO | 對於任何儲存容錯移轉（ SFO ）事件、如果 ANA （非對稱式命名空間存取）轉換超過指定路徑上的 ANA 轉換逾時上限、則 AIX NVMe / FC 主機會失敗、並出現 I/O 錯誤、儘管命名空間有其他可用的健全路徑。 


| 1541380 | AIX NVMe / FC 會等待半 / 全 ANATT 過期、然後在 ANA AEN 之後恢復 I/O | IBM AIX NVMe / FC 不支援 ONTAP 發佈的部分非同步通知（ AENs ）。這種低於最佳的全日空處理將導致 SFO 作業期間的效能不佳。 
|===


== 疑難排解

在疑難排解任何 NVMe / FC 故障之前、請先確認您執行的組態符合 IMT 規格、然後繼續執行後續步驟來偵錯任何主機端問題。



=== 啟用詳細記錄

如果您的組態有問題、詳細記錄可提供疑難排解的必要資訊。

.步驟
設定 Qlogic （ qla2xxx ）詳細記錄的程序與設定 lpfc 詳細記錄的程序不同。

[role="tabbed-block"]
====
.lpfc
--
.步驟
. 設定 `lpfc_log_verbose` 將驅動程式設定為下列任一值、以記錄NVMe/FC事件。
+
[listing]
----
#define LOG_NVME 0x00100000 /* NVME general events. */
#define LOG_NVME_DISC 0x00200000 /* NVME Discovery/Connect events. */
#define LOG_NVME_ABTS 0x00400000 /* NVME ABTS events. */
#define LOG_NVME_IOERR 0x00800000 /* NVME IO Error events. */
----
. 設定值之後、請執行 `dracut-f` 命令並重新啟動主機。
. 驗證設定。
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_log_verbose=0xf00083

# cat /sys/module/lpfc/parameters/lpfc_log_verbose
15728771
----


--
.qla2xxx
--
NVMe / FC沒有類似的特定qla2xxx記錄功能 `lpfc` 驅動程式：因此、您可以使用下列步驟設定一般的qla2xxx記錄層級：

.步驟
. 將「ql2xextend_error_logging=x1e400000」值附加至對應的「modf探測qla2xxx conf」檔案。
. 執行「dracut -f」命令重新建立「initramfs」、然後重新啟動主機。
. 重新開機後、請確認已套用詳細記錄、如下所示：
+
[listing]
----
# cat /etc/modprobe.d/qla2xxx.conf
options qla2xxx ql2xnvmeenable=1 ql2xextended_error_logging=0x1e400000
# cat /sys/module/qla2xxx/parameters/ql2xextended_error_logging
507510784
----


--
====


=== 常見的NVMe-CLI錯誤和因應措施

顯示的錯誤 `nvme-cli` 期間 `nvme discover`、 `nvme connect`或 `nvme connect-all` 作業與因應措施如下表所示：

[cols="20, 20, 50"]
|===
| 「NVMe - CLI」顯示錯誤 | 可能原因 | 因應措施 


| 「寫入/dev/NVMe架構失敗：無效的引數」 | 語法不正確 | 請確認您使用的語法正確 `nvme discover`、 `nvme connect`和 `nvme connect-all` 命令。 


| 「寫入/dev/NVMe架構失敗：沒有這類檔案或目錄」 | 例如、多個問題可能會觸發這種情況、例如為NVMe命令提供錯誤的引數是常見原因之一。  a| 
* 確認您已將正確的引數（例如、正確的WWNN字串、WWPN字串等）傳遞給命令。
* 如果引數正確、但您仍看到此錯誤、請檢查是否有 `/sys/class/scsi_host/host*/nvme_info` 命令輸出正確、NVMe啟動器顯示為 `Enabled`和NVMe / FC目標LIF會正確顯示在遠端連接埠區段下方。範例：
+
[listing]
----

# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
NVME LPORT lpfc0 WWPN x10000090fae0ec9d WWNN x20000090fae0ec9d DID x012000 ONLINE
NVME RPORT WWPN x200b00a098c80f09 WWNN x200a00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000071 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a6 Outstanding 0000000000000001
NVME Initiator Enabled
NVME LPORT lpfc1 WWPN x10000090fae0ec9e WWNN x20000090fae0ec9e DID x012400 ONLINE
NVME RPORT WWPN x200900a098c80f09 WWNN x200800a098c80f09 DID x010301 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000073 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a8 Outstanding 0000000000000001
----
* 如果目標生命量未如上述所示顯示於 `nvme_info` 命令輸出、請檢查 `/var/log/messages` 和 `dmesg` 針對任何可疑的NVMe/FC故障、提供命令輸出、並據此報告或修正。




| 「沒有要擷取的探索記錄項目」  a| 
一般在下列情況下觀察 `/etc/nvme/hostnqn` 字串尚未新增至NetApp陣列上的對應子系統、或是不正確 `hostnqn` 字串已新增至各自的子系統。
 a| 
確認正確無誤 `/etc/nvme/hostnqn` 字串會新增至NetApp陣列上的對應子系統（請使用 `vserver nvme subsystem host show` 命令）。



| 「寫入/dev/NVMe架構失敗：作業已在進行中」  a| 
觀察控制器關聯或指定作業已建立或正在建立的過程。這可能是上述安裝之自動連線指令碼的一部分。
 a| 
無。請嘗試執行 `nvme discover` 一段時間後再次命令。適用於 `nvme connect` 和 `connect-all`、執行 `nvme list` 命令來驗證命名空間裝置是否已建立並顯示在主機上。

|===


=== 何時聯絡技術支援

如果您仍遇到問題、請收集下列檔案和命令輸出、並聯絡技術支援部門以進一步分類：

[listing]
----
cat /sys/class/scsi_host/host*/nvme_info
/var/log/messages
dmesg
nvme discover output as in:
nvme discover --transport=fc --traddr=nn-0x200a00a098c80f09:pn-0x200b00a098c80f09 --host-traddr=nn-0x20000090fae0ec9d:pn-0x10000090fae0ec9d
nvme list
nvme list-subsys /dev/nvmeXnY
----