---
sidebar: sidebar 
permalink: nvme-proxmox-ve-9x.html 
keywords: nvme, proxmox, enterprise 
summary: 如何為 Proxmox VE 9.0 配置 NVMe-oF 主機和ONTAP存儲 
---
= 配置 Proxmox VE 9.0 以支援 NVMe-oF 和ONTAP存儲
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proxmox VE 9.0 主機支援基於光纖通道的 NVMe (NVMe/FC) 和基於 TCP 的 NVMe (NVMe/TCP) 協議，並支援非對稱命名空間存取 (ANA)。ANA 提供與 iSCSI 和 FCP 環境中的非對稱邏輯單元存取 (ALUA) 等效的多路徑功能。

了解如何為 Proxmox VE 9.0 設定 NVMe over Fabrics (NVMe-oF) 主機。如需更多支援和功能信息，請參閱 link:nvme-proxmox-supported-features.html["ONTAP支援和功能"^]。

NVMe-oF 與 Proxmox VE 9.0 有以下已知限制：

* 不支援 NVMe-FC 的 SAN 啟動配置。




== 步驟 1：驗證軟體版本和 NVMe 配置

若要為 NVMe-oF 設定主機，您應該安裝主機和 NVMe 軟體包，啟用多路徑，並驗證主機 NQN 設定。

.步驟
. 在伺服器上安裝 Proxmox VE 9.0。安裝完成後，請確認您執行的是所需的 Proxmox VE 9.0 核心：
+
[source, cli]
----
uname -r
----
+
Proxmox VE 9.0 核心版本範例：

+
[listing]
----
6.14.8-2-pve
----
. 安裝「NVMe-CLI（NVMe - CLI）套件：
+
[source, cli]
----
apt list|grep nvme-cli
----
+
下面的例子展示了 `nvme-cli`軟體包版本：

+
[listing]
----
nvme-cli/stable,now 2.13-2 amd64
----
. 安裝 `libnvme` 套件：
+
[source, cli]
----
apt list|grep libnvme
----
+
下面的例子展示了 `libnvme`軟體包版本：

+
[listing]
----
libnvme-dev/stable 1.13-2 amd64
----
. 在主機上，檢查 hostnqn 字串 `/etc/nvme/hostnqn` ：
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
下面的例子展示了 `hostnqn`價值：

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:39333550-3333-4753-4844-32594d4a524c
----
. 確認 `hostnqn` 字串符合 `hostnqn` ONTAP 陣列上對應子系統的字串：
+
[source, cli]
----
::> vserver nvme subsystem host show -vserver vs_proxmox_FC_NVMeFC
----
+
.顯示範例
[%collapsible]
====
[listing]
----
Vserver Subsystem Priority  Host NQN
------- --------- --------  -----------------------------------------------
vs_proxmox_FC_NVMeFC
        sub_176
                  regular   nqn.2014-08.org.nvmexpress:uuid:39333550-3333-4753-4844-32594d4a4834
                  regular   nqn.2014-08.org.nvmexpress:uuid:39333550-3333-4753-4844-32594d4a524c
2 entries were displayed
----
====
+

NOTE: 如果 `hostnqn`字串不匹配，請使用 `vserver modify`命令來更新 `hostnqn`對應ONTAP儲存系統子系統上的字串以匹配 `hostnqn`字串來自 `/etc/nvme/hostnqn`在主機上。





== 步驟 2：設定 NVMe/FC 和 NVMe/TCP

使用 Broadcom/Emulex 或 Marvell/QLogic 適配器配置 NVMe/FC，或使用手動發現和連接操作來設定 NVMe/TCP。

.步驟
[role="tabbed-block"]
====
.NVMe/FC - 博通/Emulex
--
為 Broadcom / Emulex 介面卡設定 NVMe / FC 。

. 確認您使用的是支援的介面卡機型：
+
.. 顯示模型名稱：
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
您應該會看到下列輸出：

+
[listing]
----
SN1700E2P
SN1700E2P
----
.. 顯示模型描述：
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
您應該會看到類似以下範例的輸出：

+
[listing]
----
HPE SN1700E 64Gb 2p FC HBA
HPE SN1700E 64Gb 2p FC HBA
----


. 驗證您使用的是建議的Broadcom `lpfc` 韌體與收件匣驅動程式：
+
.. 顯示韌體版本：
+
[source, cli]
----
cat /sys/class/scsi_host/host*/fwrev
----
+
該命令返回韌體版本：

+
[listing]
----
14.4.473.14, sli-4:6:d
14.4.473.14, sli-4:6:d
----
.. 顯示收件匣驅動程式版本：
+
[source, cli]
----
cat /sys/module/lpfc/version
----
+
以下範例顯示了驅動程式版本：

+
[listing]
----
0:14.4.0.7
----


+
如需支援的介面卡驅動程式和韌體版本的最新清單，請參閱link:https://mysupport.netapp.com/matrix/["互通性對照表工具"^]。

. 請確認 `lpfc_enable_fc4_type` 設為 `3`：
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. 確認您可以檢視啟動器連接埠：
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
您應該會看到類似以下內容的輸出：

+
[listing]
----
0x10005ced8c531948
0x10005ced8c531949
----
. 驗證啟動器連接埠是否在線上：
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
您應該會看到下列輸出：

+
[listing]
----
Online
Online
----
. 確認已啟用 NVMe / FC 啟動器連接埠、且目標連接埠可見：
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x10005ced8c531948 WWNN x20005ced8c531948 DID x082400 *ONLINE*
NVME RPORT       WWPN x200ed039eac79573 WWNN x200dd039eac79573 DID x060902 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2001d039eac79573 WWNN x2000d039eac79573 DID x060904 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000034 Cmpl 0000000034 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 0000000000142cfb Issue 0000000000142cfc OutIO 0000000000000001
        abort 00000005 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000005 Err 00000005

NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x10005ced8c531949 WWNN x20005ced8c531949 DID x082500 *ONLINE*
NVME RPORT       WWPN x2010d039eac79573 WWNN x200dd039eac79573 DID x062902 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2007d039eac79573 WWNN x2000d039eac79573 DID x062904 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000034 Cmpl 0000000034 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 00000000000d39f1 Issue 00000000000d39f2 OutIO 0000000000000001
        abort 00000005 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000005 Err 00000005
----
=====


--
.NVMe/FC - Marvell/QLogic
--
為 Marvell/QLogic 介面卡設定 NVMe / FC 。

. 驗證您使用的適配器驅動程式和韌體版本是否受支援：
+
[source, cli]
----
cat /sys/class/fc_host/host*/symbolic_name
----
+
以下範例顯示了驅動程式和韌體版本：

+
[listing]
----
SN1700Q FW:v9.15.05 DVR:v10.02.09.400-k
SN1700Q FW:v9.15.05 DVR:v10.02.09.400-k
----
. 請確認 `ql2xnvmeenable` 已設定。這可讓 Marvell 介面卡作為 NVMe / FC 啟動器運作：
+
[source, cli]
----
cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
----
+
預期輸出為 1 。



--
.NVMe / TCP
--
NVMe/TCP 協定不支援自動連線操作。相反，您可以透過執行 NVMe/TCP 來發現 NVMe/TCP 子系統和命名空間 `connect`或者 `connect-all`手動操作。

. 檢查啟動器連接埠是否可以跨支援的 NVMe/TCP LIF 取得發現日誌頁面資料：
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme discover -t tcp -w 192.168.165.72 -a 192.168.165.51
Discovery Log Number of Records 4, Generation counter 47
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  3
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:discovery
traddr:  192.168.165.51
eflags:  *explicit discovery connections*, *duplicate discovery information*
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  1
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:discovery
traddr:  192.168.166.50
eflags:  *explicit discovery connections*, *duplicate discovery information*
sectype: none
=====Discovery Log Entry 2======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  3
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:subsystem.sub_176
traddr:  192.168.165.51
eflags:  none
sectype: none
=====Discovery Log Entry 3======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  1
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:subsystem.sub_176
traddr:  192.168.166.50
eflags:  none
sectype: none
----
=====
. 執行 `nvme connect-all` 跨所有節點支援的 NVMe / TCP 啟動器目標生命體執行命令：
+
[source, cli]
----
nvme connect-all -t tcp -w host-traddr -a traddr
----
+
.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme connect-all -t tcp -w 192.168.166.73 -a 192.168.166.50
nvme connect-all -t tcp -w 192.168.166.73 -a 192.168.166.51
nvme connect-all -t tcp -w 192.168.165.73 -a 192.168.165.50
nvme connect-all -t tcp -w 192.168.165.73 -a 192.168.165.51
----
=====


[NOTE]
====
NVMe/TCP 的設置 `ctrl_loss_tmo timeout`自動設定為“關閉”。因此：

* 重試次數沒有限制（無限重試）。
* 您不需要手動配置特定的 `ctrl_loss_tmo timeout`使用時長 `nvme connect`或者 `nvme connect-all`命令（選項 -l ）。
* 如果發生路徑故障，NVMe/TCP 控制器不會逾時，並且會無限期地保持連線。


====
--
====


== 步驟 3：可選，啟用 NVMe/FC 的 1MB I/O。

ONTAP在識別控制器資料中報告最大資料傳輸大小 (MDTS) 為 8。這意味著最大 I/O 請求大小可達 1MB。若要向 Broadcom NVMe/FC 主機發出 1MB 大小的 I/O 要求，您應該會增加 `lpfc`的價值 `lpfc_sg_seg_cnt`參數從預設值 64 更改為 256。


NOTE: 這些步驟不適用於 Qlogic NVMe / FC 主機。

.步驟
. 將 `lpfc_sg_seg_cnt`參數設定為 256 ：
+
[source, cli]
----
cat /etc/modprobe.d/lpfc.conf
----
+
您應該會看到類似以下範例的輸出：

+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. 執行 `dracut -f`命令，然後重新啟動主機。
. 確認的值 `lpfc_sg_seg_cnt`為 256 ：
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== 步驟 4：驗證 NVMe 啟動服務

這 `nvmefc-boot-connections.service`和 `nvmf-autoconnect.service`NVMe/FC 中包含的啟動服務 `nvme-cli`系統啟動時，軟體包會自動啟用。

啟動完成後，驗證 `nvmefc-boot-connections.service`和 `nvmf-autoconnect.service`啟動服務已啟用。

.步驟
. 確認 `nvmf-autoconnect.service`已啟用：
+
[source, cli]
----
systemctl status nvmf-autoconnect.service
----
+
.顯示範例輸出
[%collapsible]
====
[listing]
----
○ nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot
     Loaded: loaded (/usr/lib/systemd/system/nvmf-autoconnect.service; enabled; preset: enabled)
     Active: inactive (dead) since Thu 2025-10-16 18:00:39 IST; 6 days ago
 Invocation: e146e0b2c339432aad6e0555a528872c
    Process: 1787 ExecStart=/usr/sbin/nvme connect-all --context=autoconnect (code=exited, status=0/SUCCESS)
   Main PID: 1787 (code=exited, status=0/SUCCESS)
   Mem peak: 2.4M
        CPU: 12ms
Oct 16 18:00:39 HPE-DL365-14-176 systemd[1]: Starting nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot...
Oct 16 18:00:39 HPE-DL365-14-176 systemd[1]: nvmf-autoconnect.service: Deactivated successfully.
Oct 16 18:00:39 HPE-DL365-14-176 systemd[1]: Finished nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot.
----
====
. 確認 `nvmefc-boot-connections.service`已啟用：
+
[source, cli]
----
systemctl status nvmefc-boot-connections.service
----
+
.顯示範例輸出
[%collapsible]
====
[listing]
----
nvmefc-boot-connections.service - Auto-connect to subsystems on FC-NVME devices found during boot
     Loaded: loaded (/usr/lib/systemd/system/nvmefc-boot-connections.service; enabled; preset: enabled)
     Active: inactive (dead) since Thu 2025-10-16 18:00:35 IST; 6 days ago
 Invocation: acf73ac1ef7a402198d6ecc4d075fab0
    Process: 1173 ExecStart=/bin/sh -c echo add > /sys/class/fc/fc_udev_device/nvme_discovery (code=exited, status=0/SUCCESS)
   Main PID: 1173 (code=exited, status=0/SUCCESS)
   Mem peak: 2.1M
        CPU: 11ms

Oct 16 18:00:35 HPE-DL365-14-176 systemd[1]: nvmefc-boot-connections.service: Deactivated successfully.
Oct 16 18:00:35 HPE-DL365-14-176 systemd[1]: Finished nvmefc-boot-connections.service - Auto-connect to subsystems on FC-NVME devices found during boot.
----
====




== 步驟 5：驗證多路徑配置

驗證核心內建 NVMe 多重路徑狀態， ANA 狀態和 ONTAP 命名空間是否適用於 NVMe 組態。

.步驟
. 確認已啟用核心內建 NVMe 多重路徑：
+
[source, cli]
----
cat /sys/module/nvme_core/parameters/multipath
----
+
您應該會看到下列輸出：

+
[listing]
----
Y
----
. 驗證主機上是否正確顯示了ONTAP命名空間的相應 NVMe-oF 設定（例如，將型號設定為NetApp ONTAP Controller，並將負載平衡 iopolicy 設定為 round-robin）：
+
.. 顯示子系統：
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
您應該會看到下列輸出：

+
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
.. 顯示策略：
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
您應該會看到下列輸出：

+
[listing]
----
queue-depth
queue-depth
----


. 確認已在主機上建立並正確探索命名空間：
+
[source, cli]
----
nvme list
----
+
.顯示範例
[%collapsible]
====
[listing]
----
Node          Generic     SN                   Model                    Namespace  Usage                      Format           FW Rev
------------- ----------- -------------------- ------------------------ ---------- -------------------------- ---------------- --------
/dev/nvme2n1  /dev/ng2n1  81PqYFYq2aVAAAAAAAAB NetApp ONTAP Controller   0x1         17.88  GB / 171.80  GB      4 KiB +  0 B   9.17.1
----
====
. 確認每個路徑的控制器狀態均為有效、且具有正確的ANA狀態：
+
[role="tabbed-block"]
====
.NVMe / FC
--
[source, cli]
----
nvme list-subsys /dev/nvme3n9
----
.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys3 - NQN=nqn.1992-08.com.netapp:sn.94929fdb84eb11f0b624d039eac809ba:subsystem.sub_176
               hostnqn=nqn.2014-08.org.nvmexpress:uuid:39333550-3333-4753-4844-32594d4a524c
\
 +- nvme1 *fc* traddr=nn-0x200dd039eac79573:pn-0x2010d039eac79573,host_traddr=nn-0x20005ced8c531949:pn-0x10005ced8c531949 *live optimized*
 +- nvme3 *fc* traddr=nn-0x200dd039eac79573:pn-0x200ed039eac79573,host_traddr=nn-0x20005ced8c531948:pn-0x10005ced8c531948 *live optimized*
+- nvme5 *fc* traddr=nn-0x200dd039eac79573:pn-0x200fd039eac79573,host_traddr=nn-0x20005ced8c531949:pn-0x10005ced8c531949 *live non-optimized*
 +- nvme7 *fc* traddr=nn-0x200dd039eac79573:pn-0x2011d039eac79573,host_traddr=nn-0x20005ced8c531948:pn-0x10005ced8c531948 *live non-optimized*
----
=====
--
.NVMe / TCP
--
[source, cli]
----
nvme list-subsys /dev/nvme2n3
----
.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys2 - NQN=nqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:subsystem.sub_176
               hostnqn=nqn.2014-08.org.nvmexpress:uuid:39333550-3333-4753-4844-32594d4a524c
\
 +- nvme2 *tcp* traddr=192.168.166.50,trsvcid=4420,host_traddr=192.168.166.73,src_addr=192.168.166.73 *live optimized*
 +- nvme4 *tcp* traddr=192.168.165.51,trsvcid=4420,host_traddr=192.168.165.73,src_addr=192.168.165.73 *live optimized*
+- nvme6 *tcp* traddr=192.168.166.51,trsvcid=4420,host_traddr=192.168.166.73,src_addr=192.168.166.73 *live non-optimized*
 +- nvme8 *tcp* traddr=192.168.165.50,trsvcid=4420,host_traddr=192.168.165.73,src_addr=192.168.165.73 *live non-optimized*
----
=====
--
====
. 驗證NetApp外掛程式是否顯示每ONTAP 個版本名稱空間裝置的正確值：
+
[role="tabbed-block"]
====
.欄位
--
[source, cli]
----
nvme netapp ontapdevices -o column
----
.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----

Device        Vserver               Namespace Path
------------- --------------------- ------------------------------
/dev/nvme2n9  vs_proxmox_FC_NVMeFC  /vol/vol_180_data_nvmefc4/ns

NSID       UUID                            Size
---- ------------------------------------  --------
1    e3d3d544-de8b-4787-93af-bfec7769e909  32.21GB
----
=====
--
.JSON
--
[source, cli]
----
nvme netapp ontapdevices -o json
----
.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----
{
      "Device":"/dev/nvme2n9",
      "Vserver":"vs_proxmox_FC_NVMeFC",
      "Subsystem":"sub_176",
      "Namespace_Path":"/vol/vol_180_data_nvmefc4/ns",
      "NSID":9,
      "UUID":"e3d3d544-de8b-4787-93af-bfec7769e909",
      "LBA_Size":4096,
      "Namespace_Size":32212254720,
      "UsedBytes":67899392,
      "Version":"9.17.1"
    }
  ]
----
=====
--
====




== 步驟 6 ：檢閱已知問題

沒有已知問題。
