---
sidebar: sidebar 
permalink: nvme_rhel_89.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: 如何使用 ONTAP 設定適用於 RHEL 8.9 的 NVMe 主機 
---
= 適用於 ONTAP 的 RHEL 8.9 的 NVMe 主機組態
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Red Hat Enterprise Linux （ RHEL ） 8.9 搭配非對稱命名空間存取（ ANA ）、可支援 NVMe over Fabrics （ NVMe over Fibre Channel 、 NVMe / FC ）和其他傳輸。在 NVMe 環境中、 ANA 等同於 iSCSI 和 FC 環境中的 ALUA 多重路徑、並以核心內建 NVMe 多重路徑來實作。

下列支援適用於 ONTAP 的 RHEL 8.9 NVMe 主機組態：

* 支援 NVMe over TCP （ NVMe / TCP ）、以及 NVMe / FC 。原生 NVMe - CLI 套件中的 NetApp 外掛程式會同時顯示 NVMe / FC 和 NVMe / TCP 命名空間的 ONTAP 詳細資料。


如需支援組態的其他詳細資訊，請參閱link:https://mysupport.netapp.com/matrix/["互通性對照表工具"^]。



== 已知限制

* 根據預設、 RHEL 8.9 NVMe 主機的核心內建 NVMe 多重路徑會停用。因此、您需要手動啟用。
* 在 RHEL 8.9 主機上、 NVMe / TCP 是一項技術預覽功能、因為存在開放式問題。
* 目前不支援使用 NVMe 型傳輸協定進行 SAN 開機。




== 啟用核心內建多重路徑

您可以使用下列程序來啟用核心內建多重路徑。

.步驟
. 在主機伺服器上安裝 RHEL 8.9 。
. 安裝完成後、請確認您正在執行指定的 RHEL 8.9 核心：
+
[listing]
----
# uname -r
----
+
* 輸出範例 *

+
[listing]
----
4.18.0-513.5.1.el8_9.x86_64
----
. 安裝 NVMe CLI 套件：
+
[listing]
----
rpm -qa|grep nvme-cli
----
+
* 輸出範例 *

+
[listing]
----
nvme-cli-1.16-9.el8.x86_64
----
. 啟用核心內建 NVMe 多重路徑：
+
[listing]
----
# grubby --args=nvme_core.multipath=Y --update-kernel /boot/vmlinuz-4.18.0-513.5.1.el8_9.x86_64
----
. 在主機上、檢查主機的 NQN 字串 `/etc/nvme/hostnqn`：
+
[listing]
----
# cat /etc/nvme/hostnqn
----
+
* 輸出範例 *

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0032-3410-8035-b8c04f4c5132
----
. 確認 `hostnqn` 字串符合 `hostnqn` ONTAP 陣列上對應子系統的字串：
+
[listing]
----
::> vserver nvme subsystem host show -vserver vs_fcnvme_141
----
+
* 輸出範例 *

+
[listing]
----
Vserver     Subsystem       Host NQN
----------- --------------- ----------------------------------------------------------
vs_nvme101 rhel_101_QLe2772    nqn.2014-08.org.nvmexpress: uuid:4c4c4544-0032-3410-8035-b8c04f4c5132
----
+

NOTE: 如果主機 NQN 字串不相符、您可以使用 `vserver modify` 用於更新對應 ONTAP NVMe 子系統上主機 NQN 字串的命令、以符合主機 NQN 字串 `/etc/nvme/hostnqn` 在主機上。

. 重新啟動主機。


[NOTE]
====
如果您打算在同一部主機上同時執行 NVMe 和 SCSI 共存的流量、 NetApp 建議分別針對 ONTAP 命名空間使用核心內建 NVMe 多重路徑、以及針對 ONTAP LUN 使用 dm-multipath 。這應該會從 dm-multipath 中排除 ONTAP 命名空間、並防止 dm-multipath 宣告這些命名空間裝置。您可以新增來執行此作業 `enable_foreign` 設定為 `/etc/multipath.conf` 檔案：

[listing]
----
# cat /etc/multipath.conf
defaults {
  enable_foreign  NONE
}
----
====


== 設定NVMe/FC

您可以為 Broadcom / Emulex 或 Marvell/Qlogic 介面卡設定 NVMe / FC 。

[role="tabbed-block"]
====
.Broadcom / Emulex
--
.步驟
. 確認您使用的是支援的介面卡機型：
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
----
+
* 輸出範例： *

+
[listing]
----
LPe32002-M2
LPe32002-M2
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/modeldesc
----
+
* 輸出範例： *

+
[listing]
----
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. 驗證您使用的是建議的Broadcom `lpfc` 韌體與收件匣驅動程式：
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
14.2.539.16, sli-4:2:c
14.2.539.16, sli-4:2:c
----
+
[listing]
----
# cat /sys/module/lpfc/version
0:14.0.0.21
----
+
如需支援的介面卡驅動程式和韌體版本的最新清單，請參閱link:https://mysupport.netapp.com/matrix/["互通性對照表工具"^]。

. 請確認 `lpfc_enable_fc4_type` 設為 `3`：
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. 確認啟動器連接埠已啟動並正在執行、而且您可以看到目標生命體：
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x10000090fae0ec88
0x10000090fae0ec89
----
+
[listing]
----
# cat /sys/class/fc_host/host*/port_state
Online
Online
----
+
[listing, subs="+quotes"]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x10000090fae0ec88 WWNN x20000090fae0ec88 DID x0a1300 *ONLINE*
NVME RPORT       WWPN x2049d039ea36a105 WWNN x2048d039ea36a105 DID x0a0c0a *TARGET DISCSRVC ONLINE*
NVME Statistics
LS: Xmt 0000000024 Cmpl 0000000024 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 00000000000001aa Issue 00000000000001ab OutIO 0000000000000001
        abort 00000002 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000002 Err 00000003
NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x10000090fae0ec89 WWNN x20000090fae0ec89 DID x0a1200 *ONLINE*
NVME RPORT       WWPN x204ad039ea36a105 WWNN x2048d039ea36a105 DID x0a080a *TARGET DISCSRVC ONLINE*
NVME Statistics
LS: Xmt 0000000024 Cmpl 0000000024 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 00000000000001ac Issue 00000000000001ad OutIO 0000000000000001
        abort 00000002 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000002 Err 00000003



----


--
.適用於 NVMe / FC 的 Marvell/QLogic FC 介面卡
--
RHEL 8.9 GA 核心中隨附的原生收件匣 qla2xxx 驅動程式具有最新的上游修正。這些修正對於 ONTAP 支援至關重要。

.步驟
. 確認您執行的是支援的介面卡驅動程式和韌體版本：
+
[listing]
----
# cat /sys/class/fc_host/host*/symbolic_name
----
+
* 輸出範例 *

+
[listing]
----
QLE2742 FW: v9.10.11 DVR: v10.02.08.200-k
QLE2742 FW: v9.10.11 DVR: v10.02.08.200-k
----
. 請確認 `ql2xnvmeenable` 已設定。這可讓 Marvell 介面卡作為 NVMe / FC 啟動器運作：
+
[listing]
----
# cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
1
----


--
====


=== 啟用 1MB I/O （選用）

ONTAP 會在識別控制器資料中報告 8 的 MDTS （ MAX Data 傳輸大小）。這表示最大 I/O 要求大小最多可達 1MB 。若要針對 Broadcom NVMe / FC 主機發出大小為 1 MB 的 I/O 要求，您應該將參數值 `lpfc_sg_seg_cnt`從預設值 64 增加 `lpfc`至 256 。


NOTE: 這些步驟不適用於 Qlogic NVMe / FC 主機。

.步驟
. 將 `lpfc_sg_seg_cnt`參數設定為 256 ：
+
[listing]
----
cat /etc/modprobe.d/lpfc.conf
----
+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. 執行 `dracut -f`命令，然後重新啟動主機。
. 確認的值 `lpfc_sg_seg_cnt`為 256 ：
+
[listing]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== 設定NVMe/TCP

NVMe / TCP 沒有自動連線功能。因此、如果某個路徑發生故障、且在 10 分鐘的預設逾時期間內未恢復、則 NVMe / TCP 無法自動重新連線。若要避免逾時、您應該將容錯移轉事件的重試期間設為至少 30 分鐘。

.步驟
. 確認啟動器連接埠可在支援的NVMe/TCP LIF中擷取探索記錄頁面資料：
+
[listing]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
* 輸出範例： *

+
[listing]
----
# nvme discover -t tcp -w 192.168.111.79 -a 192.168.111.14 -l 1800

Discovery Log Number of Records 8, Generation counter 18
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: unrecognized
treq:    not specified.
portid:  0
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b: discovery
traddr:  192.168.211.15
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: unrecognized
treq:    not specified.
portid:  1
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b: discovery
traddr:  192.168.111.15
sectype: none ..........


----
. 確認其他的 NVMe / TCP 啟動器目標 LIF 組合可以成功擷取探索記錄頁面資料：
+
[listing]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
* 輸出範例： *

+
[listing]
----
# nvme	discover	-t   tcp    -w	192.168.111.79   -a	192.168.111.14
# nvme	discover	-t   tcp    -w	192.168.111.79   -a	192.168.111.15
# nvme	discover	-t   tcp    -w	192.168.211.79   -a	192.168.211.14
# nvme	discover	-t   tcp    -w	192.168.211.79   -a	192.168.211.15


----
. 執行 `nvme connect-all` 跨所有節點支援的 NVMe / TCP 啟動器目標生命週期執行命令、並將控制器遺失逾時週期設為至少 30 分鐘或 1800 秒：
+
[listing]
----
nvme connect-all -t tcp -w host-traddr -a traddr -l 1800
----
+
* 輸出範例： *

+
[listing]
----
# nvme	connect-all	-t	tcp	-w	192.168.111.79	-a	192.168.111.14	-l	1800
# nvme	connect-all	-t	tcp	-w	192.168.111.79	-a	192.168.111.15	-l	1800
# nvme	connect-all	-t	tcp	-w	192.168.211.79	-a	192.168.211.14	-l	1800
# nvme	connect-all	-t	tcp	-w	192.168.211.79	-a	192.168.211.15	-l	1800


----




== 驗證NVMe

您可以使用下列程序來驗證 NVMe 。

.步驟
. 確認已啟用核心內建 NVMe 多重路徑：
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
. 確認適當的 NVMe 設定（例如、 `model` 設定為 `NetApp ONTAP Controller` 和負載平衡 `iopolicy` 設定為 `round-robin`）對於相應的 ONTAP 命名空間，正確地反映在主機上：
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. 確認已在主機上建立並正確探索命名空間：
+
[listing]
----
# nvme list
----
+
* 輸出範例： *

+
[listing]
----
Node         SN                   Model
---------------------------------------------------------
/dev/nvme0n1 81Gx7NSiKSQqAAAAAAAB	NetApp ONTAP Controller


Namespace Usage    Format             FW             Rev
-----------------------------------------------------------
1                 21.47 GB / 21.47 GB	4 KiB + 0 B   FFFFFFFF
----
. 確認每個路徑的控制器狀態均為有效、且具有正確的ANA狀態：
+
[role="tabbed-block"]
====
.NVMe / FC
--
[listing]
----
# nvme list-subsys /dev/nvme3n1
----
* 輸出範例： *

[listing, subs="+quotes"]
----
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.8e501f8ebafa11ec9b99d039ea359e4b:subsystem.rhel_163_Qle2742
+- nvme0 *fc* traddr=nn-0x204dd039ea36a105:pn-0x2050d039ea36a105 host_traddr=nn-0x20000024ff7f4994:pn-0x21000024ff7f4994 *live non-optimized*
+- nvme1 *fc* traddr=nn-0x204dd039ea36a105:pn-0x2050d039ea36a105 host_traddr=nn-0x20000024ff7f4994:pn-0x21000024ff7f4994 *live non-optimized*
+- nvme2 *fc* traddr=nn-0x204dd039ea36a105:pn-0x204fd039ea36a105 host_traddr=nn-0x20000024ff7f4995:pn-0x21000024ff7f4995 *live optimized*
+- nvme3 *fc* traddr=nn-0x204dd039ea36a105:pn-0x204ed039ea36a105 host_traddr=nn-0x20000024ff7f4994:pn-0x21000024ff7f4994 *live optimized*

----
--
.NVMe / TCP
--
[listing]
----
# nvme list-subsys /dev/nvme0n1
----
* 輸出範例： *

[listing, subs="+quotes"]
----
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:subsystem.rhel_tcp_165\
+- nvme0 *tcp* traddr=192.168.111.15 trsvcid=4420 host_traddr=192.168.111.79 *live non-optimized*
+- nvme1 *tcp* traddr=192.168.111.14 trsvcid=4420 host_traddr=192.168.111.79 *live optimized*
+- nvme2 *tcp* traddr=192.168.211.15 trsvcid=4420 host_traddr=192.168.211.79 *live non-optimized*
+- nvme3 *tcp* traddr=192.168.211.14 trsvcid=4420 host_traddr=192.168.211.79 *live optimized*

----
--
====
. 驗證NetApp外掛程式是否顯示每ONTAP 個版本名稱空間裝置的正確值：
+
[role="tabbed-block"]
====
.欄位
--
[listing]
----
# nvme netapp ontapdevices -o column
----
* 輸出範例： *

[listing]
----
Device        Vserver   Namespace Path
----------------------- ------------------------------
/dev/nvme0n1 vs_tcp79           /vol/vol1/ns


NSID       UUID                                   Size
------------------------------------------------------------
1          aa197984-3f62-4a80-97de-e89436360cec	21.47GB
----
--
.JSON
--
[listing]
----
# nvme netapp ontapdevices -o json
----
* 輸出範例 *

[listing]
----
{
  "ONTAPdevices”: [
    {
      "Device”: "/dev/nvme0n1",
      "Vserver”: "vs_tcp79",
      "Namespace Path”: "/vol/vol1/ns",
      "NSID”: 1,
      "UUID”: "aa197984-3f62-4a80-97de-e89436360cec",
      "Size”: "21.47GB",
      "LBA_Data_Size”: 4096,
      "Namespace Size" : 5242880
    },
]

}


----
--
====




== 已知問題

採用 ONTAP 版本的 RHEL 8.9 的 NVMe 主機組態有下列已知問題：

[cols="20,40,40"]
|===
| NetApp錯誤ID | 標題 | 說明 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1479047["1479047"^] | RHEL 8.9 NVMe 主機會建立重複的持續探索控制器 | 在NVMe over Fabrics（NVMe）主機上、您可以使用「NVMe Discover-p」命令來建立持續探索控制器（PD）。使用此命令時、每個啟動器目標組合只能建立一個PDC。  不過、如果您在 NVMe 主機上執行 Red Hat Enterprise Linux （ RHEL ） 8.9 、則每次執行「 NVMe 探索 -p 」時都會建立重複的 PDC 。這會導致主機和目標上的資源使用不必要。 
|===