---
sidebar: sidebar 
permalink: nvme-rhel-10x.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: 如何為 RHEL 10x 設定 NVMe-oF 主機（使用ONTAP） 
---
= 配置 RHEL 10x 以支援 NVMe-oF 和ONTAP存儲
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Red Hat Enterpirse Linux (RHEL) 主機支援具有非對稱命名空間存取 (ANA) 的 NVMe over Fibre Channel (NVMe/FC) 和 NVMe over TCP (NVMe/TCP) 協定。  ANA 提供與 iSCSI 和 FCP 環境中的非對稱邏輯單元存取 (ALUA) 等效的多路徑功能。

了解如何為 RHEL 10x 設定 NVMe over Fabrics (NVMe-oF) 主機。如需更多支援和功能信息，請參閱 link:nvme-rhel-supported-features.html["RHEL ONTAP支援與功能"]。

NVMe-oF 與 RHEL 10x 有以下已知限制：

* 不支援 NVMe-oF 的 DM 多路徑支援。
* 這 `nvme disconnect-all`此命令會斷開根檔案系統和資料檔案系統，可能會導致系統不穩定。請勿在透過 NVMe-TCP 或 NVMe-FC 命名空間從 SAN 啟動的系統上執行此操作。




== 步驟 1 ：選擇性啟用 SAN 開機

您可以設定主機以使用 SAN 啟動來簡化部署並提高可擴充性。使用link:https://mysupport.netapp.com/matrix/#welcome["互通性對照表工具"^]驗證您的 Linux 作業系統、主機匯流排適配器 (HBA)、HBA 韌體、HBA 啟動 BIOS 和ONTAP版本是否支援 SAN 啟動。

.步驟
. https://docs.netapp.com/us-en/ontap/san-admin/create-nvme-namespace-subsystem-task.html["建立 NVMe 命名空間並將其對應到主機"^] 。
. 在伺服器 BIOS 中為 SAN 啟動命名空間對應到的連接埠啟用 SAN 啟動。
+
如需如何啟用HBA BIOS的相關資訊、請參閱廠商專屬的文件。

. 重新啟動主機並驗證作業系統是否已啟動並正在運行。




== 步驟 2：安裝 RHEL 和 NVMe 軟體並驗證您的配置

若要為 NVMe-oF 設定主機，您應該安裝主機和 NVMe 軟體包，啟用多路徑，並驗證主機 NQN 設定。

.步驟
. 在伺服器上安裝 RHEL 10x。安裝完成後，請確認您執行的是所需的 RHEL 10x 核心：
+
[source, cli]
----
uname -r
----
+
RHEL 核心版本範例：

+
[listing]
----
6.12.0-55.9.1.el10_0.x86_64
----
. 安裝「NVMe-CLI（NVMe - CLI）套件：
+
[source, cli]
----
rpm -qa|grep nvme-cli
----
+
下面的例子展示了 `nvme-cli`軟體包版本：

+
[listing]
----
nvme-cli-2.11-5.el10.x86_64
----
. 安裝 `libnvme` 套件：
+
[source, cli]
----
rpm -qa|grep libnvme
----
+
下面的例子展示了 `libnvme`軟體包版本：

+
[listing]
----
libnvme-1.11.1-1.el10.x86_64
----
. 在主機上，檢查 hostnqn 字串 `/etc/nvme/hostnqn` ：
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
下面的例子展示了 `hostnqn`版本：

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
----
. 在ONTAP系統中，驗證以下資訊： `hostnqn`字串匹配 `hostnqn`ONTAP儲存系統中對應子系統的字串：
+
[source, cli]
----
::> vserver nvme subsystem host show -vserver vs_nvme_194_rhel10
----
+
.顯示範例
[%collapsible]
====
[listing]
----
Vserver Subsystem Priority  Host NQN
------- --------- --------  ------------------------------------------------
vs_ nvme_194_rhel10
        nvme4
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048- c7c04f425633
        nvme_1
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048- c7c04f425633
        nvme_2
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048- c7c04f425633
        nvme_3
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048- c7c04f425633
4 entries were displayed.
----
====



NOTE: 如果 `hostnqn`字串不匹配，請使用 `vserver modify`命令來更新 `hostnqn`對應ONTAP儲存系統子系統上的字串以匹配 `hostnqn`字串來自 `/etc/nvme/hostnqn`在主機上。



== 步驟 3：設定 NVMe/FC 和 NVMe/TCP

使用 Broadcom/Emulex 或 Marvell/QLogic 適配器配置 NVMe/FC，或使用手動發現和連接操作來設定 NVMe/TCP。

[role="tabbed-block"]
====
.FC——Broadcom/Emulex
--
為 Broadcom / Emulex 介面卡設定 NVMe / FC 。

. 確認您使用的是支援的介面卡機型：
+
.. 顯示模型名稱：
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
您應該會看到下列輸出：

+
[listing]
----
LPe36002-M64
LPe36002-M64
----
.. 顯示模型描述：
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
您應該會看到類似以下範例的輸出：

+
[listing]
----
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
----


. 驗證您使用的是建議的Broadcom `lpfc` 韌體與收件匣驅動程式：
+
.. 顯示韌體版本：
+
[source, cli]
----
cat /sys/class/scsi_host/host*/fwrev
----
+
該命令返回韌體版本：

+
[listing]
----
14.0.539.16, sli-4:6:d
14.0.539.16, sli-4:6:d
----
.. 顯示收件匣驅動程式版本：
+
[source, cli]
----
cat /sys/module/lpfc/version
----
+
以下範例顯示了驅動程式版本：

+
[listing]
----
0:14.4.0.6
----


+
如需支援的介面卡驅動程式和韌體版本的最新清單，請參閱link:https://mysupport.netapp.com/matrix/["互通性對照表工具"^]。

. 請確認 `lpfc_enable_fc4_type` 設為 `3`：
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. 確認您可以檢視啟動器連接埠：
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
您應該會看到類似以下內容的輸出：

+
[listing]
----
0x100000109b1c1205
----
. 驗證啟動器連接埠是否在線上：
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
您應該會看到下列輸出：

+
[listing]
----
Online
Online
----
. 確認已啟用 NVMe / FC 啟動器連接埠、且目標連接埠可見：
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc2 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc2 WWPN x100000109bf044b1 WWNN x200000109bf044b1 DID x022a00 *ONLINE*
NVME RPORT       WWPN x202fd039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x021310 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x202dd039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x020b10 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000810 Cmpl 0000000810 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000007b098f07 Issue 000000007aee27c4 OutIO ffffffffffe498bd
        abort 000013b4 noxri 00000000 nondlp 00000058 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 000013b4 Err 00021443

NVME Initiator Enabled
XRI Dist lpfc3 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc3 WWPN x100000109bf044b2 WWNN x200000109bf044b2 DID x021b00 *ONLINE*
NVME RPORT       WWPN x2033d039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x020110 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2032d039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x022910 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000840 Cmpl 0000000840 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000007afd4434 Issue 000000007ae31b83 OutIO ffffffffffe5d74f
        abort 000014a5 noxri 00000000 nondlp 0000006a qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 000014a5 Err 0002149a
----
=====


--
.FC——Marvell/QLogic
--
為 Marvell/QLogic 介面卡設定 NVMe / FC 。

. 驗證您使用的適配器驅動程式和韌體版本是否受支援：
+
[source, cli]
----
cat /sys/class/fc_host/host*/symbolic_name
----
+
以下範例顯示了驅動程式和韌體版本：

+
[listing]
----
QLE2872 FW:v9.15.00 DVR:v10.02.09.300-k
QLE2872 FW:v9.15.00 DVR:v10.02.09.300-k
----
. 請確認 `ql2xnvmeenable` 已設定。這可讓 Marvell 介面卡作為 NVMe / FC 啟動器運作：
+
[source, cli]
----
cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
----
+
預期輸出為 1 。



--
.TCP
--
NVMe/TCP 協定不支援自動連線操作。相反，您可以透過執行 NVMe/TCP 來發現 NVMe/TCP 子系統和命名空間 `connect`或者 `connect-all`手動操作。

. 檢查啟動器連接埠是否可以跨支援的 NVMe/TCP LIF 取得發現日誌頁面資料：
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme discover -t tcp -w 192.168.20.1 -a 192.168.20.20

Discovery Log Number of Records 8, Generation counter 18
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  4
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.64e65e6caae711ef9668d039ea951c46:discovery
traddr:  192.168.21.21
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  2
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.64e65e6caae711ef9668d039ea951c46:discovery
traddr:  192.168.20.21
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 2======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  3
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.64e65e6caae711ef9668d039ea951c46:discovery
traddr:  192.168.21.20
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 3======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  1
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.64e65e6caae711ef9668d039ea951c46:discovery
traddr:  192.168.20.20
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 4======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  4
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.64e65e6caae711ef9668d039ea951c46:subsystem.rhel10_tcp_subsystem
traddr:  192.168.21.21
eflags:  none
sectype: none
=====Discovery Log Entry 5======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  2
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.64e65e6caae711ef9668d039ea951c46:subsystem.rhel10_tcp_subsystem
traddr:  192.168.20.21
eflags:  none
sectype: none
=====Discovery Log Entry 6======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  3
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.64e65e6caae711ef9668d039ea951c46:subsystem.rhel10_tcp_subsystem
traddr:  192.168.21.20
eflags:  none
sectype: none
=====Discovery Log Entry 7======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  1
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.64e65e6caae711ef9668d039ea951c46:subsystem.rhel10_tcp_subsystem
traddr:  192.168.20.20
eflags:  none
sectype: none
----
=====
. 驗證其他 NVMe/TCP 啟動器-目標 LIF 組合是否可以成功檢索發現日誌頁面資料：
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme discover -t tcp -w 192.168.20.1 -a 192.168.20.20
nvme discover -t tcp -w 192.168.21.1 -a 192.168.21.20
nvme discover -t tcp -w 192.168.20.1 -a 192.168.20.21
nvme discover -t tcp -w 192.168.21.1 -a 192.168.21.21
----
=====
. 執行 `nvme connect-all` 跨所有節點支援的 NVMe / TCP 啟動器目標生命體執行命令：
+
[source, cli]
----
nvme connect-all -t tcp -w host-traddr -a traddr
----
+
.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme	connect-all	-t	tcp	-w	192.168.20.1	-a	192.168.20.20
nvme	connect-all	-t	tcp	-w	192.168.21.1	-a	192.168.21.20
nvme	connect-all	-t	tcp	-w	192.168.20.1	-a	192.168.20.21
nvme	connect-all	-t	tcp	-w	192.168.21.1	-a	192.168.21.21
----
=====


[NOTE]
====
從 RHEL 9.4 開始，NVMe/TCP 的設置 `ctrl_loss_tmo timeout`自動設定為“關閉”。因此：

* 重試次數沒有限制（無限重試）。
* 您不需要手動配置特定的 `ctrl_loss_tmo timeout`使用時長 `nvme connect`或者 `nvme connect-all`命令（選項 -l ）。
* 如果發生路徑故障，NVMe/TCP 控制器不會逾時，並且會無限期地保持連線。


====
--
====


== 步驟 4：（可選）為 NVMe/FC 啟用 1MB I/O

ONTAP在識別控制器資料中報告最大資料傳輸大小 (MDTS) 為 8。這意味著最大 I/O 請求大小可達 1MB。若要向 Broadcom NVMe/FC 主機發出 1MB 大小的 I/O 要求，您應該會增加 `lpfc`的價值 `lpfc_sg_seg_cnt`參數從預設值 64 更改為 256。


NOTE: 這些步驟不適用於 Qlogic NVMe / FC 主機。

.步驟
. 將 `lpfc_sg_seg_cnt`參數設定為 256 ：
+
[source, cli]
----
cat /etc/modprobe.d/lpfc.conf
----
+
您應該會看到類似以下範例的輸出：

+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. 執行 `dracut -f`命令，然後重新啟動主機。
. 確認的值 `lpfc_sg_seg_cnt`為 256 ：
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== 步驟 5：驗證 NVMe 啟動服務

這 `nvmefc-boot-connections.service`和 `nvmf-autoconnect.service`NVMe/FC 中包含的啟動服務 `nvme-cli`系統啟動時，軟體包會自動啟用。

啟動完成後，驗證 `nvmefc-boot-connections.service`和 `nvmf-autoconnect.service`啟動服務已啟用。

.步驟
. 確認 `nvmf-autoconnect.service`已啟用：
+
[source, cli]
----
systemctl status nvmf-autoconnect.service
----
+
.顯示範例輸出
[%collapsible]
====
[listing]
----
nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot
     Loaded: loaded (/usr/lib/systemd/system/nvmf-autoconnect.service; enabled; preset: disabled)
     Active: inactive (dead)

Jun 10 04:06:26 SR630-13-201.lab.eng.btc.netapp.in systemd[1]: Starting Connect NVMe-oF subsystems automatically during boot...
Jun 10 04:06:26 SR630-13-201.lab.eng.btc.netapp.in systemd[1]: nvmf-autoconnect.service: Deactivated successfully.
Jun 10 04:06:26 SR630-13-201.lab.eng.btc.netapp.in systemd[1]: Finished Connect NVMe-oF subsystems automatically during boot.
----
====
. 確認 `nvmefc-boot-connections.service`已啟用：
+
[source, cli]
----
systemctl status nvmefc-boot-connections.service
----
+
.顯示範例輸出
[%collapsible]
====
[listing]
----
nvmefc-boot-connections.service - Auto-connect to subsystems on FC-NVME devices found during boot
     Loaded: loaded (/usr/lib/systemd/system/nvmefc-boot-connections.service; enabled; preset: enabled)
     Active: inactive (dead) since Tue 2025-06-10 01:08:36 EDT; 2h 59min ago
   Main PID: 7090 (code=exited, status=0/SUCCESS)
        CPU: 30ms

Jun 10 01:08:36 localhost systemd[1]: Starting Auto-connect to subsystems on FC-NVME devices found during boot...
Jun 10 01:08:36 localhost systemd[1]: nvmefc-boot-connections.service: Deactivated successfully.
Jun 10 01:08:36 localhost systemd[1]: Finished Auto-connect to subsystems on FC-NVME devices found during boot.
----
====




== 步驟 6：驗證多路徑配置

驗證核心內建 NVMe 多重路徑狀態， ANA 狀態和 ONTAP 命名空間是否適用於 NVMe 組態。

.步驟
. 確認已啟用核心內建 NVMe 多重路徑：
+
[source, cli]
----
cat /sys/module/nvme_core/parameters/multipath
----
+
您應該會看到下列輸出：

+
[listing]
----
Y
----
. 驗證個別 ONTAP 命名空間的適當 NVMe 設定（例如、模型設定為 NetApp ONTAP 控制器、負載平衡 iopolicing 設定為循環）是否正確反映在主機上：
+
.. 顯示子系統：
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
您應該會看到下列輸出：

+
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
.. 顯示策略：
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
您應該會看到下列輸出：

+
[listing]
----
round-robin
round-robin
----


. 確認已在主機上建立並正確探索命名空間：
+
[source, cli]
----
nvme list
----
+
.顯示範例
[%collapsible]
====
[listing]
----
Node         SN                   Model
---------------------------------------------------------
/dev/nvme4n1 81Ix2BVuekWcAAAAAAAB	NetApp ONTAP Controller


Namespace Usage    Format             FW             Rev
-----------------------------------------------------------
1                 21.47 GB / 21.47 GB	4 KiB + 0 B   FFFFFFFF
----
====
. 確認每個路徑的控制器狀態均為有效、且具有正確的ANA狀態：
+
[role="tabbed-block"]
====
.NVMe / FC
--
[source, cli]
----
nvme list-subsys /dev/nvme5n1
----
.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys5 - NQN=nqn.1992-08.com.netapp:sn.f7565b15a66911ef9668d039ea951c46:subsystem.nvme1
               hostnqn=nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-c7c04f425633
\
 +- nvme126 *fc* traddr=nn-0x2036d039ea951c45:pn-0x2038d039ea951c45,host_traddr=nn-0x2000f4c7aa0cd7c3:pn-0x2100f4c7aa0cd7c3 *live optimized*
 +- nvme176 *fc* traddr=nn-0x2036d039ea951c45:pn-0x2037d039ea951c45,host_traddr=nn-0x2000f4c7aa0cd7c2:pn-0x2100f4c7aa0cd7c2 *live optimized*
 +- nvme5 *fc* traddr=nn-0x2036d039ea951c45:pn-0x2039d039ea951c45,host_traddr=nn-0x2000f4c7aa0cd7c2:pn-0x2100f4c7aa0cd7c2 *live non-optimized*
 +- nvme71 *fc* traddr=nn-0x2036d039ea951c45:pn-0x203ad039ea951c45,host_traddr=nn-0x2000f4c7aa0cd7c3:pn-0x2100f4c7aa0cd7c3 *live non-optimized*
----
=====
--
.NVMe / TCP
--
[source, cli]
----
nvme list-subsys /dev/nvme4n2
----
.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys4 - NQN=nqn.1992-08.com.netapp:sn.64e65e6caae711ef9668d039ea951c46:subsystem.nvme4
               hostnqn=nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0035-5910-804b-c2c04f444d33
\
+- nvme102 *tcp* traddr=192.168.21.20,trsvcid=4420,host_traddr=192.168.21.1,src_addr=192.168.21.1 *live non-optimized*
+- nvme151 *tcp* traddr=192.168.21.21,trsvcid=4420,host_traddr=192.168.21.1,src_addr=192.168.21.1 *live optimized*
+- nvme4 *tcp* traddr=192.168.20.20,trsvcid=4420,host_traddr=192.168.20.1,src_addr=192.168.20.1 *live non-optimized*
+- nvme53 *tcp* traddr=192.168.20.21,trsvcid=4420,host_traddr=192.168.20.1,src_addr=192.168.20.1 *live optimized*
----
=====
--
====
. 驗證NetApp外掛程式是否顯示每ONTAP 個版本名稱空間裝置的正確值：
+
[role="tabbed-block"]
====
.欄位
--
[source, cli]
----
nvme netapp ontapdevices -o column
----
.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----

Device        Vserver   Namespace Path
----------------------- ------------------------------
/dev/nvme10n1     vs_tcp_rhel10       /vol/vol10/ns10

NSID       UUID                                   Size
----------------------- ------------------------------
1    bbf51146-fc64-4197-b8cf-8a24f6f359b3   21.47GB
----
=====
--
.JSON
--
[source, cli]
----
nvme netapp ontapdevices -o json
----
.顯示範例
[%collapsible]
=====
[listing, subs="+quotes"]
----
{
  "ONTAPdevices":[
    {
      "Device":"/dev/nvme10n1",
      "Vserver":"vs_tcp_rhel10",
      "Namespace_Path":"/vol/vol10/ns10",
      "NSID":1,
      "UUID":"bbf51146-fc64-4197-b8cf-8a24f6f359b3",
      "Size":"21.47GB",
      "LBA_Data_Size":4096,
      "Namespace_Size":5242880
}
]
    }
----
=====
--
====




== 步驟 7：設定安全帶內身份驗證

支援透過 NVMe/TCP 在 RHEL 10x 主機和ONTAP控制器之間進行安全的帶內身份驗證。

每個主機或控制器必須與一個 `DH-HMAC-CHAP`金鑰來設定安全身份驗證。  `DH-HMAC-CHAP`金鑰是 NVMe 主機或控制器的 NQN 與管理員配置的身份驗證金鑰的組合。若要驗證其對等端點、 NVMe 主機或控制器必須識別與對等端點相關的金鑰。

使用 CLI 或設定 JSON 檔案設定安全帶內身份驗證。如果您需要為不同的子系統指定不同的 dhchap 金鑰、則必須使用組態 JSON 檔案。

[role="tabbed-block"]
====
.CLI
--
使用 CLI 設定安全的頻內驗證。

. 取得主機 NQN ：
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
. 為 RHEL 10x 主機產生 dhchap 金鑰。
+
以下輸出描述了 `gen-dhchap-key`命令參數：

+
[listing]
----
nvme gen-dhchap-key -s optional_secret -l key_length {32|48|64} -m HMAC_function {0|1|2|3} -n host_nqn
•	-s secret key in hexadecimal characters to be used to initialize the host key
•	-l length of the resulting key in bytes
•	-m HMAC function to use for key transformation
0 = none, 1- SHA-256, 2 = SHA-384, 3=SHA-512
•	-n host NQN to use for key transformation
----
+
在下列範例中、會產生一個隨機的 dhchap 金鑰、其中 HMAC 設為 3 （ SHA-512 ）。

+
[listing]
----
nvme gen-dhchap-key -m 3 -n nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0035-5910-804b-c2c04f444d33
DHHC-1:03:7zf8I9gaRcDWH3tCH5vLGaoyjzPIvwNWusBfKdpJa+hia1aKDKJQ2o53pX3wYM9xdv5DtKNNhJInZ7X8wU2RQpQIngc=:
----
. 在 ONTAP 控制器上、新增主機並指定兩個 dhchap 金鑰：
+
[source, cli]
----
vserver nvme subsystem host add -vserver <svm_name> -subsystem <subsystem> -host-nqn <host_nqn> -dhchap-host-secret <authentication_host_secret> -dhchap-controller-secret <authentication_controller_secret> -dhchap-hash-function {sha-256|sha-512} -dhchap-group {none|2048-bit|3072-bit|4096-bit|6144-bit|8192-bit}
----
. 主機支援兩種驗證方法：單向和雙向。在主機上、連線至 ONTAP 控制器、並根據所選的驗證方法指定 dhchap 金鑰：
+
[source, cli]
----
nvme connect -t tcp -w <host-traddr> -a <tr-addr> -n <host_nqn> -S <authentication_host_secret> -C <authentication_controller_secret>
----
. 驗證 `nvme connect authentication` 命令驗證主機和控制器 dhchap 金鑰：
+
.. 驗證主機 dhchap 金鑰：
+
[source, cli]
----
cat /sys/class/nvme-subsystem/<nvme-subsysX>/nvme*/dhchap_secret
----
+
.顯示單向組態的輸出範例
[%collapsible]
=====
[listing]
----
cat /sys/class/nvme-subsystem/nvme-subsys1/nvme*/dhchap_secret
DHHC- 1:03:fMCrJharXUOqRoIsOEaG6m2PH1yYvu5+z3jTmzEKUbcWu26I33b93b
il2WR09XDho/ld3L45J+0FeCsStBEAfhYgkQU=:
DHHC- 1:03:fMCrJharXUOqRoIsOEaG6m2PH1yYvu5+z3jTmzEKUbcWu26I33b93b
il2WR09XDho/ld3L45J+0FeCsStBEAfhYgkQU=:
DHHC- 1:03:fMCrJharXUOqRoIsOEaG6m2PH1yYvu5+z3jTmzEKUbcWu26I33b93b
il2WR09XDho/ld3L45J+0FeCsStBEAfhYgkQU=:
DHHC- 1:03:fMCrJharXUOqRoIsOEaG6m2PH1yYvu5+z3jTmzEKUbcWu26I33b93b
il2WR09XDho/ld3L45J+0FeCsStBEAfhYgkQU=:
----
=====
.. 驗證控制器 dhchap 按鍵：
+
[source, cli]
----
cat /sys/class/nvme-subsystem/<nvme-subsysX>/nvme*/dhchap_ctrl_secret
----
+
.顯示雙向組態的輸出範例
[%collapsible]
=====
[listing]
----
cat /sys/class/nvme-subsystem/nvme-subsys6/nvme*/dhchap_ctrl_secret
DHHC- 1:03:7zf8I9gaRcDWH3tCH5vLGaoyjzPIvwNWusBfKdpJa+hia
1aKDKJQ2o53pX3wYM9xdv5DtKNNhJInZ7X8wU2RQpQIngc=:

DHHC- 1:03:7zf8I9gaRcDWH3tCH5vLGaoyjzPIvwNWusBfKdpJa+hia
1aKDKJQ2o53pX3wYM9xdv5DtKNNhJInZ7X8wU2RQpQIngc=:

DHHC- 1:03:7zf8I9gaRcDWH3tCH5vLGaoyjzPIvwNWusBfKdpJa+hia
1aKDKJQ2o53pX3wYM9xdv5DtKNNhJInZ7X8wU2RQpQIngc=:

DHHC- 1:03:7zf8I9gaRcDWH3tCH5vLGaoyjzPIvwNWusBfKdpJa+hia
1aKDKJQ2o53pX3wYM9xdv5DtKNNhJInZ7X8wU2RQpQIngc=:
----
=====




--
.JSON
--
當ONTAP控制器上有多個 NVMe 子系統可用時，您可以使用 `/etc/nvme/config.json`文件與 `nvme connect-all`命令。

使用 `-o`選項來產生 JSON 檔案。有關更多語法選項，請參閱 NVMe connect-all 手冊頁。

. 配置 JSON 檔案。
+

NOTE: 在以下範例中，  `dhchap_key`對應於 `dhchap_secret`和 `dhchap_ctrl_key`對應於 `dhchap_ctrl_secret` 。

+
.顯示範例
[%collapsible]
=====
[listing]
----
cat /etc/nvme/config.json
[
{
"hostnqn":"nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0035-5910-804b-c2c04f444d33",
"hostid":"4c4c4544-0035-5910-804b-c2c04f444d33",
"dhchap_key":"DHHC-1:03:7zf8I9gaRcDWH3tCH5vLGaoyjzPIvwNWusBfKdpJa+hia1aKDKJQ2o53pX3wYM9xdv5DtKNNhJInZ7X8wU2RQpQIngc=:",
"subsystems":[
{
"nqn":"nqn.1992-08.com.netapp:sn.127ade26168811f0a50ed039eab69ad3:subsystem.inband_unidirectional",
"ports":[
{
"transport":"tcp",
"traddr":"192.168.20.17",
"host_traddr":"192.168.20.1",
"trsvcid":"4420"
},
{
"transport":"tcp",
"traddr":"192.168.20.18",
"host_traddr":"192.168.20.1",
"trsvcid":"4420"
},
{
"transport":"tcp",
"traddr":"192.168.21.18",
"host_traddr":"192.168.21.1",
"trsvcid":"4420"
},
{
"transport":"tcp",
"traddr":"192.168.21.17",
"host_traddr":"192.168.21.1",
"trsvcid":"4420"
}]
----
=====
. 使用組態 JSON 檔案連線至 ONTAP 控制器：
+
[source, cli]
----
nvme connect-all -J /etc/nvme/config.json
----
+
.顯示範例
[%collapsible]
=====
[listing]
----
traddr=192.168.20.20 is already connected
traddr=192.168.20.20 is already connected
traddr=192.168.20.20 is already connected
traddr=192.168.20.20 is already connected
traddr=192.168.20.20 is already connected
traddr=192.168.20.20 is already connected
traddr=192.168.20.20 is already connected
traddr=192.168.20.20 is already connected
traddr=192.168.20.21 is already connected
traddr=192.168.20.21 is already connected
traddr=192.168.20.21 is already connected
traddr=192.168.20.21 is already connected
traddr=192.168.20.21 is already connected
traddr=192.168.20.21 is already connected
traddr=192.168.20.21 is already connected
traddr=192.168.20.21 is already connected
----
=====
. 驗證每個子系統的相應控制器是否已啟用 dhchap 機密。
+
.. 驗證主機 dhchap 金鑰：
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys0/nvme0/dhchap_secret
----
+
以下範例顯示了 dhchap 金鑰：

+
[listing]
----
DHHC-1:03:7zf8I9gaRcDWH3tCH5vLGaoyjzPIvwNWusBfKdpJa+hia1
aKDKJQ2o53pX3wYM9xdv5DtKNNhJInZ7X8wU2RQpQIngc=:
----
.. 驗證控制器 dhchap 按鍵：
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys0/nvme0/dhchap_ctrl_secret
----
+
您應該會看到類似以下範例的輸出：

+
[listing]
----
DHHC-1:03:fMCrJharXUOqRoIsOEaG6m2PH1yYvu5+z3jT
mzEKUbcWu26I33b93bil2WR09XDho/ld3L45J+0FeCsStBEAfhYgkQU=:
----




--
====


== 步驟 8 ：檢閱已知問題

沒有已知問題。
