---
sidebar: sidebar 
permalink: nvme-windows-2025.html 
keywords: nvme, windows, enterprise 
summary: 適用於 Windows Server 2025 和ONTAP的 NVMe/FC 主機配置。 
---
= 使用適用於 ONTAP 的 NVMe / FC 來設定 Windows Server 2025
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在執行 Windows Server 2025 的主機上設定 NVMe over Fibre Channel （ NVMe / FC ），以便與 ONTAP LUN 一起運作。

.關於這項工作
您可以在 Windows 2025 的 NVMe / FC 主機組態中使用下列支援。在開始設定程序之前，您也應該先檢閱已知的限制。

* 可用支援：
+
從 ONTAP 9.10.1 開始， Windows Server 2025 支援 NVMe / FC 。

+
如需支援的 FC 介面卡和控制器清單，請參閱link:https://hwu.netapp.com/Home/Index["Hardware Universe"^]。如需支援組態和版本的最新清單，請參閱link:https://mysupport.netapp.com/matrix/["互通性對照表工具"^]。

* 已知限制：
+
NVMe / FC 不支援 Windows 容錯移轉叢集，因為 ONTAP 目前不支援 NVMe / FC 的持續保留。

+

NOTE: Broadcom 隨附 Windows NVMe / FC 的外部驅動程式，這是轉譯式 SCSI 變速度 NVMe 驅動程式，而非真正的 NVMe / FC 驅動程式。轉譯的負荷不一定會影響效能，但會抵消 NVMe / FC 的效能優勢。因此，在 Windows 伺服器上， NVMe / FC 和 FCP 的效能是相同的，不像其他作業系統，例如 Linux ，那就是 NVMe / FC 的效能遠比 FCP 的效能好。





== 啟用NVMe/FC

在 Windows 啟動器主機上啟用 FC/NVMe 。

.步驟
. 在 Windows 主機上安裝 Emulex HBA Manager 公用程式。
. 在每個HBA啟動器連接埠上、設定下列HBA驅動程式參數：
+
** 啟用NVMe = 1
** NVMEMode = 0


. 重新啟動主機。




== 設定 Broadcom FC 介面卡

Broadcom 啟動器可透過相同的 32G FC 介面卡連接埠，同時處理 NVMe / FC 和 FCP 流量。對於 FCP 和 FC/NVMe ，您應該使用 Microsft 裝置專用模組（ DSM ）做為 Microsoft 多重路徑 I/O （ MPIO ）選項。

A `+hostnqn+` 與 Windows 環境中的 Broadcom 介面卡（含 FC/NVMe ）的每個主機匯流排介面卡（ HBA ）連接埠相關聯。 `+hostnqn+`格式如下例所示：

....
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9765
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9766
....


=== 為 NVMe 裝置啟用 MPIO

您需要啟用適用於 NVMe 裝置的 MPIO ，才能在 Windows 主機上完成 NVMe 組態。

.步驟
. 安裝 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Windows主機公用程式套件7.1"] 設定FC和NVMe通用的驅動程式參數。
. 開啟MPIO內容。
. 從*探索多重路徑*索引標籤、新增NVMe所列的裝置ID。
+
MPIO會感知NVMe裝置、這些裝置可在磁碟管理下看到。

. 打開* Disk Management（磁碟管理）*、然後移至* Disk Properties（磁碟內容）*。
. 從 *MPIO 選項卡中，選擇 * 詳細資料 * 。
. 設定下列 Microsoft DSM 設定：
+
** PathVerfiedPeriod:* 10*
** PathVerifyEnabled:* Enabled*
** 重試計數：* 6 *
** 重試時間間隔：* 1*
** PDORemovedPeriod:* 130*


. 選擇MPIO Policy * Round Robin with Subscal*。
. 變更登錄值：
+
[listing]
----
HKLM\SYSTEM\CurrentControlSet\Services\mpio\Parameters\PathRecoveryInterval DWORD -> 30

HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\ UseCustomPathRecoveryInterval  DWORD-> 1
----
. 重新啟動主機。




== 驗證 NVMe / FC 組態

確認已探索到 NVMe 子系統，且 ONTAP 命名空間適用於 NVMe 組態。

.步驟
. 確認「連接埠類型」為 `+FC+NVMe+`：
+
`listhba`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
Port WWN       : 10:00:00:10:9b:1b:97:65
Node WWN       : 20:00:00:10:9b:1b:97:65
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 0
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 0
*Port Type*      : *FC+NVMe*
Model          : LPe32002-M2

Port WWN       : 10:00:00:10:9b:1b:97:66
Node WWN       : 20:00:00:10:9b:1b:97:66
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 1
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 1
Port Type      : FC+NVMe
Model          : LPe32002-M2
----
====
. 確認已探索到 NVMe / FC 子系統：
+
** `+nvme-list+`
+
.顯示範例
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:09:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0180
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:06:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0181
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available
Note: At present Namespace Management is not supported by NetApp Arrays.
----
====
** `nvme-list`
+
.顯示範例
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:07:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0140
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:08:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0141
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

Note: At present Namespace Management is not supported by NetApp Arrays.
----
====


. 確認已建立命名空間：
+
`+nvme-list-ns+`

+
.顯示範例
[%collapsible]
====
[listing]
----
Active Namespaces (attached to controller 0x0141):

                                       SCSI           SCSI           SCSI
   NSID           DeviceName        Bus Number    Target Number     OS LUN
-----------  --------------------  ------------  ---------------   ---------
0x00000001   \\.\PHYSICALDRIVE9         0               1              0
0x00000002   \\.\PHYSICALDRIVE10        0               1              1
0x00000003   \\.\PHYSICALDRIVE11        0               1              2
0x00000004   \\.\PHYSICALDRIVE12        0               1              3
0x00000005   \\.\PHYSICALDRIVE13        0               1              4
0x00000006   \\.\PHYSICALDRIVE14        0               1              5
0x00000007   \\.\PHYSICALDRIVE15        0               1              6
0x00000008   \\.\PHYSICALDRIVE16        0               1              7

----
====

