---
settings:
  name: ONTAP SAN Host Utilities
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: ONTAP SAN 主機和雲端用戶端
    url: "/index.html"
  - title: 瞭解 SAN 主機組態
    url: "/overview.html"
  - title: 安裝 SAN 主機公用程式
    entries:
    - title: 瞭解 SAN 主機公用程式
      url: "/hu_sanhost_index.html"
    - title: AIX主機公用程式
      entries:
      - title: 版本資訊
        url: "/hu-aix-release-notes.html"
      - title: 安裝 AIX 主機實用程式
        entries:
        - title: 安裝 AIX Host Utilities 8.0
          url: "/hu-aix-80.html"
        - title: 安裝 AIX 主機公用程式 7.0
          url: "/hu-aix-70.html"
        - title: 安裝 AIX Host Utilities 6.1
          url: "/hu_aix_61.html"
      - title: 了解 AIX SAN Tollkit
        url: "/hu-aix-san-toolkit.html"
      - title: AIX Host Utilities 指令參考
        url: "/hu-aix-command-reference.html"
    - title: HP-UX主機公用程式
      entries:
      - title: 版本資訊
        url: "/hu-hpux-release-notes.html"
      - title: 安裝 HP-UX Host Utilities 6.0
        url: "/hu_hpux_60.html"
      - title: 了解 SAN 工具包
        url: "/hu-hpux-sanlun-toolkit.html"
      - title: 了解 HP-UX 指令參考
        url: "/hu_hpux_60_cmd.html"
    - title: Linux主機公用程式
      entries:
      - title: 版本資訊
        url: "/hu-luhu-release-notes.html"
      - title: 安裝Linux主機實用程式
        entries:
        - title: 安裝 Linux Host Utilities 8.0
          url: "/hu-luhu-80.html"
        - title: 安裝 Linux 主機公用程式 7.1
          url: "/hu_luhu_71.html"
      - title: 了解三侖實用程序
        url: "/hu-luhu-sanlun-utility.html"
      - title: Linux 主機實用程式指令參考
        url: "/hu-luhu-command-reference.html"
    - title: Solaris主機公用程式
      entries:
      - title: 版本資訊
        url: "/hu-solaris-release-notes.html"
      - title: 安裝 Solaris 主機公用程式
        entries:
        - title: 安裝 Solaris Host Utilities 8.0
          url: "/hu-solaris-80.html"
        - title: 安裝 Solaris Host Utilities 6.2
          url: "/hu_solaris_62.html"
      - title: 了解 SAN 工具包
        url: "/hu-solaris-san-toolkit.html"
      - title: 了解 Solaris 指令參考
        url: "/hu-solaris-command-reference.html"
    - title: Windows 主機公用程式
      entries:
      - title: 版本資訊
        url: "/hu-wuhu-release-notes.html"
      - title: 安裝 Windows 主機實用程式
        entries:
        - title: 安裝 Windows Host Utilities 8.0
          url: "/hu-wuhu-80.html"
        - title: 安裝 Windows 主機公用程式 7.2
          url: "/hu_wuhu_72.html"
        - title: 安裝 Windows 主機公用程式 7.1
          url: "/hu_wuhu_71.html"
      - title: 配置 Windows 主機實用程式的設定
        url: "/hu_wuhu_hba_settings.html"
      - title: 升級 Windows 主機公用程式
        url: "/hu_wuhu_upgrade.html"
      - title: 修復和移除 Windows 主機公用程式
        url: "/hu_wuhu_repair_remove.html"
      - title: 疑難排解
        url: "/hu_wuhu_troubleshoot.html"
  - title: 使用 FCP 和 iSCSI 設定主機
    entries:
    - title: 總覽
      url: "/hu_fcp_scsi_index.html"
    - title: AIX與PowerVM/VIOS
      entries:
      - title: 7.3/4.x
        url: "/hu-aix-73.html"
      - title: 7.2/3.1
        url: "/hu_aix_72.html"
      - title: 7.1.
        url: "/hu_aix_71.html"
    - title: CentOS
      entries:
      - title: CentOS 8.x
        url: "/hu-centos-8x.html"
      - title: CentOS 7.
        entries:
        - title: '7.9'
          url: "/hu_centos_79.html"
        - title: 7.8%
          url: "/hu_centos_78.html"
        - title: 7.7.7.
          url: "/hu_centos_77.html"
        - title: 7.6.7.
          url: "/hu_centos_76.html"
        - title: '7.5'
          url: "/hu_centos_75.html"
        - title: 7.4.
          url: "/hu_centos_74.html"
        - title: 7.3.
          url: "/hu_centos_73.html"
        - title: '7.2'
          url: "/hu_centos_72.html"
        - title: 7.1.
          url: "/hu_centos_71.html"
        - title: '7.0'
          url: "/hu_centos_70.html"
      - title: CentOS 6.
        entries:
        - title: 6.10.
          url: "/hu_centos_610.html"
        - title: '6.9'
          url: "/hu_centos_69.html"
        - title: 6.8%
          url: "/hu_centos_68.html"
        - title: '6.7'
          url: "/hu_centos_67.html"
        - title: 6.6.6.
          url: "/hu_centos_66.html"
        - title: '6.5'
          url: "/hu_centos_65.html"
        - title: 6.4.
          url: "/hu_centos_64.html"
    - title: Citrix
      entries:
      - title: Xenserver 8.4
        url: "/hu_citrix_84.html"
      - title: 虛擬機器管理程序 8.2
        url: "/hu_citrix_82.html"
    - title: ESXi
      entries:
      - title: VMware vSphere 8.
        url: "/hu_vsphere_8.html"
      - title: VMware vSphere 7
        url: "/hu_vsphere_7.html"
      - title: VMware vSphere 6.5與6.7
        url: "/hu_vsphere_6.html"
    - title: HP-UX
      entries:
      - title: 11i v3
        url: "/hu_hpux_11iv3.html"
    - title: Oracle Linux
      pdf-filename: OA-FCP
      entries:
      - title: Oracle Linux 9.x
        url: "/hu-ol-9x.html"
      - title: Oracle Linux 8.x
        url: "/hu-ol-8x.html"
      - title: Oracle Linux 7
        pdf-filename: ol-7-FCP
        entries:
        - title: '7.9'
          url: "/hu_ol_79.html"
        - title: 7.8%
          url: "/hu_ol_78.html"
        - title: 7.7.7.
          url: "/hu_ol_77.html"
        - title: 7.6.7.
          url: "/hu_ol_76.html"
        - title: '7.5'
          url: "/hu_ol_75.html"
        - title: 7.4.
          url: "/hu_ol_74.html"
        - title: 7.3.
          url: "/hu_ol_73.html"
        - title: '7.2'
          url: "/hu_ol_72.html"
        - title: 7.1.
          url: "/hu_ol_71.html"
        - title: '7.0'
          url: "/hu_ol_70.html"
      - title: Oracle Linux 6
        pdf-filename: ol-6-FCP
        entries:
        - title: 6.10.
          url: "/hu_ol_610.html"
        - title: '6.9'
          url: "/hu_ol_69.html"
        - title: 6.8%
          url: "/hu_ol_68.html"
        - title: '6.7'
          url: "/hu_ol_67.html"
        - title: 6.6.6.
          url: "/hu_ol_66.html"
        - title: '6.5'
          url: "/hu_ol_65.html"
        - title: 6.4.
          url: "/hu_ol_64.html"
    - title: 普羅克斯莫克斯
      entries:
      - title: Proxmox VE 9.0
        url: "/hu-proxmox-ve-9x.html"
    - title: RHEL
      entries:
      - title: RHEL 10
        url: "/hu-rhel-10.html"
        pdf-filename: RHEL-10-FCP
      - title: RHEL 9.x
        url: "/hu-rhel-9x.html"
        pdf-filename: RHEL-9-FCP
      - title: RHEL 8.x
        pdf-filename: RHEL-8-FCP
        url: "/hu-rhel-8x.html"
      - title: RHEL 7
        pdf-filename: RHEL-7-FCP
        entries:
        - title: '7.9'
          url: "/hu_rhel_79.html"
        - title: 7.8%
          url: "/hu_rhel_78.html"
        - title: 7.7.7.
          url: "/hu_rhel_77.html"
        - title: 7.6.7.
          url: "/hu_rhel_76.html"
        - title: '7.5'
          url: "/hu_rhel_75.html"
        - title: 7.4.
          url: "/hu_rhel_74.html"
        - title: 7.3.
          url: "/hu_rhel_73.html"
        - title: '7.2'
          url: "/hu_rhel_72.html"
        - title: 7.1.
          url: "/hu_rhel_71.html"
        - title: '7.0'
          url: "/hu_rhel_70.html"
      - title: RHEL 6
        pdf-filename: RHEL-6-FCP
        entries:
        - title: 6.10.
          url: "/hu_rhel_610.html"
        - title: '6.9'
          url: "/hu_rhel_69.html"
        - title: 6.8%
          url: "/hu_rhel_68.html"
        - title: '6.7'
          url: "/hu_rhel_67.html"
        - title: 6.6.6.
          url: "/hu_rhel_66.html"
        - title: '6.5'
          url: "/hu_rhel_65.html"
        - title: 6.4.
          url: "/hu_rhel_64.html"
    - title: Rocky Linux
      entries:
      - title: Rocky Linux 10
        pdf-filename: RL-10-FCP
        url: "/hu-rockylinux-10.html"
      - title: Rocky Linux 9.x
        pdf-filename: RL-9-FCP
        url: "/hu-rockylinux-9x.html"
      - title: Rocky Linux 8.x
        pdf-filename: RL-8-FCP
        url: "/hu-rockylinux-8x.html"
    - title: Solaris
      entries:
      - title: '11.4'
        url: "/hu-solaris-114.html"
      - title: '11.3'
        url: "/hu_solaris_113.html"
    - title: SUSE Linux Enterprise Server
      entries:
      - title: SUSE Linux Enterprise Server 15
        pdf-filename: sles-15-FCP
        url: "/hu-sles-15spx.html"
      - title: SUSE Linux Enterprise Server 12
        entries:
        - title: 12 SP 5.
          url: "/hu_sles_12SP5.html"
        - title: 12 SP 4.
          url: "/hu_sles_12SP4.html"
        - title: 12 SP 3.
          url: "/hu_sles_12SP3.html"
        - title: 12 SP 2.
          url: "/hu_sles_12SP2.html"
        - title: 12 SP 1
          url: "/hu_sles_12SP1.html"
        - title: '12.'
          url: "/hu_sles_12.html"
    - title: Ubuntu
      pdf-filename: Ubuntu - FCP
      entries:
      - title: '24.04'
        url: "/hu_ubuntu_2404.html"
      - title: '22.04'
        url: "/hu_ubuntu_2204.html"
      - title: '20.04'
        url: "/hu_ubuntu_2004.html"
    - title: Veritas
      entries:
      - title: 資訊量表 9
        url: "/hu-veritas-9x.html"
      - title: Infoscale 8.
        url: "/hu-veritas-8x.html"
      - title: Infoscale 7.
        url: "/hu-veritas-7x.html"
      - title: 儲存基礎6.
        url: "/hu_veritas_6x.html"
    - title: Windows
      pdf-filename: Windows -FCP
      entries:
      - title: '2025'
        url: "/hu-windows-2025.html"
      - title: 2022年
        url: "/hu_windows_2022.html"
      - title: 2019年
        url: "/hu_windows_2019.html"
      - title: 2016年
        url: "/hu_windows_2016.html"
      - title: 2012 R2
        url: "/hu_windows_2012r2.html"
  - title: 使用 NVMe 設定主機
    entries:
    - title: 了解如何設定 NVMe-oF 主機
      url: "/hu-nvme-index.html"
    - title: AIX
      url: "/nvme_aix.html"
    - title: ESXi
      entries:
      - title: VMware vSphere 8.
        url: "/nvme_esxi_8.html"
      - title: VMware vSphere 7
        url: "/nvme_esxi_7.html"
    - title: Oracle Linux
      pdf-filename: NVMeoF OL
      entries:
      - title: ONTAP支援和功能
        url: "/nvme-ol-supported-features.html"
      - title: 9x
        url: "/nvme-ol-9x.html"
      - title: 8x
        url: "/nvme-ol-8x.html"
      - title: 7x
        url: "/nvme-ol-7x.html"
    - title: 普羅克斯莫克斯
      pdf-filename: NVMeoF Proxmox
      entries:
      - title: ONTAP支援和功能
        url: "/nvme-proxmox-supported-features.html"
      - title: Proxmox VE 9x
        url: "/nvme-proxmox-ve-9x.html"
    - title: RHEL
      pdf-filename: NVMeoF RHEL
      entries:
      - title: ONTAP支援和功能
        url: "/nvme-rhel-supported-features.html"
      - title: 10x
        url: "/nvme-rhel-10x.html"
      - title: 9x
        url: "/nvme-rhel-9x.html"
      - title: 8x
        url: "/nvme-rhel-8x.html"
    - title: Rocky Linux
      entries:
      - title: ONTAP支援和功能
        url: "/nvme-rockylinux-supported-features.html"
      - title: 10.x
        url: "/nvme-rockylinux-10x.html"
      - title: 9.x
        url: "/nvme-rockylinux-9x.html"
      - title: 8.x
        url: "/nvme-rockylinux-8x.html"
    - title: SUSE Linux Enterprise Server
      entries:
      - title: SUSE Linux Enterprise Server 15
        entries:
        - title: 15 SP7.
          url: "/nvme_sles15_sp7.html"
        - title: 15 SP6.
          url: "/nvme_sles15_sp6.html"
        - title: 15 sp5
          url: "/nvme_sles15_sp5.html"
        - title: 15 SP4
          url: "/nvme_sles15_sp4.html"
        - title: 15 SP3
          url: "/nvme_sles15_sp3.html"
        - title: 15 SP2
          url: "/nvme_sles15_sp2.html"
        - title: 15 SP1
          url: "/nvme_sles15_sp1.html"
    - title: Ubuntu
      entries:
      - title: '24.04'
        url: "/nvme_ubuntu_2404.html"
      - title: '22.04'
        url: "/nvme_ubuntu_2204.html"
    - title: Windows
      entries:
      - title: '2025'
        url: "/nvme-windows-2025.html"
      - title: 2022年
        url: "/nvme_windows_2022.html"
      - title: 2019年
        url: "/nvme_windows_2019.html"
      - title: 2016年
        url: "/nvme_windows_2016.html"
      - title: 2012 R2
        url: "/nvme_windows_2012r2.html"
    - title: 疑難排解
      url: "/troubleshoot.html"
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
