---
sidebar: sidebar 
permalink: troubleshoot.html 
keywords: host utilities, veritas, infoscale, 8.x, netapp, ontap, vmware, vspehere 
summary: 您可以使用 FC 、 FCoE 和 iSCSI 通訊協定、為 VMware vSphere 8.x 版本設定 ONTAP SAN 主機設定。 
---
= 疑難排解
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
針對 RHEL 、 OL 和 SUSE Linux Enterprise Server 主機的任何 NVMe 故障進行疑難排解之前、請先確認您執行的組態符合互通性對照表工具（ IMT ）規格、然後繼續後續步驟、以偵錯任何主機端問題。


NOTE: 疑難排解指示不適用於 AIX 、 Windows 和 ESXi 主機。



== 啟用詳細記錄

如果您的組態有問題、詳細記錄可提供疑難排解的必要資訊。

設定 Qlogic （ qla2xxx ）詳細記錄的程序與設定 lpfc 詳細記錄的程序不同。

[role="tabbed-block"]
====
.lpfc
--
設定適用於 NVMe / FC 的 lpfc 驅動程式。

.步驟
. 設定 `lpfc_log_verbose` 將驅動程式設定為下列任一值、以記錄NVMe/FC事件。
+
[listing]
----
#define LOG_NVME 0x00100000 /* NVME general events. */
#define LOG_NVME_DISC 0x00200000 /* NVME Discovery/Connect events. */
#define LOG_NVME_ABTS 0x00400000 /* NVME ABTS events. */
#define LOG_NVME_IOERR 0x00800000 /* NVME IO Error events. */
----
. 設定值之後、請執行 `dracut-f` 命令並重新啟動主機。
. 驗證設定。
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf options lpfc lpfc_log_verbose=0xf00083

# cat /sys/module/lpfc/parameters/lpfc_log_verbose 15728771
----


--
.qla2xxx
--
NVMe / FC 沒有類似於的特定 qla2xxx 記錄 `lpfc` 驅動程式：請改為設定一般 qla2xxx 記錄層級。

.步驟
. 將「ql2xextend_error_logging=x1e400000」值附加至對應的「modf探測qla2xxx conf」檔案。
. 執行 `dracut -f` 命令、然後重新啟動主機。
. 重新開機後、請確認已啟用詳細資訊記錄：
+
[listing]
----
# cat /etc/modprobe.d/qla2xxx.conf
----
+
輸出範例：

+
[listing]
----
options qla2xxx ql2xnvmeenable=1 ql2xextended_error_logging=0x1e400000
# cat /sys/module/qla2xxx/parameters/ql2xextended_error_logging
507510784
----


--
====


=== 常見的NVMe-CLI錯誤和因應措施

顯示的錯誤 `nvme-cli` 期間 `nvme discover`、 `nvme connect`或 `nvme connect-all` 作業與因應措施如下表所示：

[cols="20, 20, 50"]
|===
| 錯誤訊息 | 可能原因 | 因應措施 


| 「寫入/dev/NVMe架構失敗：無效的引數」 | 語法不正確 | 請確認您使用的語法正確 `nvme discover`、 `nvme connect`和 `nvme connect-all` 命令。 


| 「寫入/dev/NVMe架構失敗：沒有這類檔案或目錄」 | 例如、多個問題可能會觸發這種情況、例如為NVMe命令提供錯誤的引數是常見原因之一。  a| 
* 確認您已將正確的引數（例如、正確的WWNN字串、WWPN字串等）傳遞給命令。
* 如果引數正確、但您仍看到此錯誤、請檢查是否有 `/sys/class/scsi_host/host*/nvme_info` 命令輸出正確、NVMe啟動器顯示為 `Enabled`和NVMe / FC目標LIF會正確顯示在遠端連接埠區段下方。範例：
+
[listing]
----

# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
NVME LPORT lpfc0 WWPN x10000090fae0ec9d WWNN x20000090fae0ec9d DID x012000 ONLINE
NVME RPORT WWPN x200b00a098c80f09 WWNN x200a00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000071 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a6 Outstanding 0000000000000001
NVME Initiator Enabled
NVME LPORT lpfc1 WWPN x10000090fae0ec9e WWNN x20000090fae0ec9e DID x012400 ONLINE
NVME RPORT WWPN x200900a098c80f09 WWNN x200800a098c80f09 DID x010301 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000073 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a8 Outstanding 0000000000000001
----
* 如果目標生命量未如上述所示顯示於 `nvme_info` 命令輸出、請檢查 `/var/log/messages` 和 `dmesg` 針對任何可疑的NVMe/FC故障、提供命令輸出、並據此報告或修正。




| 「沒有要擷取的探索記錄項目」  a| 
一般在下列情況下觀察 `/etc/nvme/hostnqn` 字串尚未新增至NetApp陣列上的對應子系統、或是不正確 `hostnqn` 字串已新增至各自的子系統。
 a| 
確認正確無誤 `/etc/nvme/hostnqn` 字串會新增至NetApp陣列上的對應子系統（請使用 `vserver nvme subsystem host show` 命令）。



| 「寫入/dev/NVMe架構失敗：作業已在進行中」  a| 
觀察控制器關聯或指定作業已建立或正在建立的過程。這可能是上述安裝之自動連線指令碼的一部分。
 a| 
無。請嘗試執行 `nvme discover` 一段時間後再次命令。適用於 `nvme connect` 和 `connect-all`、執行 `nvme list` 命令來驗證命名空間裝置是否已建立並顯示在主機上。

|===


== 何時聯絡技術支援

如果您仍面臨問題、請收集下列檔案和命令輸出及聯絡人 link:mysupport.netapp.com["NetApp支援"^] 進一步分類：

[listing]
----
cat /sys/class/scsi_host/host*/nvme_info
/var/log/messages
dmesg
nvme discover output as in:
nvme discover --transport=fc --traddr=nn-0x200a00a098c80f09:pn-0x200b00a098c80f09 --host-traddr=nn-0x20000090fae0ec9d:pn-0x10000090fae0ec9d
nvme list
nvme list-subsys /dev/nvmeXnY
----