= 
:allow-uri-read: 


.步驟
根據您的配置，選擇 UEK 3 或 UEK 4 標籤。

[role="tabbed-block"]
====
.UEK 3
--
啟用和停用 ALUA 的 Oracle Linux UEK 3 設定都會自動更新。設定更新後，您需要啟用「ALUA 處理程序」：

. 建立initrd-image的備份。
. 將以下參數值附加到核心以使 ALUA 和非 ALUA 正常工作：
+
[source, cli]
----
rdloaddriver=scsi_dh_alua
----
+
.輸出範例
[listing]
----
kernel /vmlinuz-3.8.13-68.1.2.el6uek.x86_64 ro root=/dev/mapper/vg_ibmx3550m421096-lv_root rd_NO_LUKSrd_LVM_LV=vg_ibmx3550m421096/lv_root LANG=en_US.UTF-8 rd_NO_MDSYSFONT=latarcyrheb-sun16 crashkernel=256M KEYBOARDTYPE=pc KEYTABLE=us rd_LVM_LV=vg_ibmx3550m421096/lv_swap rd_NO_DM rhgb quiet rdloaddriver=scsi_dh_alua
----
. 重新建立 initrd 映像：
+
[source, cli]
----
dracut -f
----
. 重新啟動主機。
. 查看 `cat /proc/cmdline`命令來驗證設定是否完成。


--
.UEK 4
--
對於 Oracle Linux UEK 4，驗證 `/etc/multipath.conf`檔案已定義，並且已為您的 ONTAP LUN 設定了 NetApp 建議的設定。

. 確認 `/etc/multipath.conf`檔案已結束。如果檔案不存在，請建立空白的零位元組檔案：
+
[source, cli]
----
touch /etc/multipath.conf
----
. 第一次 `multipath.conf`建立檔案時，您可能需要啟用並啟動多重路徑服務，才能載入建議的設定：
+
[source, cli]
----
chkconfig multipathd on
----
+
[source, cli]
----
/etc/init.d/multipathd start
----
. 每次引導主機時，空的 `/etc/multipath.conf`零位元組檔案會自動載入 NetApp 建議的主機多重路徑參數作為預設設定。您不需要變更 `/etc/multipath.conf`主機的檔案，因為作業系統會使用多重路徑參數進行編譯，以正確辨識及管理 ONTAP LUN 。
+
.顯示參數設定
[%collapsible]
=====
[cols="2"]
|===
| 參數 | 設定 


| DETECT（偵測）_prio | 是的 


| 開發損失_tmo | "無限遠" 


| 容錯回復 | 立即 


| fast_io_f故障_tmo | 5. 


| 功能 | "2 pg_init_retries 50" 


| Flip_on_last刪除 | "是" 


| 硬體處理常式 | 「0」 


| no_path_retry | 佇列 


| path_checker_ | "周" 


| path_grouping_policy | "群組by_prio" 


| path_selector | "服務時間0" 


| Polling_時間 間隔 | 5. 


| 優先 | 「NetApp」ONTAP 


| 產品 | LUN 


| Retain附加的硬體處理常式 | 是的 


| RR_weight | "統一" 


| 使用者易記名稱 | 否 


| 廠商 | NetApp 
|===
=====
. 驗證 ONTAP LUN 的參數設定和路徑狀態：
+
[source, cli]
----
multipath -ll
----
+
預設多路徑參數支援AFF和FAS配置。在這些組態中，單一 ONTAP LUN 不應需要四個以上的路徑。如果路徑超過四條，可能會在儲存設備故障期間導致路徑問題。

+
AFF 或 FAS 組態應該有兩個路徑群組，優先順序較高或較低。較高優先順序的主動 / 最佳化路徑由集合所在的控制器提供服務。較低優先順序的路徑是作用中的，但未最佳化，因為它們是由不同的控制器提供服務。非最佳化路徑只有在最佳化路徑無法使用時才會使用。

+
以下範例輸出顯示了具有兩個主動/最佳化路徑和兩個主動/非最佳化路徑的 AFF 或 FAS 配置中 ONTAP LUN 的正確參數設定和路徑狀態：

+
.顯示範例
[%collapsible]
=====
[listing]
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
=====


--
====