= 
:allow-uri-read: 


* 。 `multipath.conf` 檔案必須存在、多重路徑常駐程式才能啟動、但您可以使用下列命令來建立空的零位元組檔案：
`touch /etc/multipath.conf`。
* 第一次建立此檔案時、可能需要啟用及啟動多重路徑服務。


[listing]
----
# chkconfig multipathd on
# /etc/init.d/multipathd start
----
* 無需直接在中新增任何內容 `multipath.conf` 除非您有不想要多重路徑管理的裝置、或現有的設定會覆寫預設值、否則請勿使用檔案。
* 您可以將下列語法新增至「multiPath.conf」檔案、以排除不需要的裝置。
* 將 <DevId> 取代為您要排除的裝置 WWID 字串：


....
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
....
.範例
在此範例中、 `sda` 是我們需要新增至黑名單的本機SCSI磁碟。

. 執行下列命令來判斷WWID：
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
. 將此WWID新增至/etc/multipath.conf中的「黑名單」節：
+
....
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
....


您應該隨時檢查 `/etc/multipath.conf` 舊版設定的檔案、尤其是在預設值區段中、可能會覆寫預設設定。

下表顯示要徑 `multipathd` 支援的參數ONTAP 和所需的值。如果主機已從其他廠商連接至 LUN 、而且這些參數中的任何一個都會被覆寫、則必須在中的稍後方例項加以修正 `multipath.conf` 特別適用於ONTAP 整個LUN的檔案。如果沒有這麼做、ONTAP 則可能無法如預期般運作。只有在完全瞭解影響的情況下、您才應諮詢 NetApp 和 / 或作業系統廠商、以覆寫這些預設值。
