= 
:allow-uri-read: 


. 如果您的儲存配置包括MetroCluster、Oracle Solaris 虛擬化或SnapMirror活動同步，請變更預設值：
+
[role="tabbed-block"]
====
.MetroCluster
--
預設情況下，如果到 LUN 的所有路徑都遺失，Solaris OS 將在 *20 秒* 後無法執行 I/O 操作。這是由 `fcp_offline_delay`範圍。預設值為 `fcp_offline_delay`適用於標準ONTAP集群。但是，在MetroCluster配置中，您必須增加 `fcp_offline_delay`至 *120 秒*，以確保 I/O 在操作期間不會過早逾時，包括計劃外的故障轉移。

有關MetroCluster預設設定的其他資訊和建議更改，請參閱知識庫文章 https://kb.netapp.com/onprem/ontap/metrocluster/Solaris_host_support_considerations_in_a_MetroCluster_configuration["Solaris主機支援MetroCluster 考量的功能"^]。

--
.Oracle Solaris虛擬化
--
** Solaris 虛擬化選項包括 Solaris 邏輯域（也稱為 LDOM 或 Oracle VM Server for SPARC）、Solaris 動態域、Solaris 區域和 Solaris 容器。這些技術也被稱為「Oracle虛擬機器」。
** 您可以一起使用多個選項，例如，特定 Solaris 邏輯域內的 Solaris 容器。
** NetApp支援使用 Solaris 虛擬化技術，其中整體配置由 Oracle 支持，並且任何可直接存取 LUN 的分區都列在link:https://imt.netapp.com/matrix/#welcome["IMT"]在受支援的配置中。這包括根容器、LDOM I/O 域和使用 NPIV 存取 LUN 的 LDOM。
** 僅使用虛擬化儲存資源的分區或虛擬機，例如 `vdsk`，不需要特定資格，因為他們無法直接存取ONTAP LUN。您只需驗證對底層 LUN 具有直接存取權限的分割區或虛擬機器（例如 LDOM I/O 網域）是否會列在link:https://imt.netapp.com/matrix/#welcome["IMT"^]。


.步驟
當 LUN 用作 LDOM 內的虛擬磁碟設備時，LUN 的來源會被虛擬化屏蔽，且 LDOM 無法正確偵測區塊大小。為了防止此問題：

.. 為 LDOM OS 修補_Oracle Bug 15824910_
.. 創建一個 `vdc.conf`將虛擬磁碟的區塊大小設定為 `4096`。有關詳細信息，請參閱 Oracle DOC：2157669.1。
.. 驗證補丁安裝以確保已正確配置建議的設定：
+
... 建立 zpool：
+
[source, cli]
----
zpool create zpool_name disk_list
----
... 執行 `zdb -C` 檢查 zpool 並驗證 *ashift* 的值是否爲 `12`。
+
如果 *ashift* 的值不是 `12`，重新運行 `zdb -C11`，並驗證是否安裝了正確的補丁並重新檢查 `vdc.conf`。

+
直到 *ashift* 顯示值 `12`。






NOTE: 針對多個 Solaris 版本上的 Oracle 錯誤 15824910 提供了補丁。如果您需要協助確定最佳核心補丁，請聯絡 Oracle。

--
.SnapMirror主動同步
--
從ONTAP 9.9.1 開始，Solaris 主機支援SnapMirror主動同步設定配置。若要驗證在SnapMirror主動同步環境中發生排程外站點故障轉移切換時 Solaris 用戶端應用程式是否不會中斷，必須設定 `scsi-vhci-failover-override`Solaris 主機上的設定。此設定覆蓋故障轉移模組 `f_tpgs`阻止執行偵測到矛盾的程式碼路徑。

.步驟
.. 建立設定檔 `/etc/driver/drv/scsi_vhci.conf`對於連接到主機的NetApp儲存類型，其項目類似於以下範例：
+
[listing]
----
scsi-vhci-failover-override =
"NETAPP  LUN","f_tpgs"
----
.. 驗證覆蓋參數是否已成功套用：
+
[source, cli]
----
devprop
----
+
[source, cli]
----
mdb
----
+
.顯示範例
[%collapsible]
=====
[listing]
----
root@host-A:~# devprop -v -n /scsi_vhci scsi-vhci-failover-override      scsi-vhci-failover-override=NETAPP  LUN + f_tpgs
root@host-A:~# echo "*scsi_vhci_dip::print -x struct dev_info devi_child | ::list struct dev_info devi_sibling| ::print struct dev_info devi_mdi_client| ::print mdi_client_t ct_vprivate| ::print struct scsi_vhci_lun svl_lun_wwn svl_fops_name"| mdb -k
----
[listing]
----
svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----
=====



NOTE: 之後 `scsi-vhci-failover-override` 已套用、 `conf` 已新增至 `svl_fops_name`。如需更多資訊及預設設定的建議變更、請參閱 NetApp 知識庫文件 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Solaris_Host_support_recommended_settings_in_SnapMirror_Business_Continuity_(SM-BC)_configuration["Solaris 主機支援 SnapMirror 主動式同步組態中的建議設定"^]。

--
====

